window.DINNERLIST = [
"Bacon and eggs",
"Baked potatoes",
"Bánh mì",
"Barbecue ribs",
"Beef and broccoli",
"Beef dip sandwich",
"Beef short ribs",
"Beef stroganoff",
"Bibimbap",
"Biscuits and gravy",
"BLT sandwich",
"Breakfast burrito",
"Breakfast for dinner",
"Brisket",
"Burgers",
"Buffalo chicken wrap",
"Burritos",
"Butter chicken",
"Calzone",
"Caesar salad",
"Caprese salad",
"Charcuterie plate",
"Chicken adobo",
"Chicken and dumplings",
"Chicken and waffles",
"Chicken burrito bowl",
"Chicken cordon bleu",
"Chicken curry",
"Chicken fingers",
"Chicken fried steak",
"Chicken jambalaya",
"Chicken pot pie",
"Chicken soo gai",
"Chicken wings",
"Chili",
"Chili cheese dogs",
"Chimichangas",
"Chop suey",
"Club sandwich",
"Cobb salad",
"Coconut curry",
"Corned beef and cabbage",
"Crab cakes",
"Crab legs",
"Cubano sandwich",
"Curry",
"Detroit style pizza",
"Dirty rice and sausage",
"Donair",
"Dumplings",
"Eggplant parmesan",
"Enchiladas",
"English muffin breakfast sandwiches",
"Falafels",
"Fettuccine alfredo",
"Fish and chips",
"Fish tacos",
"French dip sandwich",
"French onion soup",
"Fried chicken",
"Fried rice",
"Garlic shrimp",
"General Tso's chicken",
"Gnocchi",
"Greek salad",
"Green curry",
"Grilled cheese and tomato soup",
"Grilled chicken and vegetables",
"Grilled shrimp",
"Gyros",
"Ham and cheese sandwich",
"Hot dogs",
"Italian sub sandwich",
"Jambalaya",
"Jerk chicken",
"Kebabs",
"Korean BBQ bowl",
"Kung pao chicken",
"Lamb chops",
"Lasagna",
"Lemon chicken",
"Lo mein",
"Lobster",
"Lobster roll",
"Mac and cheese",
"Margherita pizza",
"Mashed potatoes and gravy",
"Meatball subs",
"Meatballs and pasta",
"Meatloaf",
"Mushroom risotto",
"Nachos",
"Naan and curry",
"Nashville chicken sandwich",
"Omelette",
"Orange chicken",
"Pad Thai",
"Panzerotti",
"Pasta",
"Pasta alfredo",
"Pasta carbonara",
"Pasta bolognese",
"Perogies",
"Philly cheesesteak",
"Pho",
"Pizza",
"Pizza casserole",
"Poke bowl",
"Pork chops",
"Pork tenderloin",
"Popcorn shrimp",
"Pot roast",
"Poutine",
"Prime rib",
"Pulled pork",
"Quesadilla",
"Quiche",
"Quinoa bowl",
"Ramen",
"Ravioli",
"Ribeye steak",
"Roast chicken",
"Roast sticky chicken",
"Roasted vegetables and rice",
"Roti and curry",
"Salmon",
"Sausage and peppers",
"Scalloped potatoes",
"Schnitzel",
"Sea bass",
"Sesame chicken",
"Shawarma",
"Shepherd's pie",
"Short ribs",
"Shrimp boil",
"Shrimp tacos",
"Sloppy joes",
"Smash burgers",
"Soba noodles",
"Souvlaki",
"Spaghetti and meatballs",
"Spinach and feta stuffed chicken",
"Steak and frites",
"Steak au poivre",
"Stir fry",
"Stir fry and rice",
"Stuffed pasta shells",
"Sushi",
"Sweet and sour chicken",
"Sweet potato casserole",
"Szechuan noodles",
"Tacos",
"Teriyaki chicken",
"Thai noodles with peanut sauce",
"Tikka masala",
"Tomato soup and grilled cheese",
"Tortilla soup",
"Tuna",
"Twice baked potatoes",
"Udon noodle bowl",
"Veggie burger",
"Vindaloo",
"Yellow curry",
"American comfort food",
"Barbecue",
"Chinese",
"Greek",
"Indian",
"Italian",
"Japanese",
"Korean",
"Mexican",
"Middle Eastern",
"Thai",
"Vietnamese",
"French",
"Spanish tapas",
"Caribbean",
"Ethiopian",
"Brazilian",
"Cuban",
"German",
"Polish",
"Filipino",
"Turkish",
"Lebanese",
"Peruvian",
"Malaysian",
"Hawaiian",
"Soul food",
"Southern",
"Street food",
"Seafood",
"Comfort food",
"Tapas",
"Dim sum",
"Hot pot",
"Try a restaurant you've never been to",
"Try a food truck",
"Order something you've never tried before",
"Something spicy",
"Pub food",
"Raw plant-based meal",
"Fresh oysters",
];
