window.DINNERLIST = [
  // A
  "Adam's ribs",
  "Alfredo pasta",
  "Alfredo with chicken",
  "Almond crusted chicken",
  "American chop suey",
  "Angus burgers",
  "Antipasto plate",
  "Apple and brie grilled cheese",
  "Arancini",
  "Asian chicken salad",
  "Asian noodle bowl",
  "Authentic Italian tomato sauce with pasta",
  "Award winning chili",

  // B
  "Bacon and eggs",
  "Bacon cheeseburger",
  "Bacon mac and cheese",
  "Bacon wrapped chicken",
  "Bagel sandwich",
  "Baked chicken leg quarters",
  "Baked corned beef brisket",
  "Baked penne",
  "Baked ziti",
  "Baklava salmon",
  "Balsamic chicken with peppers and onions",
  "Barbecued pulled pork",
  "Barbecue ribs",
  "BBQ chicken pizza",
  "BBQ pulled chicken sandwiches",
  "BBQ pulled pork sandwich",
  "BBQ ribs and coleslaw",
  "Beef and broccoli",
  "Beef and rice bowl",
  "Beef burrito",
  "Beef dip sandwich",
  "Beef enchiladas",
  "Beef pho",
  "Beef short ribs",
  "Beef stir fry",
  "Beef stroganoff",
  "Beef tacos",
  "Beer battered fish and chips",
  "Bibimbap",
  "Birria tacos",
  "Biscuits and gravy",
  "Black bean burrito",
  "Black bean tacos",
  "BLT sandwich",
  "Breakfast burrito",
  "Breakfast for dinner",
  "Brisket sandwich",
  "Broiled steak",
  "Brown sugar glazed corned beef",
  "Bulgogi bowl",
  "Butter chicken",
  "Butter chicken and rice",

  // C
  "California shrimp tacos",
  "Calzone",
  "Caprese salad",
  "Carbonara",
  "Carnitas tacos",
  "Cheddar garlic chicken",
  "Cheeseburger and fries",
  "Cheesy chicken parmesan",
  "Cheesy hashbrown casserole",
  "Cheesy potato and sausage casserole",
  "Chicken adobo",
  "Chicken and dumplings",
  "Chicken and rice",
  "Chicken burrito bowl",
  "Chicken cordon bleu casserole",
  "Chicken curry",
  "Chicken fried steak",
  "Chicken jambalaya",
  "Chicken laz﻿one",
  "Chicken parmesan",
  "Chicken pot pie",
  "Chicken scaloppine",
  "Chicken schnitzel",
  "Chicken shawarma bowl",
  "Chicken stir fry",
  "Chicken tacos",
  "Chicken tenders and fries",
  "Chicken tikka masala",
  "Chicken tortilla soup",
  "Chicken wings",
  "Chicken with lemon glaze",
  "Chili cheese dogs",
  "Chimichanga",
  "Chorizo tacos",
  "Classic baked spaghetti",
  "Classic meatloaf",
  "Club sandwich",
  "Cobb salad",
  "Copycat orange chicken",
  "Corned beef and cabbage",
  "Creamy Cajun chicken pasta",
  "Creamy turkey tetrazzini",
  "Crispy baked chicken",
  "Cross rib roast",
  "Cuban sandwich",

  // D
  "Dal and rice",
  "Deli sandwich",
  "Detroit style pizza",
  "Dirty rice and sausage",
  "Donair",
  "Drunken garlic roast",
  "Dumplings",

    // E
  "Eggplant parmesan",
  "Enchiladas",
  "English muffin breakfast sandwiches",
  "Everything bagel sandwich",

  // F
  "Falafel wrap",
  "Fettuccine alfredo",
  "Fish and chips",
  "Fish tacos",
  "Flatbread pizza",
  "French dip sandwich",
  "French onion burgers",
  "French onion soup",
  "Fried chicken",
  "Fried chicken sandwich",
  "Fried rice",
  "Funeral potatoes",

  // G
  "Garlic alfredo pasta",
  "Garlic and herb pork chops",
  "Garlic butter shrimp",
  "General Tso's chicken",
  "Gnocchi with tomato sauce",
  "Grilled cheese and tomato soup",
  "Grilled chicken and vegetables",
  "Grilled shrimp",
  "Ground beef gyros",

  // H
  "Hamburgers",
  "Ham and cheese sandwich",
  "Honey mustard pork chops",
  "Honey roasted pork loin",
  "Hot dogs",
  "Hot honey fried chicken sandwich"
  // I
  "Italian beef sandwich",
  "Italian sausage and peppers",
  "Italian sub sandwich",

  // J
  "Jambalaya",
  "Japanese chicken and rice",
  "Jerk chicken and rice",
  "Jumbo shrimp parmesan",

  // K
  "Kung pao chicken",
  "Korean BBQ bowl",
  "Korean popcorn chicken",
  "Korean roast chicken",
  "Korean style beef bowl",

  // L
  "Lamb chops",
  "Lamb gyros",
  "Lasagna",
  "Lemon chicken",
  "Lemon garlic salmon",
  "Lobster roll",
  "Low and slow oven baked ribs",

  // M
  "Mac and cheese",
  "Macaroni and cheese",
  "Make-ahead twice baked potatoes",
  "Margherita pizza",
  "Maryland crab cakes",
  "Mashed potatoes and gravy",
  "Meatball subs",
  "Meatballs and pasta",
  "Mexican shepherd's pie",
  "Miso salmon",
  "Mushroom risotto",

  // N
  "Nachos",
  "Naan and curry",
  "New York strip steak",
  "Noodle stir fry",

  // O
  "Old Bay shrimp boil",
  "Old-fashioned pan fried pork chops",
  "Omelette and toast",
  "Orange chicken",
  "Oven baked chicken",
  "Oven baked sea bass",
  "Oven fried chicken chimichangas",

  // P
  "Pad Thai",
  "Panda Express orange chicken",
  "Parmesan crusted salmon",
  "Pasta primavera",
  "Pasta with sausage and cream",
  "Peanut noodles",
  "Pepperoni pizza",
  "Philly cheesesteak",
  "Pizza",
  "Pizza casserole",
  "Poke bowl",
  "Pork chops and potatoes",
  "Pork tenderloin",
  "Pot roast",
  "Pressure cooker short ribs",
  "Pulled pork sandwich",

  // Q
  "Quesadilla",
  "Quiche",
  "Quinoa bowl",

  // R
  "Ramen",
  "Ravioli",
  "Ravioli lasagna",
  "Red curry and rice",
  "Roast chicken",
  "Roast sticky chicken",
  "Roasted vegetables and rice",
  "Roti and curry",

  // S
  "Salmon and rice",
  "Sausage and peppers",
  "Sausage and potatoes",
  "Scalloped potatoes and ham",
  "Sea bass and vegetables",
  "Sesame chicken",
  "Sheet pan tacos",
  "Shepherd's pie",
  "Shrimp boil",
  "Shrimp fried rice",
  "Shrimp scampi",
  "Shrimp tacos",
  "Shredded chicken sandwiches",
  "Skillet tarragon chicken",
  "Sloppy joes",
  "Smash burgers",
  "Soba noodles",
  "Souvlaki and pita",
  "Spanish pork",
  "Spaghetti and meatballs",
  "Spinach and feta stuffed chicken",
  "Steak and baked potato",
  "Steak frites",
  "Stir fry and rice",
  "Stuffed pasta shells",
  "Sweet and sour chicken",
  "Sweet potato casserole",
  "Szechuan noodles",

  // T
  "Tacos",
  "Teriyaki chicken bowl",
  "Thai grilled chicken",
  "Thai noodles with peanut sauce",
  "Thin crust pizza",
  "Tilapia and rice",
  "Tomato soup and grilled cheese",
  "Tortilla soup",
  "Turkey tetrazzini",
  "Twice baked potatoes",

  // U
  "Udon noodle bowl",
  "Ultimate salmon fillets",

  // V
  "Veggie burger",
  "Veggie stir fry",
  "Vegetable curry",
  "Vegetable fried rice",

  // W
  "Waffle fried chicken",
  "Wings and fries",
  "Wrap and salad",

  // Y
  "Yellow curry and rice",

  // Z
  "Ziti and meat sauce",
  "Zuppa toscana",
];
