window.FORTUNES = [
  "A gentle breeze brings your luck into view.",
  "Your luck grows where your heart feels light.",
  "A calm moment carries your best opportunity.",
  "A bright thought becomes your next lucky idea.",
  "Luck waits for you in the quiet spaces.",
  "A new connection brings unexpected fortune.",
  "Something small becomes surprisingly important.",
  "Lucky paths open where curiosity leads.",
  "Your next idea has the power to delight.",
  "Let your kindness circle back as luck.",
  "A soft answer today makes tomorrow clearer.",
  "The right choice feels simple when it arrives.",
  "Peace invites luck to stay awhile with you.",
  "A smile is the first step toward luck.",
  "Good fortune flutters in on quiet wings.",
  "Your next chance arrives when you least expect it.",
  "A single thought can change your direction.",
  "A refreshed mind attracts fortunate moments.",
  "Where you focus your calm, luck gathers.",
  "Lucky surprises hide in everyday moments.",
  "Open yourself to small miracles today.",
  "Your next success starts with a gentle breath.",
  "Luck sees you clearly when you trust yourself.",
  "A trusting heart finds joyful openings.",
  "A moment of stillness reveals new luck.",
  "The path forward becomes visible at dawn.",
  "Your hope invites the bright moments to come.",
  "A playful idea becomes real sooner than you think.",
  "Your courage shines luck into your day.",
  "A fresh perspective makes luck feel closer.",
  "Lucky signs appear in ordinary places.",
  "A creative notion becomes your next break.",
  "The seeds of luck grow where you nurture them.",
  "Your next step feels like resonance.",
  "A simple choice returns abundant peace.",
  "Luck flows to you through calm persistence.",
  "Something joyful enters through a small decision.",
  "Your clarity attracts fortunate paths.",
  "When your mind is open, luck enters easily.",
  "A soft smile changes the shape of chance.",
  "Be curious and watch your fortune grow.",
  "Your goodwill becomes someone’s unexpected gift.",
  "Even a quiet thought can sparkle with luck.",
  "An ordinary day may hold your lucky turn.",
  "A light heart brings the richest kind of luck.",
  "Your next opportunity arrives after a clear choice.",
  "A tranquil mind makes room for lucky thoughts.",
  "The sun finds a way to warm every willing heart.",
  "Your confidence invites good fortune to stay.",
  "Luck favors those who keep showing up.",
  "The next path forward reveals itself quietly.",
  "A brave heart makes space for pleasant surprises.",
  "A song you hear today becomes tomorrow’s luck.",
  "Your positive intention lights the smallest chance.",
  "A small delight today leads to a bigger one tomorrow.",
  "Your peace of mind becomes your best asset.",
  "Lucky chances are born from sincere beginnings.",
  "An unexpected smile brings delightful luck.",
  "New ideas enrich your journey with luck.",
  "Where your attention flows, luck tends to follow.",
  "Your next decision becomes your next blessing.",
  "A spark of imagination leads you to luck.",
  "Fortune settles where patience dwells.",
  "Your gentlest effort leads to obvious progress.",
  "An open heart finds luck in the unexpected.",
  "A warm thought becomes tomorrow’s good news.",
  "Luck finds you when you embrace kindness first.",
  "Your next lucky turn arrives with a calm mind.",
  "The smallest action becomes your greatest gift.",
  "Joyful moments arrive in quiet waves.",
  "Your compassion creates unseen good fortune.",
  "Luck rises when you are steady inside.",
  "Miracles seem ordinary from the right angle.",
  "A kind heart navigates towards luck.",
  "Your clarity makes the complicated simple.",
  "A quiet kindness makes fortune smile at you.",
  "A small gesture becomes a memorable moment.",
  "Your patience unfolds good results like flowers.",
  "Turn toward joy and luck walks by your side.",
  "Luck visits when you welcome new beginnings.",
  "Happiness blooms where your curiosity grows.",
  "The next horizon appears when you look up.",
  "Your gentle confidence attracts good paths.",
  "A fresh start feels like sunlight on water.",
  "Opportunity sits quietly behind familiar doors.",
  "Your trustworthy nature draws good fortune close.",
  "The moment you embrace possibility, luck listens.",
  "What seems simple today becomes bigger later.",
  "A restful mind reads signs others overlook.",
  "Your next lucky turn hides in plain sight.",
  "Careful listening uncovers unexpected insight.",
  "A joyful pause before action brings clarity.",
  "Your next dream feels closer than it seems.",
  "Peaceful choices make room for lucky change.",
  "Good fortune rests where your heart is steady.",
  "A warm breath before acting brightens your luck.",
  "One kind thought becomes many good ones.",
  "Your next lucky break might start with curiosity.",
  "Stay open and the next blessing falls into place.",
  "A mindful walk brings a clear, new idea.",
  "Your calm focus shapes your most fortunate days.",
  "Lucky moments arrive quietly like petals falling.",
  "Your next joy hides in a place you already know.",
  "A generous word returns as warm good luck.",
  "Your reflection today reveals tomorrow’s strength.",
  "The best luck feels like breathing with ease.",
  "A content heart finds luck beneath simple things.",
  "Genuine gratitude grows luck in unexpected ways.",
  "The next surprise feels like a welcome friend.",
  "Fortune listens to those who pay attention.",
  "Your ease attracts people who share good fortune.",
  "Every calm decision builds future opportunity.",
  "Luck feels easiest when your mind is clear.",
  "Your instinct guides you toward welcoming turns.",
  "Good fortune flows in paths of least resistance.",
  "Small chances add up to remarkable progress.",
  "When you honor silence, clarity follows soon.",
  "Your next calm choice becomes your bright memory.",
  "A peaceful heart finds more luck than a restless one.",
  "Serendipity walks with those who stay kind.",
  "Your next clear thought becomes tomorrow’s advantage.",
  "Smile at possibility, and it smiles back.",
  "Gentle confidence becomes your invisible luck.",
  "Your next idea knocks on the door quietly.",
  "Patience and readiness make luck feel natural.",
  "An unhurried mind catches hidden opportunities.",
  "Your warmth brightens every ordinary moment.",
  "Even the smallest step leads to noticeable progress.",
  "A calm mind lets fortune find its way to you.",
  "Luck is simply the pattern of moments aligned.",
  "Your next triumph begins with a trusting breath.",
  "Fortune feels natural when you welcome newness.",
  "Every good fortune starts with humble hope.",
  "A gentle compassion opens doors worth walking through.",
  "Good luck hides where kindness has been planted.",
  "The next perfect moment unfolds without strain.",
  "Your inner stillness creates steady, good fortune.",
  "A brave choice today becomes tomorrow’s delight.",
  "Peaceful momentum brings encouraging results.",
  "Open eyes and a joyful heart make luck obvious.",
  "Your next idea carries a rare kind of luck.",
  "Kind imagination becomes your strongest luck.",
  "The beginnings of luck often look like small steps.",
  "When your hands are open, so is your fortune.",
  "Luck grows softly where gratitude blooms."
];
