window.FUNFACTS = [
"Octopuses have three hearts.",
"A day on Venus is longer than a year on Venus.",
"Bananas are berries, but strawberries are not.",
"Sharks existed before trees.",
"Honey never spoils.",
"The Eiffel Tower grows taller in summer.",
"A group of flamingos is called a flamboyance.",
"Wombat poop is cube-shaped.",
"The human body has more bacterial cells than human cells.",
"There are more stars in the universe than grains of sand on Earth.",
"Cleopatra lived closer in time to the Moon landing than to the building of the pyramids.",
"Sloths can hold their breath longer than dolphins.",
"Water can boil and freeze at the same time.",
"Your stomach gets a new lining every few days.",
"Scotland has 421 words for snow.",
"A single strand of spaghetti is called a spaghetto.",
"Octopuses can taste with their arms.",
"Some turtles can breathe through their butts.",
"Venus flytraps can count.",
"Cows have best friends.",
"An apple floats because it is 25 percent air.",
"A bolt of lightning is five times hotter than the surface of the sun.",
"Bees can recognize human faces.",
"There are more possible games of chess than atoms in the observable universe.",
"Sea otters hold hands while they sleep.",
"The inventor of the microwave discovered it after a chocolate bar melted in his pocket.",
"A blue whale’s heart is about the size of a small car.",
"Humans share about 60 percent of their DNA with bananas.",
"There are more trees on Earth than stars in the Milky Way.",
"Penguins propose with pebbles.",
"Saturn could float in water if you had a big enough bathtub.",
"The shortest war in history lasted 38 minutes.",
"Butterflies can taste with their feet.",
"Hot water can freeze faster than cold water.",
"A day on Mercury lasts 59 Earth days.",
"The average cloud weighs over a million kilograms.",
"Giraffes only need about 30 minutes of sleep per day.",
"Your nose can remember 50,000 different scents.",
"Sharks do not have bones.",
"A teaspoon of honey represents the life’s work of about 12 bees.",
"Earth is not perfectly round. It bulges at the equator.",
"Some cats are allergic to humans.",
"The Moon is slowly drifting away from Earth.",
"The fingerprints of a koala are almost identical to humans.",
"Your brain uses about 20 percent of your body’s energy.",
"The Great Wall of China is not visible from space with the naked eye.",
"One cloud can weigh more than a million elephants.",
"Some metals explode in water.",
"An astronaut grows taller in space.",
"Polar bears have black skin.",
"The human body glows very faintly in the dark.",
"Venus rotates backward compared to most planets.",
"A day on Jupiter is only about 10 hours long.",
"There are more possible arrangements of a deck of cards than seconds since Earth formed.",
"A group of crows is called a murder.",
"Glass is technically a slow-moving liquid.",
"Your ears never stop growing.",
"The smell of rain has a name. It is called petrichor.",
"Space is completely silent.",
"Some frogs can freeze solid and survive.",
"Elephants can recognize themselves in mirrors.",
"There are rivers beneath the ocean.",
"A shrimp’s heart is in its head.",
"The tallest mountain on Earth is technically Mauna Kea if measured from base to peak.",
"Antarctica is the largest desert in the world.",
"Some planets rain diamonds.",
"A sneeze can travel up to 100 miles per hour.",
"Starfish can regenerate lost arms.",
"Koalas sleep up to 22 hours a day.",
"There are more fake flamingos in the world than real ones.",
"The human brain contains about 86 billion neurons.",
"Rats laugh when tickled.",
"The first alarm clock could only ring at 4 a.m.",
"Your bones are stronger than steel of the same density.",
"There are over 8 million species on Earth.",
"A day on Mars is just 37 minutes longer than a day on Earth.",
"The largest living structure on Earth is the Great Barrier Reef.",
"Caterpillars have more muscles than humans.",
"A cloud can travel thousands of kilometers.",
"Some bamboo grows nearly a meter in a single day.",
"The coldest place in the universe we know of is on Earth.",
"The average person walks the equivalent of five times around the world in a lifetime.",
"Venus is the hottest planet in our solar system.",
"There is a species of jellyfish that is biologically immortal.",
"A lightning bolt contains enough energy to toast 100,000 slices of bread.",
"The first photo ever taken required an eight-hour exposure.",
"Butterflies remember being caterpillars.",
"The Milky Way smells like rum and tastes like raspberries, according to astronomers.",
"Trees can communicate through underground fungal networks.",
"The average human produces enough saliva in a lifetime to fill two swimming pools.",
"A crocodile cannot stick out its tongue.",
"The Earth’s core is as hot as the surface of the sun.",
"A group of porcupines is called a prickle.",
"Snakes can predict earthquakes.",
"Your heart beats about 100,000 times a day.",
"The hottest chili pepper can cause temporary loss of feeling in your mouth.",
"Some spiders can fly using electricity.",
"An octopus has nine brains.",
"The largest snowflake ever recorded was 15 inches wide.",
"You share more DNA with mushrooms than plants do.",
"The speed of a computer mouse is measured in Mickeys.",
"Sea cucumbers can fight with their internal organs.",
"One in four mammals is a bat.",
"The Pacific Ocean is shrinking.",
"Birds do not urinate.",
"The first oranges were green.",
"Sharks can detect a drop of blood in the ocean.",
"There are more possible Sudoku grids than atoms in the universe.",
"Your liver can regenerate itself.",
"Some ants farm other insects.",
"The Sahara Desert was once green and full of lakes.",
"A group of owls is called a parliament.",
"Your body has about 37 trillion cells.",
"Some fish can recognize themselves in mirrors.",
"Octopuses can open jars from the inside.",
"The Amazon rainforest produces about 20 percent of the world’s oxygen.",
"A day on Pluto lasts about 153 hours.",
"The human eye can distinguish millions of colors.",
"There are more lakes in Canada than in the rest of the world combined.",
"A hummingbird’s heart can beat over 1,200 times per minute.",
"Some trees are older than the pyramids.",
"Sound travels four times faster in water than in air.",
"The average lightning bolt is about 3 miles long.",
"Your brain generates enough electricity to power a small light bulb.",
"A group of hedgehogs is called a prickle.",
"The first computer bug was an actual moth.",
"Butterflies were once called flutterbys.",
"There are volcanoes under Antarctica.",
"Some plants scream when cut.",
"The tallest tree ever recorded was over 380 feet tall.",
"Octopuses can squeeze through openings the size of a coin.",
"Venus is the brightest planet in our night sky.",
"The world’s quietest room can make you hear your own heartbeat.",
"Snails can sleep for up to three years.",
"There are more stars than grains of sand on all the beaches on Earth.",
"The average human blinks about 20,000 times a day.",
"A day on Neptune lasts about 16 hours.",
"Some birds can sleep while flying.",
"The largest animal ever to live is the blue whale.",
"There is enough gold in Earth’s core to coat the planet.",
"Space smells like burnt steak, according to astronauts.",
"A group of jellyfish is called a smack.",
"Your body replaces most of its cells every few years.",
"There are more than 1,000 languages spoken in Africa.",
"An ostrich’s eye is bigger than its brain.",
"The Sun accounts for about 99.8 percent of the mass in our solar system.",
"Some metals can remember their shape.",
"The fingerprints of identical twins are not identical.",
"A lightning strike can create glass in sand.",
"There are waterfalls beneath the ocean.",
"Your bones constantly rebuild themselves.",
"The largest desert in the world is Antarctica.",
"Time moves slightly faster on a mountain than at sea level.",
"Some fish can walk on land.",
"The average person spends about six months of their life waiting at red lights.",
"The human nose can detect over a trillion scents.",
"There is a species of spider that keeps tiny frogs as pets.",
"A day on Uranus lasts about 17 hours.",
"The first recorded Olympic Games were held in 776 BC.",
"The tallest building in the world can sway several feet in strong winds.",
"Your skin is your largest organ.",
"There are more possible passwords with eight characters than people on Earth.",
"Some trees can live for over 4,000 years.",
"An astronaut’s footprints on the Moon could last millions of years.",
"The average person dreams for about two hours each night.",
"The Pacific Ocean is larger than all land on Earth combined.",
"There are more possible Rubik’s Cube combinations than atoms in the observable universe.",
"Your heart creates enough pressure to squirt blood several feet.",
"Some lizards can squirt blood from their eyes.",
"The human brain is about 60 percent fat.",
"Lightning strikes Earth about 100 times per second.",
"The Great Barrier Reef can be seen from space.",
"Your taste buds live about 10 days before being replaced.",
"Some whales can communicate across entire ocean basins.",
"The average person will eat about 35 tons of food in a lifetime.",
"There are over 200 bones in the human body.",
"A group of hippos is called a bloat.",
"The universe is about 13.8 billion years old.",
"Your body produces about a liter of mucus every day.",
"Some birds can mimic chainsaws and camera shutters.",
"Jupiter has the shortest day of all the planets.",
"The human eye blinks in about 100 milliseconds.",
"There are more plastic flamingos in the U.S. than real ones.",
"The tallest waterfall in the world is Angel Falls.",
"Some fish can change gender.",
"Your body heat can power a small light bulb.",
"The average person has about 100,000 hairs on their head.",
"The Earth travels around the Sun at about 67,000 miles per hour.",
];
