window.JOKES = [
  "I tried to read a book on anti-gravity. I couldn’t put it down.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "I would tell you a joke about time travel, but you didn’t like it.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "I used to play piano by ear. Now I use my hands.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I’m reading a book about teleportation. It’s bound to take me places.",
  "What do you call fake spaghetti? An impasta.",
  "Why did the math book look sad? It had too many problems.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I used to be afraid of hurdles, but I got over it.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "I once got fired from a keyboard factory. I wasn’t putting in enough shifts.",
  "I asked the librarian if the library had books on paranoia. She whispered, “They’re right behind you.”",
  "What do you call a belt made of watches? A waist of time.",
  "What did 0 say to 8? Nice belt.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why did the cookie go to the hospital? It felt crummy.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "Why are ghosts bad liars? You can see right through them.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "Why don’t sharks eat clowns? They taste funny.",
  "What do you call an alien with three eyes? An aliiien.",
  "What’s an alien’s favorite music? Neptunes.",
  "Why did the astronaut break up with his girlfriend? He needed space.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "I’m on a seafood diet. I see food and I eat it.",
  "I used to hate facial hair, but then it grew on me.",
  "Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent.",
  "I’m afraid for the calendar. Its days are numbered.",
  "I told my dog a chemistry joke. There was no reaction.",
  "I once got fired from a canned juice company. I couldn’t concentrate.",
  "Why did the bicycle fall over? It was two-tired.",
  "I ordered a chicken and an egg online. I’ll let you know.",
  "Why did the coffee file a police report? It got mugged.",
  "I told my suitcase there would be no vacations this year. Now I’m dealing with emotional baggage.",
  "Why don’t programmers like nature? Too many bugs.",
  "I tried to catch fog yesterday. Mist.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Why don’t crabs give to charity? Because they’re shellfish.",
  "I used to be addicted to not using soap. I’m clean now.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "I once had a job at a bakery. I kneaded dough.",
  "Why did the invisible man turn down the job offer? He couldn’t see himself doing it.",
  "Why don’t melons get married? Because they cantaloupe.",
  "I accidentally swallowed some food coloring. I feel like I’ve dyed a little inside.",
  "Did you hear about the antennas that got married? The wedding was okay, but the reception was fantastic.",
  "I went to buy some camouflage pants, but I couldn’t find any.",
  "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
  "I tried to sue the airport for losing my luggage. I lost my case.",
  "I used to be addicted to the hokey pokey, but I turned myself around.",
  "I used to be a banker, but I lost interest.",
  "I once worked at a blanket factory. But it folded.",
  "I don’t trust stairs. They’re always up to something.",
  "I used to be a watchmaker. It was about time.",
  "I once had a job at a calendar factory, but I took a couple days off.",
  "I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.",
  "I used to be a lumberjack, but I couldn’t hack it.",
  "I tried to be a ghost, but I didn’t have the spirit.",
  "I once worked in a glue factory. I couldn’t stick with it.",
  "I tried to write a joke about paper, but it was tearable.",
  "I once worked at a sunglasses factory. Shady business...",
  "I used to be a tailor, but I wasn’t suited for it.",
  "I once applied to work at a mirror factory. I could really see myself there.",
  "I told my wife she should do lunges to stay in shape. That would be a big step forward.",
  "I tried to write a joke about construction, but I’m still working on it.",
  "Did you hear about the circus fire? It was in tents!",
  "How do you catch a squirrel? Climb a tree and act like a nut!",
  "Did you hear about the guy who invented Lifesavers? They say he made a mint!",
  "What did the big flower say to the little flower? Hi, bud!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
  "What do you call a snowman with a six-pack? An abdominal snowman!",
  "Did you hear about the restaurant on the moon? Great food, no atmosphere!",
  "What did one hat say to the other hat? You stay here, I’ll go on ahead!",
  "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
  "I’m writing a book about glue, but I’m stuck on the first chapter.",
  "What did one plate whisper to the other plate? Dinner is on me.",
  "Did you hear the rumor about butter? Well, I’m not going to go spreading it!",
  "What’s Forrest Gump’s password? 1forrest1",
  "What state is known for its small drinks? Minnesota.",
  "What does a nosey pepper do? It gets jalapeño business.",
  "If two vegetarians get in an argument, is it still called beef?",
  "I have a clean conscience. It’s never been used.",
  "I love telling dad jokes. Sometimes, he even laughs.",
  "How do you stop a bull from charging? Cancel its credit card.",
  "What’s the difference between a man’s wallet before and after kids? There are pictures where the money used to be.",
  "My kid is blaming me for ruining their birthday. That’s ridiculous. I didn’t even know it was today.",
  "What’s the difference between the bird flu and the swine flu? One requires tweetment and the other an oinkment.",
  "What do you call a line of men waiting to get haircuts? A barberqueue.",
  "Why can’t a leopard hide? He’s always spotted.",
  "Air used to be free at the gas station. Now it costs a dollar. Inflation.",
  "Why did the orange lose the race? It ran out of juice.",
  "How do you fix a broken pumpkin? With a pumpkin patch.",
  "Why did the man fall down the well? Because he couldn’t see that well.",
  "What has ears but cannot hear? A cornfield.",
  "Can February March? No, but April May.",
  "Why was six afraid of seven? Because seven ate nine.",
  "What do you call a pencil with two erasers? Pointless.",
  "What’s brown and sticky? A stick.",
  "It really takes guts to be an organ donor.",
  "How do you throw a party in outer space? You planet.",
  "How do you make an octopus laugh? With ten-tickles.",
  "What type of tree fits in your hand? A palm tree.",
  "What made the tomato blush? It saw the salad dressing.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What do you call a fibbing cat? A lion.",
  "If a child refuses to nap, are they guilty of resisting a rest?",
  "RIP boiling water, you will be mist.",
  "I ate a clock the other day. It was very time consuming.",
  "You can tell it’s a dogwood tree from its bark.",
  "When does a joke turn into a dad joke? When it becomes apparent.",
  "They say that three out of two people are bad at fractions.",
  "Why did the picture go to prison? Because it was framed.",
  "What gets wetter the more it dries? A towel.",
  "I was wondering why the frisbee kept getting bigger and bigger. Then it hit me.",
  "What do you call someone who tells dad jokes but isn’t a dad? A faux pa.",
  "If you see a crime at an Apple store, are you an iWitness?",
  "Why are spiders so smart? They can find everything on the web.",
  "What do you call a toothless bear? A gummy bear.",
  "What do you give a sick lemon? Lemon-aid.",
  "What kind of car does a sheep like to drive? A lamborghini.",
  "What key is used to open bananas? A mon-key.",
  "What has four wheels and flies? A garbage truck.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "What do you call an alligator in a vest? An investigator.",
  "What kind of shoes do frogs wear? Open-toad sandals.",
  "I just built an ATM that only gives out coins. It just makes cents.",
  "Did I ever tell you about the time I went mushroom foraging? It’s a story with a morel at the end.",
  "What happened when two slices of bread went on a date? It was loaf at first sight.",
  "I had a quiet game of tennis today. There was no racket.",
  "What's a shark's favorite saying? \"Man overboard!\"",
  "What did one slice of bread say to the other before the race? You're toast!",
  "I poured some water over a duck's back yesterday. I don't think he cared.",
  "How did I know my girlfriend thought I was invading her privacy? She wrote about it in her diary.",
  "Why did the electric car feel discriminated against? Because the rules weren't current.",
  "I'm such a good navigator, a self-driving car once asked me for directions.",
  "What did the bison say to his son when he left the ranch? Bi-son.",
  "Watch what you say around the egg whites. They can't take a yolk.",
  "I'm so good at fixing things, my motto is, \"If it is broke, I'll still fix it.\"",
  "Where did the pumpkins have their meeting? In the gourdroom.",
  "What's the best way to save your dad jokes? In a dadda-base.",
  "I got a new pen that can write under water. It can write other words too.",
  "My boss said, \"Dress for the job you want, not the job you have.\" So I went in as Batman.",
  "I went to the aquarium this weekend, but I didn’t stay long. There’s something fishy about that place.",
  "What do you call a sheep who can sing and dance? Lady Ba Ba.",
  "What do you call a French man wearing sandals? Philipe Fallop.",
  "Why can't dinosaurs clap their hands? Because they're extinct.",
  "I gave my handyman a to-do list, but he only did jobs 1, 3, and 5. Turns out he only does odd jobs.",
  "Why should you never take sides in an argument at the dinner table? Trick question. It's the perfect time to take sides because no one's paying attention. Bring Tupperware.",
  "Who won the neck decorating contest? It was a tie.",
  "Where do rainbows go when they've been bad? To prism, so they have time to reflect on what they've done.",
  "Dogs can't operate MRI machines. But catscan.",
  "I'm so upset, my barber said he can't cut my hair any longer. He can only cut it shorter.",
  "What do mermaids use to wash their fins? Tide.",
  "What did the skillet eat on its birthday? Pan-cakes.",
  "Why couldn't the produce manager make it to work? He could drive, but he didn't avocado.",
  "I went to a silent auction. I won a dog whistle and two mimes.",
  "How is my wallet like an onion? Every time I open it, I cry.",
  "What do you call a dog who meditates? Aware wolf.",
  "What kind of fish do penguins catch at night? Star fish.",
  "Which vegetable has the best kung fu? Broc-lee.",
  "Can a frog jump higher than a house? Of course. A house can't jump.",
  "I was going to try an all almond diet, but that's just nuts.",
  "I was going to tell a joke about the layoffs, but sadly none of them work.",
  "What's the hardest tea to swallow? Reality.",
  "I was raised as an only child. It drove my sister nuts.",
  "Never date a tennis player. Love means nothing to them.",
  "You don't need a parachute to go sky-diving. You need one to go sky-diving twice.",
  "My dog just ate a $100 bill. I guess he has expensive taste.",
  "The guy who stole my diary went missing. My thoughts are with his family.",
  "What did the cow say to the leather chair? \"Hi, Mom!\"",
  "Hard work pays off later. Laziness pays off now.",
  "My resume is a list of things I hope I never have to do again.",
  "Why did the social media manager break up with her boyfriend? Lack of engagement.",
  "I threw a boomerang months ago. Now I live in constant fear.",
  "\"I'm sorry\" and \"I apologize\" usually mean the same thing... but not at a funeral.",
  "I haven't spoken to my wife in years. I thought it would be rude to interrupt her.",
  "A woman passed out on the merry-go-round. She's coming around.",
  "There was a break-in at the wig factory. Police are combing the area.",
  "I got an A on my origami assignment when I turned my paper into my teacher.",
  "How many storm troopers does it take to change a lightbulb? None, because they are all on the dark side.",
  "If your house is cold, just stand in the corner. It’s always 90 degrees there.",
  "Hi, I’m Cliff. Drop over sometime.",
  "Did you hear about the guy who went to the doctor for a headache? The doctor examined his ear and found money. The doctor kept pulling and pulling it out until he had $1,999. Then the doctor said, \"No wonder you're not feeling two grand!\"",
  "Dad, when he puts the car in reverse: \"Ah, this takes me back.\"",
  "What do you call the security guards for Samsung? Guardians of the galaxy.",
  "The other day I bought a thesaurus, but when I got home and opened it, all the pages were blank. I have no word to describe how angry I am.",
  "The owner of the tuxedo store kept hovering over me when I was browsing, so I asked him to leave me alone. He said, \"Fine, suit yourself.\"",
  "Why did the egg have a day off? Because it was Fryday.",
  "Have you ever heard about the kidnapping at school? It's okay, he woke up.",
  "I found a book called How to Solve 50% of Your Problems. So I bought 2.",
  "Why did the Rolling Stones stop making music? Because they got to bottom of the hill.",
  "What is the best present? Broken drums. You can't beat them.",
  "Did you know corduroy pillows are in style? They're making headlines.",
  "Did you hear about the fragile myth? It was busted.",
  "What word can you make shorter by adding two letters? Short.",
  "What do you call a criminal landing an airplane? Condescending.",
  "I stayed up all night wondering where the sun went, and then it dawned on me.",
  "Why do people who live in Greece hate waking up at dawn? Because Dawn is tough on Greece.",
  "How do you make holy water? You boil the hell out of it.",
  "Justice is a dish best served cold. Otherwise, it's just water.",
  "Why should you never throw grandpa's false teeth at a vehicle? You might denture car.",
  "Why are Christmas trees bad at knitting? They always drop their needles.",
  "What did the lunch box say to the refrigerator? Don't hate me because I'm a little cooler.",
  "Why couldn’t the tree get on his computer? Because he could not log on.",
  "What's a skeleton's favorite type of road? A dead end.",
  "What did the alien say to the landscaper? Take me to your weeder.",
  "Me: \"I want to write when I grow up.\" Dad: \"Why don’t you left instead?\"",
  "What did Elvis say to his landscaper? Thank you for the mulch!",
  "Why didn't the lifeguard save the hippie? He was too far out!",
  "What did the mother broom say to the baby broom? Time to go to sweep.",
  "The other day I was attacked by a bunch of circus clowns in a parking lot. I won though, cause I went right for the juggler.",
  "I'd like to shout out sidewalks for keeping me off the streets.",
  "Why did the computer go to the doctor? Because he had a virus.",
  "How many ears does Captain Kirk have? Three. The left ear, the right ear, and the final front-ear.",
  "Did you hear about the famous pickle? He's a really big dill.",
  "I went on Amazon to buy a lighter but all they had were 3,472 matches.",
  "What do you need to make a highway in an art studio? A mile marker.",
  "How does Vin Diesel keep in touch with the Fast and Furious crew? On a Zoom call.",
  "How much does a chimney cost? Nothing, it's on the house.",
  "Why do only some couples go to the gym? Because some relationships don't work out.",
  "How do you make 7 even? Take away the S.",
  "Why is sausage bad for you? It brings out the Wurst in people.",
  "What do you call a broken clock? A waste of time.",
  "Why did the teddy bear turn down a slice of cake? He was stuffed.",
  "What's an astronaut's favorite board game? Moon-opoly.",
  "How do you make Budweiser? Send him to school.",
  "What is Santa’s favorite state to visit? Ida Ho Ho Ho.",
  "Have you seen those traffic circles or driven around them? Well, they are pointless.",
  "What’s a dog’s favorite super hero? Labra-Thor.",
  "I was walking down the beach when I heard a swimmer yelling for help with a shark circling him. I just laughed... I knew that shark wasn't going to help him.",
  "What do you call a rabbit with fleas? Bugs Bunny!",
  "What do you say when a chicken is looking at salad? Chicken sees a salad.",
  "What do you call a cow with no legs? Ground beef!",
  "You are on a horse riding full gallop. Next to you is a giraffe at full gallop, and behind you is a lion on your tail. What do you do? Get off the carousel.",
  "I have a horse named mayo, and mayo neighs.",
  "What is the cutest creature in the sea? A cuddlefish.",
  "What do you call an elephant in a telephone booth? Stuck.",
  "A man walked into a bar with a parrot on his shoulder. The bartender said, \"Does the animal talk?\" And the parrot replied, \"I don't know.\"",
  "What do you get when you cross a parrot with a caterpillar? A little walkie-talkie.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "What do you call a deer with no eyes? No eye deer.",
  "What do you call a fish with no eyes? Fshhhh.",
  "Why did the chicken cross the road? To show the possum it could be done.",
  "Why aren’t dogs allowed in bars? Because they can’t control their licker!",
  "Why did the baseball player get fired? He ran 3 bases then walked home.",
  "Why don't fish play basketball? Because they're scared of the net.",
  "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
  "What does a sprinter eat before a race? Nothing, they fast!",
  "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
  "Where do basketball players go when they need a uniform? New Jersey.",
  "Why don't football players wear glasses? It's a contact sport.",
  "What's the best animal in soccer? A score-pion.",
  "What's the difference between a quarterback and a baby? One takes a snap, one takes a nap.",
  "I used to be addicted to basketball, but I rebounded.",
  "Why can't pigs play soccer? They hog the ball.",
  "Why shouldn't you play tennis in the jungle? Too many cheetahs.",
  "What does a sports fan have in common with an angry chicken? A foul mouth.",
  "Why couldn't the baby score in basketball? He was always dribbling.",
  "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
  "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
  "How does dry skin affect you at work? You don’t have any elbow grease to put into it.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Have you heard about the chocolate record player? It sounds pretty sweet.",
  "A skeleton walks into a bar and says, \"Hey, bartender. I'll have one beer and a mop.\"",
  "Where do fruits go on vacation? Pear-is!",
  "I asked my dog what's two minus two. He said nothing.",
  "What did Baby Corn say to Mama Corn? Where's Pop Corn?",
  "Where do you learn to make a banana split? Sundae school.",
  "What has more letters than the alphabet? The post office.",
  "What do you call a poor Santa Claus? St. Nickel-less.",
  "I don't trust those trees. They seem kind of shady.",
  "What do you call someone with no body and no nose? Nobody knows.",
  "Why did Billy get fired from the banana factory? He kept throwing away the bent ones.",
  "Dad, did you get a haircut? No, I got them all cut!",
  "What does a lemon say when it answers the phone? Yellow!",
  "This graveyard looks overcrowded. People must be dying to get in.",
  "Dad, can you put the cat out? I didn't know it was on fire.",
  "What time did the man go to the dentist? Tooth hurt-y.",
  "What do you call it when a snowman throws a tantrum? A meltdown.",
  "What concert costs just 45 cents? 50 Cent featuring Nickelback!",
  "What kind of shoes do ninjas wear? Sneakers!",
  "A guy walks into a bar... and he was disqualified from the limbo contest.",
  "Do you wanna box for your leftovers? No, but I'll wrestle you for them.",
  "That car looks nice but the muffler seems exhausted.",
  "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.",
  "A cheeseburger walks into a bar. The bartender says, \"Sorry, we don't serve food here.\"",
  "Did you hear about the guy who invented the knock-knock joke? He won the \"no-bell\" prize.",
  "I decided to sell my vacuum cleaner. It was just gathering dust!",
  "I had a neck brace fitted years ago and I've never looked back since.",
  "What do you call an elephant that doesn't matter? An irrelephant.",
  "What's the best smelling insect? A deodor-ant.",
  "I used to be a personal trainer. Then I gave my too weak notice.",
  "I'm so good at sleeping, I can do it with my eyes closed!",
  "What do you call a lazy baby kangaroo? A pouch potato!",
  "Why are piggy banks so wise? They're filled with common cents.",
  "How do you get a good price on a sled? You have toboggan.",
  "Why are elevator jokes so classic and good? They work on many levels.",
  "Spring is here. I got so excited I wet my plants.",
  "I wouldn't buy anything with velcro. It's a total rip-off."
];
