window.JOKES = [

  "I tried to read a book on anti-gravity. I couldn’t put it down.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "I told my computer I needed a break. It said: no problem, I’ll go to sleep.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "I would tell you a joke about time travel, but you didn’t like it.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "I used to play piano by ear. Now I use my hands.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I’m reading a book about teleportation. It’s bound to get somewhere.",
  "What do you call fake spaghetti? An impasta.",
  "Why did the math book look sad? Too many problems.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "I started a band called 999 Megabytes. We haven’t gotten a gig yet.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don’t programmers like nature? Too many bugs.",
  "I’m on a seafood diet. I see food and I eat it.",
  "Why did the bicycle fall over? It was two tired.",
  "I used to be afraid of hurdles, but I got over it.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "Why did the coffee file a police report? It got mugged.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "I once got fired from a keyboard factory. I wasn’t putting in enough shifts.",
  "Why did the tomato blush? It saw the salad dressing.",
  "I asked the librarian if the library had books on paranoia. She whispered, “They’re right behind you.”",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why did the computer go to the doctor? It caught a virus.",
  "Why don’t oysters donate to charity? Because they’re shellfish.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the calendar get promoted? It had a lot of dates.",
  "I told a joke about construction, but I’m still working on it.",
  "Why did the stadium get hot after the game? All the fans left.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the cookie go to the hospital? It felt crummy.",
  "I bought shoes from a drug dealer. I don’t know what he laced them with, but I was tripping all day.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "Why did the banker quit his job? He lost interest.",
  "Why are ghosts bad liars? You can see right through them.",
  "Why did the picture go to jail? It was framed.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why did the orange stop? It ran out of juice.",
  "Why can’t you give Elsa a balloon? Because she’ll let it go.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "Why did the man put his money in the blender? He wanted liquid assets.",
  "Why don’t sharks eat clowns? They taste funny.",
  "Why did the moon skip dinner? It was full.",
  "What do you call an alligator in a vest? An investigator.",
  "Why did the phone wear glasses? It lost its contacts.",
  "Why did the musician bring a ladder? To reach the high notes."

];
