// watchlist.js
// Just Movies, Series, Documentaries

window.WATCHLIST = [

// NUMERICAL
// MOVIES
{ title: "10 Things I Hate About You", type: "Movie", year: "1999" },
{ title: "12 Angry Men", type: "Movie", year: "1957" },
{ title: "12 Years a Slave", type: "Movie", year: "2013" },
{ title: "127 Hours", type: "Movie", year: "2010" },
{ title: "1917", type: "Movie", year: "2019" },
{ title: "2001: A Space Odyssey", type: "Movie", year: "1968" },
{ title: "2012", type: "Movie", year: "2009" },
{ title: "21 Jump Street", type: "Movie", year: "2012" },
{ title: "22 Jump Street", type: "Movie", year: "2014" },
{ title: "28 Days Later", type: "Movie", year: "2002" },
{ title: "28 Weeks Later", type: "Movie", year: "2007" },
{ title: "300", type: "Movie", year: "2006" },
{ title: "3:10 to Yuma", type: "Movie", year: "2007" },
{ title: "40-Year-Old Virgin", type: "Movie", year: "2005" },
{ title: "42", type: "Movie", year: "2013" },
{ title: "50/50", type: "Movie", year: "2011" },
{ title: "500 Days of Summer", type: "Movie", year: "2009" },
{ title: "8 Mile", type: "Movie", year: "2002" },
{ title: "8½", type: "Movie", year: "1963" },
{ title: "9", type: "Movie", year: "2009" },

// SERIES
{ title: "24", type: "Series", year: "2001–2010" },
{ title: "3%", type: "Series", year: "2016–2020" },
{ title: "30 Rock", type: "Series", year: "2006–2013" },
{ title: "1883", type: "Series", year: "2021–2022" },
{ title: "1923", type: "Series", year: "2022–" },

// DOCUMENTARIES
{ title: "13th", type: "Documentary", year: "2016" },
{ title: "20 Feet from Stardom", type: "Documentary", year: "2013" },
{ title: "102 Minutes That Changed America", type: "Documentary", year: "2008" },
{ title: "7 Days in September", type: "Documentary", year: "2002" },
{ title: "9/11", type: "Documentary", year: "2002" },
  
// A
// MOVIES
{ title: "A Beautiful Mind", type: "Movie", year: "2001" },
{ title: "A Clockwork Orange", type: "Movie", year: "1971" },
{ title: "A Few Good Men", type: "Movie", year: "1992" },
{ title: "A Quiet Place", type: "Movie", year: "2018" },
{ title: "A Quiet Place Part II", type: "Movie", year: "2021" },
{ title: "A Star Is Born", type: "Movie", year: "2018" },
{ title: "A Streetcar Named Desire", type: "Movie", year: "1951" },
{ title: "A Time to Kill", type: "Movie", year: "1996" },
{ title: "A.I. Artificial Intelligence", type: "Movie", year: "2001" },
{ title: "About Time", type: "Movie", year: "2013" },
{ title: "Air", type: "Movie", year: "2023" },
{ title: "Airplane!", type: "Movie", year: "1980" },
{ title: "Alien", type: "Movie", year: "1979" },
{ title: "Aliens", type: "Movie", year: "1986" },
{ title: "Alien 3", type: "Movie", year: "1992" },
{ title: "Alien: Covenant", type: "Movie", year: "2017" },
{ title: "All the President's Men", type: "Movie", year: "1976" },
{ title: "Almost Famous", type: "Movie", year: "2000" },
{ title: "Amadeus", type: "Movie", year: "1984" },
{ title: "American Beauty", type: "Movie", year: "1999" },
{ title: "American History X", type: "Movie", year: "1998" },
{ title: "American Hustle", type: "Movie", year: "2013" },
{ title: "American Psycho", type: "Movie", year: "2000" },
{ title: "Amélie", type: "Movie", year: "2001" },
{ title: "Annihilation", type: "Movie", year: "2018" },
{ title: "Annie Hall", type: "Movie", year: "1977" },
{ title: "Apocalypse Now", type: "Movie", year: "1979" },
{ title: "Apollo 13", type: "Movie", year: "1995" },
{ title: "Argo", type: "Movie", year: "2012" },
{ title: "Arrival", type: "Movie", year: "2016" },
{ title: "As Good as It Gets", type: "Movie", year: "1997" },
{ title: "The Artist", type: "Movie", year: "2011" },
{ title: "Avatar", type: "Movie", year: "2009" },
{ title: "Avatar: The Way of Water", type: "Movie", year: "2022" },
{ title: "Avengers: Infinity War", type: "Movie", year: "2018" },
{ title: "Avengers: Endgame", type: "Movie", year: "2019" },
{ title: "The Apartment", type: "Movie", year: "1960" },
{ title: "The Assassination of Jesse James by the Coward Robert Ford", type: "Movie", year: "2007" },
{ title: "The Adjustment Bureau", type: "Movie", year: "2011" },
{ title: "A League of Their Own", type: "Movie", year: "1992" },

// SERIES
{ title: "Arrested Development", type: "Series", year: "2003–2019" },
{ title: "Atlanta", type: "Series", year: "2016–2022" },
{ title: "Andor", type: "Series", year: "2022–" },
{ title: "American Crime Story", type: "Series", year: "2016–" },
{ title: "American Horror Story", type: "Series", year: "2011–" },
{ title: "Alias", type: "Series", year: "2001–2006" },
{ title: "The Americans", type: "Series", year: "2013–2018" },

// DOCUMENTARIES
{ title: "An Inconvenient Truth", type: "Documentary", year: "2006" },
{ title: "Amy", type: "Documentary", year: "2015" },
{ title: "Apollo 11", type: "Documentary", year: "2019" },
{ title: "The Act of Killing", type: "Documentary", year: "2012" },
{ title: "American Movie", type: "Documentary", year: "1999" },
{ title: "The Alpinist", type: "Documentary", year: "2021" },
  
// B
// MOVIES
{ title: "Back to the Future", type: "Movie", year: "1985" },
{ title: "Back to the Future Part II", type: "Movie", year: "1989" },
{ title: "Back to the Future Part III", type: "Movie", year: "1990" },
{ title: "The Batman", type: "Movie", year: "2022" },
{ title: "Batman Begins", type: "Movie", year: "2005" },
{ title: "Batman", type: "Movie", year: "1989" },
{ title: "The Big Lebowski", type: "Movie", year: "1998" },
{ title: "The Big Short", type: "Movie", year: "2015" },
{ title: "The Big Sick", type: "Movie", year: "2017" },
{ title: "Blade Runner", type: "Movie", year: "1982" },
{ title: "Blade Runner 2049", type: "Movie", year: "2017" },
{ title: "Black Swan", type: "Movie", year: "2010" },
{ title: "Black Panther", type: "Movie", year: "2018" },
{ title: "Black Panther: Wakanda Forever", type: "Movie", year: "2022" },
{ title: "Black Hawk Down", type: "Movie", year: "2001" },
{ title: "Bohemian Rhapsody", type: "Movie", year: "2018" },
{ title: "Borat", type: "Movie", year: "2006" },
{ title: "The Bourne Identity", type: "Movie", year: "2002" },
{ title: "The Bourne Supremacy", type: "Movie", year: "2004" },
{ title: "The Bourne Ultimatum", type: "Movie", year: "2007" },
{ title: "Braveheart", type: "Movie", year: "1995" },
{ title: "Bridesmaids", type: "Movie", year: "2011" },
{ title: "Brokeback Mountain", type: "Movie", year: "2005" },
{ title: "The Breakfast Club", type: "Movie", year: "1985" },
{ title: "The Bridge on the River Kwai", type: "Movie", year: "1957" },
{ title: "Birdman", type: "Movie", year: "2014" },
{ title: "The Banshees of Inisherin", type: "Movie", year: "2022" },
{ title: "The Book of Eli", type: "Movie", year: "2010" },
{ title: "Before Sunrise", type: "Movie", year: "1995" },
{ title: "Before Sunset", type: "Movie", year: "2004" },
{ title: "Before Midnight", type: "Movie", year: "2013" },
{ title: "Big", type: "Movie", year: "1988" },
{ title: "The Bodyguard", type: "Movie", year: "1992" },
{ title: "Blue Velvet", type: "Movie", year: "1986" },
{ title: "The Blair Witch Project", type: "Movie", year: "1999" },
{ title: "Burn After Reading", type: "Movie", year: "2008" },
{ title: "The Blind Side", type: "Movie", year: "2009" },
{ title: "The Boy in the Striped Pyjamas", type: "Movie", year: "2008" },
{ title: "The Bucket List", type: "Movie", year: "2007" },
{ title: "Baby Driver", type: "Movie", year: "2017" },

// SERIES
{ title: "Breaking Bad", type: "Series", year: "2008–2013" },
{ title: "Better Call Saul", type: "Series", year: "2015–2022" },
{ title: "Band of Brothers", type: "Series", year: "2001" },
{ title: "Black Mirror", type: "Series", year: "2011–" },
{ title: "Boardwalk Empire", type: "Series", year: "2010–2014" },
{ title: "The Boys", type: "Series", year: "2019–" },
{ title: "Brooklyn Nine-Nine", type: "Series", year: "2013–2021" },
{ title: "Big Little Lies", type: "Series", year: "2017–2019" },

// DOCUMENTARIES
{ title: "Bowling for Columbine", type: "Documentary", year: "2002" },
{ title: "Blackfish", type: "Documentary", year: "2013" },
{ title: "The Beatles: Get Back", type: "Documentary", year: "2021" },
{ title: "Beyond the Mat", type: "Documentary", year: "1999" },
{ title: "Becoming", type: "Documentary", year: "2020" },
{ title: "Burden of Dreams", type: "Documentary", year: "1982" },
  
// C
// MOVIES
{ title: "Casablanca", type: "Movie", year: "1942" },
{ title: "Citizen Kane", type: "Movie", year: "1941" },
{ title: "Chinatown", type: "Movie", year: "1974" },
{ title: "Catch Me If You Can", type: "Movie", year: "2002" },
{ title: "Casino", type: "Movie", year: "1995" },
{ title: "Casino Royale", type: "Movie", year: "2006" },
{ title: "Children of Men", type: "Movie", year: "2006" },
{ title: "Collateral", type: "Movie", year: "2004" },
{ title: "Clueless", type: "Movie", year: "1995" },
{ title: "Coco", type: "Movie", year: "2017" },
{ title: "Cold Mountain", type: "Movie", year: "2003" },
{ title: "Coming to America", type: "Movie", year: "1988" },
{ title: "Con Air", type: "Movie", year: "1997" },
{ title: "Contagion", type: "Movie", year: "2011" },
{ title: "Coraline", type: "Movie", year: "2009" },
{ title: "The Conjuring", type: "Movie", year: "2013" },
{ title: "The Conjuring 2", type: "Movie", year: "2016" },
{ title: "Creed", type: "Movie", year: "2015" },
{ title: "Creed II", type: "Movie", year: "2018" },
{ title: "Creed III", type: "Movie", year: "2023" },
{ title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
{ title: "Crazy Rich Asians", type: "Movie", year: "2018" },
{ title: "The Curious Case of Benjamin Button", type: "Movie", year: "2008" },
{ title: "The Cabin in the Woods", type: "Movie", year: "2011" },
{ title: "Captain Phillips", type: "Movie", year: "2013" },
{ title: "Captain America: The Winter Soldier", type: "Movie", year: "2014" },
{ title: "Captain America: Civil War", type: "Movie", year: "2016" },
{ title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", type: "Movie", year: "2005" },
{ title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
{ title: "Call Me by Your Name", type: "Movie", year: "2017" },
{ title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },
{ title: "The Color of Money", type: "Movie", year: "1986" },
{ title: "The Crow", type: "Movie", year: "1994" },
{ title: "Chicago", type: "Movie", year: "2002" },
{ title: "City of God", type: "Movie", year: "2002" },
{ title: "The Commitments", type: "Movie", year: "1991" },
{ title: "Clerks", type: "Movie", year: "1994" },
{ title: "The Craft", type: "Movie", year: "1996" },
{ title: "The Constant Gardener", type: "Movie", year: "2005" },
{ title: "The Count of Monte Cristo", type: "Movie", year: "2002" },

// SERIES
{ title: "Chernobyl", type: "Series", year: "2019" },
{ title: "The Crown", type: "Series", year: "2016–2023" },
{ title: "Community", type: "Series", year: "2009–2015" },
{ title: "Curb Your Enthusiasm", type: "Series", year: "2000–2024" },
{ title: "The Continental: From the World of John Wick", type: "Series", year: "2023" },
{ title: "Castle Rock", type: "Series", year: "2018–2019" },
{ title: "Carnivàle", type: "Series", year: "2003–2005" },

// DOCUMENTARIES
{ title: "Citizenfour", type: "Documentary", year: "2014" },
{ title: "The Cove", type: "Documentary", year: "2009" },
{ title: "Crumb", type: "Documentary", year: "1994" },
{ title: "The Corporation", type: "Documentary", year: "2003" },
{ title: "The Civil War", type: "Documentary", year: "1990" },
{ title: "Conversations with a Killer: The Ted Bundy Tapes", type: "Documentary", year: "2019" },
{ title: "Capturing the Friedmans", type: "Documentary", year: "2003" },
  
// D
// MOVIES
{ title: "The Dark Knight", type: "Movie", year: "2008" },
{ title: "The Dark Knight Rises", type: "Movie", year: "2012" },
{ title: "Django Unchained", type: "Movie", year: "2012" },
{ title: "Drive", type: "Movie", year: "2011" },
{ title: "Die Hard", type: "Movie", year: "1988" },
{ title: "Die Hard 2", type: "Movie", year: "1990" },
{ title: "Die Hard with a Vengeance", type: "Movie", year: "1995" },
{ title: "Donnie Darko", type: "Movie", year: "2001" },
{ title: "Donnie Brasco", type: "Movie", year: "1997" },
{ title: "The Departed", type: "Movie", year: "2006" },
{ title: "Dunkirk", type: "Movie", year: "2017" },
{ title: "Dune", type: "Movie", year: "2021" },
{ title: "Dune: Part Two", type: "Movie", year: "2024" },
{ title: "Dead Poets Society", type: "Movie", year: "1989" },
{ title: "The Devil Wears Prada", type: "Movie", year: "2006" },
{ title: "District 9", type: "Movie", year: "2009" },
{ title: "The Deer Hunter", type: "Movie", year: "1978" },
{ title: "The Descent", type: "Movie", year: "2005" },
{ title: "The Dirty Dozen", type: "Movie", year: "1967" },
{ title: "The Disaster Artist", type: "Movie", year: "2017" },
{ title: "Doctor Zhivago", type: "Movie", year: "1965" },
{ title: "Doctor Strange", type: "Movie", year: "2016" },
{ title: "Doctor Strange in the Multiverse of Madness", type: "Movie", year: "2022" },
{ title: "The Da Vinci Code", type: "Movie", year: "2006" },
{ title: "Dallas Buyers Club", type: "Movie", year: "2013" },
{ title: "Dazed and Confused", type: "Movie", year: "1993" },
{ title: "Double Indemnity", type: "Movie", year: "1944" },
{ title: "The Doors", type: "Movie", year: "1991" },
{ title: "The Day After Tomorrow", type: "Movie", year: "2004" },
{ title: "The Death of Stalin", type: "Movie", year: "2017" },
{ title: "The Descendants", type: "Movie", year: "2011" },
{ title: "Deep Impact", type: "Movie", year: "1998" },
{ title: "Deepwater Horizon", type: "Movie", year: "2016" },
{ title: "Dirty Dancing", type: "Movie", year: "1987" },
{ title: "The Devil's Advocate", type: "Movie", year: "1997" },
{ title: "The Divergent Series: Divergent", type: "Movie", year: "2014" },
{ title: "The Divergent Series: Insurgent", type: "Movie", year: "2015" },
{ title: "The Divergent Series: Allegiant", type: "Movie", year: "2016" },
{ title: "Dawn of the Dead", type: "Movie", year: "1978" },
{ title: "Dawn of the Planet of the Apes", type: "Movie", year: "2014" },
{ title: "The Dig", type: "Movie", year: "2021" },
{ title: "Dog Day Afternoon", type: "Movie", year: "1975" },
{ title: "The Drop", type: "Movie", year: "2014" },
{ title: "The Duelists", type: "Movie", year: "1977" },

// SERIES
{ title: "Dark", type: "Series", year: "2017–2020" },
{ title: "The Deuce", type: "Series", year: "2017–2019" },
{ title: "Dexter", type: "Series", year: "2006–2013" },
{ title: "Deadwood", type: "Series", year: "2004–2006" },
{ title: "The Diplomat", type: "Series", year: "2023–" },
{ title: "Daredevil", type: "Series", year: "2015–2018" },
{ title: "Downton Abbey", type: "Series", year: "2010–2015" },

// DOCUMENTARIES
{ title: "Dear Zachary: A Letter to a Son About His Father", type: "Documentary", year: "2008" },
{ title: "The Dawn Wall", type: "Documentary", year: "2017" },
{ title: "The Devil and Daniel Johnston", type: "Documentary", year: "2005" },
{ title: "Don't F**k with Cats", type: "Documentary", year: "2019" },
{ title: "The Dissident", type: "Documentary", year: "2020" },
{ title: "Dogtown and Z-Boys", type: "Documentary", year: "2001" },
{ title: "The Deepest Breath", type: "Documentary", year: "2023" },
  
// E
// MOVIES
{ title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
{ title: "The Exorcist", type: "Movie", year: "1973" },
{ title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
{ title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
{ title: "Ex Machina", type: "Movie", year: "2014" },
{ title: "Edge of Tomorrow", type: "Movie", year: "2014" },
{ title: "The Empire Strikes Back", type: "Movie", year: "1980" },
{ title: "Enemy", type: "Movie", year: "2013" },
{ title: "The English Patient", type: "Movie", year: "1996" },
{ title: "Erin Brockovich", type: "Movie", year: "2000" },
{ title: "The Equalizer", type: "Movie", year: "2014" },
{ title: "The Equalizer 2", type: "Movie", year: "2018" },
{ title: "The Equalizer 3", type: "Movie", year: "2023" },
{ title: "Escape from New York", type: "Movie", year: "1981" },
{ title: "Escape from Alcatraz", type: "Movie", year: "1979" },
{ title: "The Evil Dead", type: "Movie", year: "1981" },
{ title: "Evil Dead II", type: "Movie", year: "1987" },
{ title: "The Evil Dead", type: "Movie", year: "2013" },
{ title: "Elvis", type: "Movie", year: "2022" },
{ title: "Enter the Dragon", type: "Movie", year: "1973" },
{ title: "Election", type: "Movie", year: "1999" },
{ title: "Enchanted", type: "Movie", year: "2007" },
{ title: "Encanto", type: "Movie", year: "2021" },
{ title: "The Edge", type: "Movie", year: "1997" },
{ title: "Eastern Promises", type: "Movie", year: "2007" },
{ title: "The Elephant Man", type: "Movie", year: "1980" },
{ title: "Eyes Wide Shut", type: "Movie", year: "1999" },
{ title: "The Expendables", type: "Movie", year: "2010" },
{ title: "The Expendables 2", type: "Movie", year: "2012" },
{ title: "The Expendables 3", type: "Movie", year: "2014" },
{ title: "The Expendables 4", type: "Movie", year: "2023" },
{ title: "The Edge of Seventeen", type: "Movie", year: "2016" },
{ title: "The Exorcism of Emily Rose", type: "Movie", year: "2005" },
{ title: "Everest", type: "Movie", year: "2015" },
{ title: "Easy Rider", type: "Movie", year: "1969" },
{ title: "The East", type: "Movie", year: "2013" },
{ title: "Emma.", type: "Movie", year: "2020" },
{ title: "The Equalizer", type: "Movie", year: "1985" },

// SERIES
{ title: "The Expanse", type: "Series", year: "2015–2022" },
{ title: "Euphoria", type: "Series", year: "2019–" },
{ title: "Elementary", type: "Series", year: "2012–2019" },
{ title: "ER", type: "Series", year: "1994–2009" },
{ title: "Eastbound & Down", type: "Series", year: "2009–2013" },
{ title: "The End of the F***ing World", type: "Series", year: "2017–2019" },
{ title: "Emily in Paris", type: "Series", year: "2020–" },
{ title: "Entourage", type: "Series", year: "2004–2011" },

// DOCUMENTARIES
{ title: "Exit Through the Gift Shop", type: "Documentary", year: "2010" },
{ title: "The Endless Summer", type: "Documentary", year: "1966" },
{ title: "Enron: The Smartest Guys in the Room", type: "Documentary", year: "2005" },
{ title: "Earthlings", type: "Documentary", year: "2005" },
{ title: "Empire of Dreams: The Story of the Star Wars Trilogy", type: "Documentary", year: "2004" },
{ title: "The Elephant Queen", type: "Documentary", year: "2018" },
  
// F
// MOVIES
{ title: "Fight Club", type: "Movie", year: "1999" },
{ title: "Forrest Gump", type: "Movie", year: "1994" },
{ title: "The Fugitive", type: "Movie", year: "1993" },
{ title: "The French Connection", type: "Movie", year: "1971" },
{ title: "Fargo", type: "Movie", year: "1996" },
{ title: "Full Metal Jacket", type: "Movie", year: "1987" },
{ title: "The Florida Project", type: "Movie", year: "2017" },
{ title: "First Blood", type: "Movie", year: "1982" },
{ title: "The Fifth Element", type: "Movie", year: "1997" },
{ title: "Field of Dreams", type: "Movie", year: "1989" },
{ title: "The Fast and the Furious", type: "Movie", year: "2001" },
{ title: "Fast Five", type: "Movie", year: "2011" },
{ title: "Furious 7", type: "Movie", year: "2015" },
{ title: "The Favourite", type: "Movie", year: "2018" },
{ title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
{ title: "The Fighter", type: "Movie", year: "2010" },
{ title: "Finding Nemo", type: "Movie", year: "2003" },
{ title: "Finding Dory", type: "Movie", year: "2016" },
{ title: "The Firm", type: "Movie", year: "1993" },
{ title: "The Fly", type: "Movie", year: "1986" },
{ title: "The Founder", type: "Movie", year: "2016" },
{ title: "Free Guy", type: "Movie", year: "2021" },
{ title: "Friday", type: "Movie", year: "1995" },
{ title: "The Frighteners", type: "Movie", year: "1996" },
{ title: "The Fountain", type: "Movie", year: "2006" },
{ title: "Fried Green Tomatoes", type: "Movie", year: "1991" },
{ title: "Face/Off", type: "Movie", year: "1997" },
{ title: "The Faculty", type: "Movie", year: "1998" },
{ title: "Fantastic Mr. Fox", type: "Movie", year: "2009" },
{ title: "The Farewell", type: "Movie", year: "2019" },
{ title: "The Fault in Our Stars", type: "Movie", year: "2014" },
{ title: "The French Dispatch", type: "Movie", year: "2021" },
{ title: "Flight", type: "Movie", year: "2012" },
{ title: "Footloose", type: "Movie", year: "1984" },
{ title: "Flashdance", type: "Movie", year: "1983" },
{ title: "The Fast and the Furious: Tokyo Drift", type: "Movie", year: "2006" },
{ title: "The Fast and the Furious 6", type: "Movie", year: "2013" },
{ title: "Fences", type: "Movie", year: "2016" },
{ title: "The Fall", type: "Movie", year: "2006" },

// SERIES
{ title: "Friends", type: "Series", year: "1994–2004" },
{ title: "Fargo", type: "Series", year: "2014–" },
{ title: "Fleabag", type: "Series", year: "2016–2019" },
{ title: "Friday Night Lights", type: "Series", year: "2006–2011" },
{ title: "The Fall", type: "Series", year: "2013–2016" },
{ title: "Firefly", type: "Series", year: "2002–2003" },
{ title: "The Flash", type: "Series", year: "2014–2023" },
{ title: "Foundation", type: "Series", year: "2021–" },
{ title: "The Following", type: "Series", year: "2013–2015" },
{ title: "Futurama", type: "Series", year: "1999–2023" },

// DOCUMENTARIES
{ title: "Free Solo", type: "Documentary", year: "2018" },
{ title: "The Fog of War", type: "Documentary", year: "2003" },
{ title: "Fyre", type: "Documentary", year: "2019" },
{ title: "Fahrenheit 9/11", type: "Documentary", year: "2004" },
{ title: "For Sama", type: "Documentary", year: "2019" },
{ title: "Five Came Back", type: "Documentary", year: "2017" },
{ title: "The Fear of 13", type: "Documentary", year: "2015" },
  
// G
// MOVIES
{ title: "Gladiator", type: "Movie", year: "2000" },
{ title: "The Godfather", type: "Movie", year: "1972" },
{ title: "The Godfather Part II", type: "Movie", year: "1974" },
{ title: "Goodfellas", type: "Movie", year: "1990" },
{ title: "Good Will Hunting", type: "Movie", year: "1997" },
{ title: "Gone Girl", type: "Movie", year: "2014" },
{ title: "Get Out", type: "Movie", year: "2017" },
{ title: "Ghostbusters", type: "Movie", year: "1984" },
{ title: "Ghostbusters: Afterlife", type: "Movie", year: "2021" },
{ title: "Gravity", type: "Movie", year: "2013" },
{ title: "The Grand Budapest Hotel", type: "Movie", year: "2014" },
{ title: "The Green Mile", type: "Movie", year: "1999" },
{ title: "The Great Gatsby", type: "Movie", year: "2013" },
{ title: "The Great Escape", type: "Movie", year: "1963" },
{ title: "Groundhog Day", type: "Movie", year: "1993" },
{ title: "The Goonies", type: "Movie", year: "1985" },
{ title: "Gran Torino", type: "Movie", year: "2008" },
{ title: "Good Morning, Vietnam", type: "Movie", year: "1987" },
{ title: "The Girl with the Dragon Tattoo", type: "Movie", year: "2011" },
{ title: "The Gentlemen", type: "Movie", year: "2019" },
{ title: "The Game", type: "Movie", year: "1997" },
{ title: "Gone Baby Gone", type: "Movie", year: "2007" },
{ title: "Gangs of New York", type: "Movie", year: "2002" },
{ title: "The Graduate", type: "Movie", year: "1967" },
{ title: "Grease", type: "Movie", year: "1978" },
{ title: "The Green Knight", type: "Movie", year: "2021" },
{ title: "The Good, the Bad and the Ugly", type: "Movie", year: "1966" },
{ title: "The Great Lebowski", type: "Movie", year: "1998" },
{ title: "Glass Onion", type: "Movie", year: "2022" },
{ title: "Godzilla Minus One", type: "Movie", year: "2023" },
{ title: "The Grey", type: "Movie", year: "2011" },
{ title: "The Girl on the Train", type: "Movie", year: "2016" },
{ title: "Green Book", type: "Movie", year: "2018" },
{ title: "The Gift", type: "Movie", year: "2015" },
{ title: "The Grudge", type: "Movie", year: "2004" },
{ title: "The Good Dinosaur", type: "Movie", year: "2015" },
{ title: "The Greatest Showman", type: "Movie", year: "2017" },
{ title: "G.I. Joe: The Rise of Cobra", type: "Movie", year: "2009" },
{ title: "G.I. Joe: Retaliation", type: "Movie", year: "2013" },

// SERIES
{ title: "Game of Thrones", type: "Series", year: "2011–2019" },
{ title: "The Good Place", type: "Series", year: "2016–2020" },
{ title: "The Good Wife", type: "Series", year: "2009–2016" },
{ title: "Glee", type: "Series", year: "2009–2015" },
{ title: "Girls", type: "Series", year: "2012–2017" },
{ title: "Gotham", type: "Series", year: "2014–2019" },
{ title: "Generation Kill", type: "Series", year: "2008" },
{ title: "The Great", type: "Series", year: "2020–2023" },
{ title: "Goliath", type: "Series", year: "2016–2021" },
{ title: "Griselda", type: "Series", year: "2024" },

// DOCUMENTARIES
{ title: "Grizzly Man", type: "Documentary", year: "2005" },
{ title: "The Gates of Heaven", type: "Documentary", year: "1978" },
{ title: "Gimme Shelter", type: "Documentary", year: "1970" },
{ title: "Going Clear: Scientology and the Prison of Belief", type: "Documentary", year: "2015" },
{ title: "The Game Changers", type: "Documentary", year: "2018" },
{ title: "George Harrison: Living in the Material World", type: "Documentary", year: "2011" },
  
// H
// MOVIES
{ title: "Heat", type: "Movie", year: "1995" },
{ title: "Her", type: "Movie", year: "2013" },
{ title: "The Hangover", type: "Movie", year: "2009" },
{ title: "The Hangover Part II", type: "Movie", year: "2011" },
{ title: "The Hangover Part III", type: "Movie", year: "2013" },
{ title: "Halloween", type: "Movie", year: "1978" },
{ title: "Halloween", type: "Movie", year: "2018" },
{ title: "The Hateful Eight", type: "Movie", year: "2015" },
{ title: "Hacksaw Ridge", type: "Movie", year: "2016" },
{ title: "The Hurt Locker", type: "Movie", year: "2008" },
{ title: "Home Alone", type: "Movie", year: "1990" },
{ title: "Home Alone 2: Lost in New York", type: "Movie", year: "1992" },
{ title: "How to Train Your Dragon", type: "Movie", year: "2010" },
{ title: "How to Train Your Dragon 2", type: "Movie", year: "2014" },
{ title: "How to Train Your Dragon: The Hidden World", type: "Movie", year: "2019" },
{ title: "The Hobbit: An Unexpected Journey", type: "Movie", year: "2012" },
{ title: "The Hobbit: The Desolation of Smaug", type: "Movie", year: "2013" },
{ title: "The Hobbit: The Battle of the Five Armies", type: "Movie", year: "2014" },
{ title: "The Hunger Games", type: "Movie", year: "2012" },
{ title: "The Hunger Games: Catching Fire", type: "Movie", year: "2013" },
{ title: "The Hunger Games: Mockingjay – Part 1", type: "Movie", year: "2014" },
{ title: "The Hunger Games: Mockingjay – Part 2", type: "Movie", year: "2015" },
{ title: "Hidden Figures", type: "Movie", year: "2016" },
{ title: "High Fidelity", type: "Movie", year: "2000" },
{ title: "The Highwaymen", type: "Movie", year: "2019" },
{ title: "Hugo", type: "Movie", year: "2011" },
{ title: "Hotel Rwanda", type: "Movie", year: "2004" },
{ title: "House of Gucci", type: "Movie", year: "2021" },
{ title: "The Host", type: "Movie", year: "2006" },
{ title: "Hot Fuzz", type: "Movie", year: "2007" },
{ title: "The Hunt", type: "Movie", year: "2012" },
{ title: "The Hunt for Red October", type: "Movie", year: "1990" },
{ title: "The Help", type: "Movie", year: "2011" },
{ title: "Happy Gilmore", type: "Movie", year: "1996" },
{ title: "The House of the Devil", type: "Movie", year: "2009" },
{ title: "The Half of It", type: "Movie", year: "2020" },
{ title: "Hancock", type: "Movie", year: "2008" },
{ title: "The Harder They Fall", type: "Movie", year: "2021" },

// SERIES
{ title: "House of Cards", type: "Series", year: "2013–2018" },
{ title: "House of the Dragon", type: "Series", year: "2022–" },
{ title: "The Handmaid's Tale", type: "Series", year: "2017–" },
{ title: "Homeland", type: "Series", year: "2011–2020" },
{ title: "Hannibal", type: "Series", year: "2013–2015" },
{ title: "Halt and Catch Fire", type: "Series", year: "2014–2017" },
{ title: "The Haunting of Hill House", type: "Series", year: "2018" },
{ title: "The Haunting of Bly Manor", type: "Series", year: "2020" },
{ title: "Heroes", type: "Series", year: "2006–2010" },
{ title: "Hacks", type: "Series", year: "2021–" },

// DOCUMENTARIES
{ title: "Hoop Dreams", type: "Documentary", year: "1994" },
{ title: "Harlan County, USA", type: "Documentary", year: "1976" },
{ title: "Hearts of Darkness: A Filmmaker's Apocalypse", type: "Documentary", year: "1991" },
{ title: "Homecoming: A Film by Beyoncé", type: "Documentary", year: "2019" },
{ title: "Human Flow", type: "Documentary", year: "2017" },
{ title: "Hype!", type: "Documentary", year: "1996" },
  
// I
// MOVIES
{ title: "Inception", type: "Movie", year: "2010" },
{ title: "Interstellar", type: "Movie", year: "2014" },
{ title: "Inglourious Basterds", type: "Movie", year: "2009" },
{ title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
{ title: "Indiana Jones and the Last Crusade", type: "Movie", year: "1989" },
{ title: "Indiana Jones and the Temple of Doom", type: "Movie", year: "1984" },
{ title: "Inside Out", type: "Movie", year: "2015" },
{ title: "Inside Out 2", type: "Movie", year: "2024" },
{ title: "Iron Man", type: "Movie", year: "2008" },
{ title: "Iron Man 2", type: "Movie", year: "2010" },
{ title: "Iron Man 3", type: "Movie", year: "2013" },
{ title: "In the Mood for Love", type: "Movie", year: "2000" },
{ title: "I Am Legend", type: "Movie", year: "2007" },
{ title: "I, Tonya", type: "Movie", year: "2017" },
{ title: "It", type: "Movie", year: "2017" },
{ title: "It Chapter Two", type: "Movie", year: "2019" },
{ title: "The Irishman", type: "Movie", year: "2019" },
{ title: "The Imitation Game", type: "Movie", year: "2014" },
{ title: "In Bruges", type: "Movie", year: "2008" },
{ title: "In the Heat of the Night", type: "Movie", year: "1967" },
{ title: "Into the Wild", type: "Movie", year: "2007" },
{ title: "Invasion of the Body Snatchers", type: "Movie", year: "1978" },
{ title: "The Insider", type: "Movie", year: "1999" },
{ title: "The Intouchables", type: "Movie", year: "2011" },
{ title: "Insomnia", type: "Movie", year: "2002" },
{ title: "Invictus", type: "Movie", year: "2009" },
{ title: "The Impossible", type: "Movie", year: "2012" },
{ title: "The Incredibles", type: "Movie", year: "2004" },
{ title: "The Incredibles 2", type: "Movie", year: "2018" },
{ title: "Inherent Vice", type: "Movie", year: "2014" },
{ title: "The Interview", type: "Movie", year: "2014" },
{ title: "Identity", type: "Movie", year: "2003" },
{ title: "Ice Age", type: "Movie", year: "2002" },
{ title: "The Ice Storm", type: "Movie", year: "1997" },
{ title: "The Illusionist", type: "Movie", year: "2006" },
{ title: "The Italian Job", type: "Movie", year: "2003" },

// SERIES
{ title: "The IT Crowd", type: "Series", year: "2006–2013" },
{ title: "Industry", type: "Series", year: "2020–" },
{ title: "The Invincible", type: "Series", year: "2024–" },
{ title: "Insecure", type: "Series", year: "2016–2021" },
{ title: "The Idol", type: "Series", year: "2023" },
{ title: "iCarly", type: "Series", year: "2007–2012" },
{ title: "The Imperfects", type: "Series", year: "2022" },

// DOCUMENTARIES
{ title: "Icarus", type: "Documentary", year: "2017" },
{ title: "Inside Job", type: "Documentary", year: "2010" },
{ title: "The Imposter", type: "Documentary", year: "2012" },
{ title: "Into the Inferno", type: "Documentary", year: "2016" },
{ title: "Ice on Fire", type: "Documentary", year: "2019" },
{ title: "The Ivory Game", type: "Documentary", year: "2016" },
  
// J
// MOVIES
{ title: "Jaws", type: "Movie", year: "1975" },
{ title: "Joker", type: "Movie", year: "2019" },
{ title: "Jurassic Park", type: "Movie", year: "1993" },
{ title: "Jurassic World", type: "Movie", year: "2015" },
{ title: "Jojo Rabbit", type: "Movie", year: "2019" },
{ title: "John Wick", type: "Movie", year: "2014" },
{ title: "John Wick: Chapter 2", type: "Movie", year: "2017" },
{ title: "John Wick: Chapter 3 – Parabellum", type: "Movie", year: "2019" },
{ title: "John Wick: Chapter 4", type: "Movie", year: "2023" },
{ title: "Jerry Maguire", type: "Movie", year: "1996" },
{ title: "Jackie Brown", type: "Movie", year: "1997" },
{ title: "The Jungle Book", type: "Movie", year: "1967" },
{ title: "The Jungle Book", type: "Movie", year: "2016" },
{ title: "The Jerk", type: "Movie", year: "1979" },
{ title: "Jumanji", type: "Movie", year: "1995" },
{ title: "Jumanji: Welcome to the Jungle", type: "Movie", year: "2017" },
{ title: "Jumanji: The Next Level", type: "Movie", year: "2019" },
{ title: "The Judge", type: "Movie", year: "2014" },
{ title: "Jarhead", type: "Movie", year: "2005" },
{ title: "The Joy Luck Club", type: "Movie", year: "1993" },
{ title: "Julie & Julia", type: "Movie", year: "2009" },
{ title: "The Jungle", type: "Movie", year: "2017" },
{ title: "Justice League", type: "Movie", year: "2017" },
{ title: "Zack Snyder's Justice League", type: "Movie", year: "2021" },
{ title: "Jack Reacher", type: "Movie", year: "2012" },
{ title: "Jack Reacher: Never Go Back", type: "Movie", year: "2016" },
{ title: "Jeepers Creepers", type: "Movie", year: "2001" },
{ title: "Juno", type: "Movie", year: "2007" },
{ title: "JFK", type: "Movie", year: "1991" },
{ title: "The Jeffersons Movie", type: "Movie", year: "1998" },

// SERIES
{ title: "Justified", type: "Series", year: "2010–2015" },
{ title: "Jack Ryan", type: "Series", year: "2018–2023" },
{ title: "Jane the Virgin", type: "Series", year: "2014–2019" },
{ title: "Jessica Jones", type: "Series", year: "2015–2019" },
{ title: "The Jetsons", type: "Series", year: "1962–1963" },
{ title: "Jury Duty", type: "Series", year: "2023" },
{ title: "The Jinx", type: "Series", year: "2015–2024" },

// DOCUMENTARIES
{ title: "Jiro Dreams of Sushi", type: "Documentary", year: "2011" },
{ title: "Jane", type: "Documentary", year: "2017" },
{ title: "The Jinx: The Life and Deaths of Robert Durst", type: "Documentary", year: "2015" },
{ title: "Jackass Number Two", type: "Documentary", year: "2006" },
{ title: "Jackass 3D", type: "Documentary", year: "2010" },
{ title: "Jackass Forever", type: "Documentary", year: "2022" },
  
// K
// MOVIES
{ title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
{ title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },
{ title: "Knives Out", type: "Movie", year: "2019" },
{ title: "Knocked Up", type: "Movie", year: "2007" },
{ title: "Kramer vs. Kramer", type: "Movie", year: "1979" },
{ title: "King Kong", type: "Movie", year: "1933" },
{ title: "King Kong", type: "Movie", year: "2005" },
{ title: "King Richard", type: "Movie", year: "2021" },
{ title: "The King's Speech", type: "Movie", year: "2010" },
{ title: "Kiss Kiss Bang Bang", type: "Movie", year: "2005" },
{ title: "The Karate Kid", type: "Movie", year: "1984" },
{ title: "The Karate Kid", type: "Movie", year: "2010" },
{ title: "K-PAX", type: "Movie", year: "2001" },
{ title: "The Kid", type: "Movie", year: "1921" },
{ title: "Kids", type: "Movie", year: "1995" },
{ title: "Kindergarten Cop", type: "Movie", year: "1990" },
{ title: "Kingdom of Heaven", type: "Movie", year: "2005" },
{ title: "The Killing Fields", type: "Movie", year: "1984" },
{ title: "The Killing of a Sacred Deer", type: "Movie", year: "2017" },
{ title: "Kick-Ass", type: "Movie", year: "2010" },
{ title: "Kick-Ass 2", type: "Movie", year: "2013" },
{ title: "The Kite Runner", type: "Movie", year: "2007" },
{ title: "Kubo and the Two Strings", type: "Movie", year: "2016" },
{ title: "Kong: Skull Island", type: "Movie", year: "2017" },
{ title: "Knowing", type: "Movie", year: "2009" },
{ title: "Krampus", type: "Movie", year: "2015" },
{ title: "K-19: The Widowmaker", type: "Movie", year: "2002" },
{ title: "Kelly's Heroes", type: "Movie", year: "1970" },
{ title: "The Kitchen", type: "Movie", year: "2019" },
{ title: "The King", type: "Movie", year: "2019" },

// SERIES
{ title: "Killing Eve", type: "Series", year: "2018–2022" },
{ title: "The Killing", type: "Series", year: "2011–2014" },
{ title: "Kingdom", type: "Series", year: "2019–2020" },
{ title: "King of the Hill", type: "Series", year: "1997–2010" },
{ title: "The Knick", type: "Series", year: "2014–2015" },
{ title: "Kaleidoscope", type: "Series", year: "2023" },
{ title: "The Kardashians", type: "Series", year: "2022–" },
{ title: "Kevin Can F**k Himself", type: "Series", year: "2021–2022" },

// DOCUMENTARIES
{ title: "Ken Burns: The Civil War", type: "Documentary", year: "1990" },
{ title: "Ken Burns: Baseball", type: "Documentary", year: "1994" },
{ title: "The Keepers", type: "Documentary", year: "2017" },
{ title: "Kurt Cobain: Montage of Heck", type: "Documentary", year: "2015" },
{ title: "King in the Wilderness", type: "Documentary", year: "2018" },
{ title: "The Killing Season", type: "Documentary", year: "2016" },
{ title: "Knock Down the House", type: "Documentary", year: "2019" },
  
// L
// MOVIES
{ title: "La La Land", type: "Movie", year: "2016" },
{ title: "L.A. Confidential", type: "Movie", year: "1997" },
{ title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
{ title: "The Lord of the Rings: The Two Towers", type: "Movie", year: "2002" },
{ title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },
{ title: "Logan", type: "Movie", year: "2017" },
{ title: "The Lion King", type: "Movie", year: "1994" },
{ title: "The Lion King", type: "Movie", year: "2019" },
{ title: "The Lighthouse", type: "Movie", year: "2019" },
{ title: "The Last Samurai", type: "Movie", year: "2003" },
{ title: "The Last of the Mohicans", type: "Movie", year: "1992" },
{ title: "The Last Duel", type: "Movie", year: "2021" },
{ title: "Little Miss Sunshine", type: "Movie", year: "2006" },
{ title: "Lost in Translation", type: "Movie", year: "2003" },
{ title: "Lethal Weapon", type: "Movie", year: "1987" },
{ title: "Lethal Weapon 2", type: "Movie", year: "1989" },
{ title: "Lethal Weapon 3", type: "Movie", year: "1992" },
{ title: "Lethal Weapon 4", type: "Movie", year: "1998" },
{ title: "Lincoln", type: "Movie", year: "2012" },
{ title: "Life Is Beautiful", type: "Movie", year: "1997" },
{ title: "Life of Pi", type: "Movie", year: "2012" },
{ title: "Looper", type: "Movie", year: "2012" },
{ title: "Love Actually", type: "Movie", year: "2003" },
{ title: "The Long Goodbye", type: "Movie", year: "1973" },
{ title: "The Lost Boys", type: "Movie", year: "1987" },
{ title: "The Lost City", type: "Movie", year: "2022" },
{ title: "Licorice Pizza", type: "Movie", year: "2021" },
{ title: "Lady Bird", type: "Movie", year: "2017" },
{ title: "The Legend of 1900", type: "Movie", year: "1998" },
{ title: "Lawrence of Arabia", type: "Movie", year: "1962" },
{ title: "The Lego Movie", type: "Movie", year: "2014" },
{ title: "The Lego Batman Movie", type: "Movie", year: "2017" },
{ title: "The Last Picture Show", type: "Movie", year: "1971" },
{ title: "The Longest Day", type: "Movie", year: "1962" },
{ title: "The Lobster", type: "Movie", year: "2015" },
{ title: "The Lovely Bones", type: "Movie", year: "2009" },
{ title: "The Lost Daughter", type: "Movie", year: "2021" },
{ title: "The Lady from Shanghai", type: "Movie", year: "1947" },
{ title: "The Lincoln Lawyer", type: "Movie", year: "2011" },
{ title: "The Little Mermaid", type: "Movie", year: "1989" },

// SERIES
{ title: "Lost", type: "Series", year: "2004–2010" },
{ title: "Loki", type: "Series", year: "2021–2023" },
{ title: "The Last of Us", type: "Series", year: "2023–" },
{ title: "Line of Duty", type: "Series", year: "2012–2021" },
{ title: "Louie", type: "Series", year: "2010–2015" },
{ title: "The Leftovers", type: "Series", year: "2014–2017" },
{ title: "Lucifer", type: "Series", year: "2016–2021" },
{ title: "Love, Death & Robots", type: "Series", year: "2019–" },
{ title: "The League", type: "Series", year: "2009–2015" },
{ title: "Little Fires Everywhere", type: "Series", year: "2020" },

// DOCUMENTARIES
{ title: "The Last Dance", type: "Documentary", year: "2020" },
{ title: "Life Itself", type: "Documentary", year: "2014" },
{ title: "The Last Waltz", type: "Documentary", year: "1978" },
{ title: "The Long Way Round", type: "Documentary", year: "2004" },
{ title: "LA 92", type: "Documentary", year: "2017" },
{ title: "Leaving Neverland", type: "Documentary", year: "2019" },
{ title: "Life in a Day", type: "Documentary", year: "2011" },
{ title: "The Look of Silence", type: "Documentary", year: "2014" },  
  
// M
// MOVIES
{ title: "The Matrix", type: "Movie", year: "1999" },
{ title: "The Matrix Reloaded", type: "Movie", year: "2003" },
{ title: "The Matrix Revolutions", type: "Movie", year: "2003" },
{ title: "Mad Max: Fury Road", type: "Movie", year: "2015" },
{ title: "Memento", type: "Movie", year: "2000" },
{ title: "Moonlight", type: "Movie", year: "2016" },
{ title: "Moneyball", type: "Movie", year: "2011" },
{ title: "Manchester by the Sea", type: "Movie", year: "2016" },
{ title: "Marriage Story", type: "Movie", year: "2019" },
{ title: "Mean Girls", type: "Movie", year: "2004" },
{ title: "Midnight in Paris", type: "Movie", year: "2011" },
{ title: "Minority Report", type: "Movie", year: "2002" },
{ title: "Mission: Impossible", type: "Movie", year: "1996" },
{ title: "Mission: Impossible II", type: "Movie", year: "2000" },
{ title: "Mission: Impossible III", type: "Movie", year: "2006" },
{ title: "Mission: Impossible – Ghost Protocol", type: "Movie", year: "2011" },
{ title: "Mission: Impossible – Rogue Nation", type: "Movie", year: "2015" },
{ title: "Mission: Impossible – Fallout", type: "Movie", year: "2018" },
{ title: "Mission: Impossible – Dead Reckoning Part One", type: "Movie", year: "2023" },
{ title: "Mad Men", type: "Movie", year: "N/A" }, 
{ title: "The Maltese Falcon", type: "Movie", year: "1941" },
{ title: "The Martian", type: "Movie", year: "2015" },
{ title: "The Menu", type: "Movie", year: "2022" },
{ title: "Mulholland Drive", type: "Movie", year: "2001" },
{ title: "Mrs. Doubtfire", type: "Movie", year: "1993" },
{ title: "Moulin Rouge!", type: "Movie", year: "2001" },
{ title: "Million Dollar Baby", type: "Movie", year: "2004" },
{ title: "The Mummy", type: "Movie", year: "1999" },
{ title: "The Mummy Returns", type: "Movie", year: "2001" },
{ title: "Midsommar", type: "Movie", year: "2019" },
{ title: "Misery", type: "Movie", year: "1990" },
{ title: "Mystic River", type: "Movie", year: "2003" },
{ title: "Moonrise Kingdom", type: "Movie", year: "2012" },
{ title: "The Magnificent Seven", type: "Movie", year: "1960" },
{ title: "Man on Fire", type: "Movie", year: "2004" },
{ title: "The Mask", type: "Movie", year: "1994" },
{ title: "The Mask of Zorro", type: "Movie", year: "1998" },
{ title: "My Cousin Vinny", type: "Movie", year: "1992" },
{ title: "My Big Fat Greek Wedding", type: "Movie", year: "2002" },
{ title: "The Mitchells vs. the Machines", type: "Movie", year: "2021" },

// SERIES
{ title: "Mad Men", type: "Series", year: "2007–2015" },
{ title: "Mindhunter", type: "Series", year: "2017–2019" },
{ title: "Mr. Robot", type: "Series", year: "2015–2019" },
{ title: "The Mandalorian", type: "Series", year: "2019–" },
{ title: "Modern Family", type: "Series", year: "2009–2020" },
{ title: "Mare of Easttown", type: "Series", year: "2021" },
{ title: "Monk", type: "Series", year: "2002–2009" },
{ title: "Money Heist", type: "Series", year: "2017–2021" },
{ title: "The Morning Show", type: "Series", year: "2019–" },
{ title: "Marvel's Daredevil", type: "Series", year: "2015–2018" },

// DOCUMENTARIES
{ title: "Making a Murderer", type: "Documentary", year: "2015–2018" },
{ title: "March of the Penguins", type: "Documentary", year: "2005" },
{ title: "Man on Wire", type: "Documentary", year: "2008" },
{ title: "The Last Dance", type: "Documentary", year: "2020" },
{ title: "My Octopus Teacher", type: "Documentary", year: "2020" },
{ title: "Miss Americana", type: "Documentary", year: "2020" },
{ title: "Metallica: Some Kind of Monster", type: "Documentary", year: "2004" },
{ title: "McMillions", type: "Documentary", year: "2020" },
  
// N
// MOVIES
{ title: "No Country for Old Men", type: "Movie", year: "2007" },
{ title: "No Time to Die", type: "Movie", year: "2021" },
{ title: "Nightcrawler", type: "Movie", year: "2014" },
{ title: "Network", type: "Movie", year: "1976" },
{ title: "The Nice Guys", type: "Movie", year: "2016" },
{ title: "The Notebook", type: "Movie", year: "2004" },
{ title: "Notting Hill", type: "Movie", year: "1999" },
{ title: "North by Northwest", type: "Movie", year: "1959" },
{ title: "Napoleon Dynamite", type: "Movie", year: "2004" },
{ title: "Natural Born Killers", type: "Movie", year: "1994" },
{ title: "The Naked Gun", type: "Movie", year: "1988" },
{ title: "The Naked Gun 2½: The Smell of Fear", type: "Movie", year: "1991" },
{ title: "The Naked Gun 33⅓: The Final Insult", type: "Movie", year: "1994" },
{ title: "National Treasure", type: "Movie", year: "2004" },
{ title: "National Treasure: Book of Secrets", type: "Movie", year: "2007" },
{ title: "Neighbors", type: "Movie", year: "2014" },
{ title: "The NeverEnding Story", type: "Movie", year: "1984" },
{ title: "The Nightmare Before Christmas", type: "Movie", year: "1993" },
{ title: "Night at the Museum", type: "Movie", year: "2006" },
{ title: "Night at the Museum: Battle of the Smithsonian", type: "Movie", year: "2009" },
{ title: "Night of the Living Dead", type: "Movie", year: "1968" },
{ title: "The Northman", type: "Movie", year: "2022" },
{ title: "Now You See Me", type: "Movie", year: "2013" },
{ title: "Now You See Me 2", type: "Movie", year: "2016" },
{ title: "The Nun", type: "Movie", year: "2018" },
{ title: "The Nun II", type: "Movie", year: "2023" },
{ title: "The Negotiator", type: "Movie", year: "1998" },
{ title: "Nomadland", type: "Movie", year: "2020" },
{ title: "The New World", type: "Movie", year: "2005" },
{ title: "Newsies", type: "Movie", year: "1992" },
{ title: "The Next Three Days", type: "Movie", year: "2010" },
{ title: "Nixon", type: "Movie", year: "1995" },
{ title: "Nobody", type: "Movie", year: "2021" },
{ title: "The Novice", type: "Movie", year: "2021" },
{ title: "Nerve", type: "Movie", year: "2016" },
{ title: "Nashville", type: "Movie", year: "1975" },
{ title: "Never Let Me Go", type: "Movie", year: "2010" },
{ title: "The Night House", type: "Movie", year: "2020" },
{ title: "New Jack City", type: "Movie", year: "1991" },
{ title: "The Name of the Rose", type: "Movie", year: "1986" },

// SERIES
{ title: "Narcos", type: "Series", year: "2015–2017" },
{ title: "Narcos: Mexico", type: "Series", year: "2018–2021" },
{ title: "The Night Of", type: "Series", year: "2016" },
{ title: "Normal People", type: "Series", year: "2020" },
{ title: "New Girl", type: "Series", year: "2011–2018" },
{ title: "Nip/Tuck", type: "Series", year: "2003–2010" },
{ title: "The Newsroom", type: "Series", year: "2012–2014" },
{ title: "Never Have I Ever", type: "Series", year: "2020–2023" },
{ title: "The Night Manager", type: "Series", year: "2016–" },
{ title: "NYPD Blue", type: "Series", year: "1993–2005" },

// DOCUMENTARIES
{ title: "The Nightmare", type: "Documentary", year: "2015" },
{ title: "The Netflix Effect", type: "Documentary", year: "2022" },
{ title: "Navalny", type: "Documentary", year: "2022" },
{ title: "No End in Sight", type: "Documentary", year: "2007" },
{ title: "No Direction Home: Bob Dylan", type: "Documentary", year: "2005" },
{ title: "Nostalgia for the Light", type: "Documentary", year: "2010" },
{ title: "Night and Fog", type: "Documentary", year: "1956" },
  
// O
// MOVIES
{ title: "Oppenheimer", type: "Movie", year: "2023" },
{ title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
{ title: "Once Upon a Time in the West", type: "Movie", year: "1968" },
{ title: "Ocean's Eleven", type: "Movie", year: "2001" },
{ title: "Ocean's Twelve", type: "Movie", year: "2004" },
{ title: "Ocean's Thirteen", type: "Movie", year: "2007" },
{ title: "Oldboy", type: "Movie", year: "2003" },
{ title: "The Others", type: "Movie", year: "2001" },
{ title: "The Outsiders", type: "Movie", year: "1983" },
{ title: "The Outlaw Josey Wales", type: "Movie", year: "1976" },
{ title: "Office Space", type: "Movie", year: "1999" },
{ title: "On the Waterfront", type: "Movie", year: "1954" },
{ title: "Open Range", type: "Movie", year: "2003" },
{ title: "Open Your Eyes", type: "Movie", year: "1997" },
{ title: "Orphan", type: "Movie", year: "2009" },
{ title: "The Orphanage", type: "Movie", year: "2007" },
{ title: "Out of the Furnace", type: "Movie", year: "2013" },
{ title: "Out of Sight", type: "Movie", year: "1998" },
{ title: "Outbreak", type: "Movie", year: "1995" },
{ title: "Over the Top", type: "Movie", year: "1987" },
{ title: "Oblivion", type: "Movie", year: "2013" },
{ title: "October Sky", type: "Movie", year: "1999" },
{ title: "Only Lovers Left Alive", type: "Movie", year: "2013" },
{ title: "The Omega Man", type: "Movie", year: "1971" },
{ title: "The Omen", type: "Movie", year: "1976" },
{ title: "Onward", type: "Movie", year: "2020" },
{ title: "The Other Guys", type: "Movie", year: "2010" },
{ title: "The Other Woman", type: "Movie", year: "2014" },
{ title: "Our Idiot Brother", type: "Movie", year: "2011" },
{ title: "Oz the Great and Powerful", type: "Movie", year: "2013" },

// SERIES
{ title: "Ozark", type: "Series", year: "2017–2022" },
{ title: "Orange Is the New Black", type: "Series", year: "2013–2019" },
{ title: "The Office (US)", type: "Series", year: "2005–2013" },
{ title: "The Office (UK)", type: "Series", year: "2001–2003" },
{ title: "Orphan Black", type: "Series", year: "2013–2017" },
{ title: "The OA", type: "Series", year: "2016–2019" },
{ title: "Outer Banks", type: "Series", year: "2020–" },
{ title: "Only Murders in the Building", type: "Series", year: "2021–" },
{ title: "One Tree Hill", type: "Series", year: "2003–2012" },
{ title: "The Odd Couple", type: "Series", year: "1970–1975" },

// DOCUMENTARIES
{ title: "OJ: Made in America", type: "Documentary", year: "2016" },
{ title: "Our Planet", type: "Documentary", year: "2019–" },
{ title: "One Child Nation", type: "Documentary", year: "2019" },
{ title: "The Overnighters", type: "Documentary", year: "2014" },
{ title: "Operation Odessa", type: "Documentary", year: "2018" },
{ title: "One Day in September", type: "Documentary", year: "1999" },
{ title: "Out of the Shadows", type: "Documentary", year: "2020" },
  
// P
// MOVIES
{ title: "Pulp Fiction", type: "Movie", year: "1994" },
{ title: "Parasite", type: "Movie", year: "2019" },
{ title: "The Prestige", type: "Movie", year: "2006" },
{ title: "Prisoners", type: "Movie", year: "2013" },
{ title: "Pan's Labyrinth", type: "Movie", year: "2006" },
{ title: "Platoon", type: "Movie", year: "1986" },
{ title: "Patton", type: "Movie", year: "1970" },
{ title: "The Pianist", type: "Movie", year: "2002" },
{ title: "The Princess Bride", type: "Movie", year: "1987" },
{ title: "Pirates of the Caribbean: The Curse of the Black Pearl", type: "Movie", year: "2003" },
{ title: "Pirates of the Caribbean: Dead Man's Chest", type: "Movie", year: "2006" },
{ title: "Pirates of the Caribbean: At World's End", type: "Movie", year: "2007" },
{ title: "The Place Beyond the Pines", type: "Movie", year: "2012" },
{ title: "Pretty Woman", type: "Movie", year: "1990" },
{ title: "Pretty in Pink", type: "Movie", year: "1986" },
{ title: "The Pursuit of Happyness", type: "Movie", year: "2006" },
{ title: "Pineapple Express", type: "Movie", year: "2008" },
{ title: "Point Break", type: "Movie", year: "1991" },
{ title: "Promising Young Woman", type: "Movie", year: "2020" },
{ title: "The Post", type: "Movie", year: "2017" },
{ title: "Phone Booth", type: "Movie", year: "2002" },
{ title: "The Patriot", type: "Movie", year: "2000" },
{ title: "Pacific Rim", type: "Movie", year: "2013" },
{ title: "The Peanut Butter Falcon", type: "Movie", year: "2019" },
{ title: "Philadelphia", type: "Movie", year: "1993" },
{ title: "Public Enemies", type: "Movie", year: "2009" },
{ title: "The Pelican Brief", type: "Movie", year: "1993" },
{ title: "The Pink Panther", type: "Movie", year: "1963" },
{ title: "Pitch Perfect", type: "Movie", year: "2012" },
{ title: "Paddington", type: "Movie", year: "2014" },
{ title: "Paddington 2", type: "Movie", year: "2017" },
{ title: "Palm Springs", type: "Movie", year: "2020" },
{ title: "The Power of the Dog", type: "Movie", year: "2021" },
{ title: "The Phantom of the Opera", type: "Movie", year: "2004" },
{ title: "Psycho", type: "Movie", year: "1960" },
{ title: "The Purge", type: "Movie", year: "2013" },
{ title: "The Purge: Anarchy", type: "Movie", year: "2014" },
{ title: "The Purge: Election Year", type: "Movie", year: "2016" },
{ title: "The Proposal", type: "Movie", year: "2009" },
{ title: "Planes, Trains and Automobiles", type: "Movie", year: "1987" },
{ title: "The Player", type: "Movie", year: "1992" },
{ title: "Poltergeist", type: "Movie", year: "1982" },
{ title: "The Prince of Egypt", type: "Movie", year: "1998" },
{ title: "The Punisher", type: "Movie", year: "2004" },

// SERIES
{ title: "Peaky Blinders", type: "Series", year: "2013–2022" },
{ title: "The Pacific", type: "Series", year: "2010" },
{ title: "Parks and Recreation", type: "Series", year: "2009–2015" },
{ title: "Penny Dreadful", type: "Series", year: "2014–2016" },
{ title: "Pose", type: "Series", year: "2018–2021" },
{ title: "Prison Break", type: "Series", year: "2005–2017" },
{ title: "The Practice", type: "Series", year: "1997–2004" },
{ title: "The Peripheral", type: "Series", year: "2022" },
{ title: "P-Valley", type: "Series", year: "2020–" },
{ title: "Perry Mason", type: "Series", year: "2020–2023" },

// DOCUMENTARIES
{ title: "Planet Earth", type: "Documentary", year: "2006" },
{ title: "Planet Earth II", type: "Documentary", year: "2016" },
{ title: "The Pixar Story", type: "Documentary", year: "2007" },
{ title: "The Pruitt-Igoe Myth", type: "Documentary", year: "2011" },
{ title: "The Paradise Lost Trilogy", type: "Documentary", year: "1996–2011" },
{ title: "Pumping Iron", type: "Documentary", year: "1977" },
{ title: "The Phenomenon", type: "Documentary", year: "2020" },
{ title: "Project Nim", type: "Documentary", year: "2011" },
{ title: "The People vs. George Lucas", type: "Documentary", year: "2010" },
{ title: "The Playbook", type: "Documentary", year: "2020" },

// Q
// MOVIES
{ title: "Quantum of Solace", type: "Movie", year: "2008" },
{ title: "A Quiet Place", type: "Movie", year: "2018" },
{ title: "A Quiet Place Part II", type: "Movie", year: "2021" },
{ title: "Quiz Show", type: "Movie", year: "1994" },
{ title: "Quills", type: "Movie", year: "2000" },
{ title: "The Quick and the Dead", type: "Movie", year: "1995" },
{ title: "Queen of Katwe", type: "Movie", year: "2016" },
{ title: "Queen & Slim", type: "Movie", year: "2019" },
{ title: "The Queen", type: "Movie", year: "2006" },
{ title: "The Queen's Corgi", type: "Movie", year: "2019" },
{ title: "Quarantine", type: "Movie", year: "2008" },
{ title: "Quigley Down Under", type: "Movie", year: "1990" },
{ title: "The Quatermass Xperiment", type: "Movie", year: "1955" },
{ title: "Quo Vadis", type: "Movie", year: "1951" },
{ title: "The Quarry", type: "Movie", year: "2020" },

// SERIES
{ title: "The Queen's Gambit", type: "Series", year: "2020" },
{ title: "Queer as Folk", type: "Series", year: "1999–2000" },
{ title: "Queer Eye", type: "Series", year: "2018–" },
{ title: "Quarry", type: "Series", year: "2016" },
{ title: "Quantum Leap", type: "Series", year: "1989–1993" },
{ title: "Quantum Leap", type: "Series", year: "2022–2024" },

// DOCUMENTARIES
{ title: "The Queen of Versailles", type: "Documentary", year: "2012" },
{ title: "Quincy", type: "Documentary", year: "2018" },
{ title: "Q: Into the Storm", type: "Documentary", year: "2021" },
{ title: "Quick Change Artists", type: "Documentary", year: "2020" },
{ title: "Quest", type: "Documentary", year: "2017" },

// R
// MOVIES
{ title: "Raiders of the Lost Ark", type: "Movie", year: "1981" },
{ title: "Raging Bull", type: "Movie", year: "1980" },
{ title: "Rain Man", type: "Movie", year: "1988" },
{ title: "Ratatouille", type: "Movie", year: "2007" },
{ title: "Rear Window", type: "Movie", year: "1954" },
{ title: "Rebel Without a Cause", type: "Movie", year: "1955" },
{ title: "The Red Shoes", type: "Movie", year: "1948" },
{ title: "The Revenant", type: "Movie", year: "2015" },
{ title: "Requiem for a Dream", type: "Movie", year: "2000" },
{ title: "Reservoir Dogs", type: "Movie", year: "1992" },
{ title: "The Ring", type: "Movie", year: "2002" },
{ title: "The Right Stuff", type: "Movie", year: "1983" },
{ title: "Risky Business", type: "Movie", year: "1983" },
{ title: "Road House", type: "Movie", year: "1989" },
{ title: "Road to Perdition", type: "Movie", year: "2002" },
{ title: "RoboCop", type: "Movie", year: "1987" },
{ title: "Rocky", type: "Movie", year: "1976" },
{ title: "Rocky II", type: "Movie", year: "1979" },
{ title: "Rocky III", type: "Movie", year: "1982" },
{ title: "Rocky IV", type: "Movie", year: "1985" },
{ title: "Rocky Balboa", type: "Movie", year: "2006" },
{ title: "Rogue One: A Star Wars Story", type: "Movie", year: "2016" },
{ title: "Roman Holiday", type: "Movie", year: "1953" },
{ title: "Romeo + Juliet", type: "Movie", year: "1996" },
{ title: "Room", type: "Movie", year: "2015" },
{ title: "The Royal Tenenbaums", type: "Movie", year: "2001" },
{ title: "Rush", type: "Movie", year: "2013" },
{ title: "Rushmore", type: "Movie", year: "1998" },
{ title: "Ruthless People", type: "Movie", year: "1986" },
{ title: "Run Lola Run", type: "Movie", year: "1998" },
{ title: "The Rundown", type: "Movie", year: "2003" },
{ title: "Ready Player One", type: "Movie", year: "2018" },
{ title: "The Rock", type: "Movie", year: "1996" },
{ title: "Red Dragon", type: "Movie", year: "2002" },
{ title: "Red Eye", type: "Movie", year: "2005" },
{ title: "Red Sparrow", type: "Movie", year: "2018" },
{ title: "Red State", type: "Movie", year: "2011" },
{ title: "The Road", type: "Movie", year: "2009" },
{ title: "Robin Hood: Prince of Thieves", type: "Movie", year: "1991" },
{ title: "Rob Roy", type: "Movie", year: "1995" },

// SERIES
{ title: "The Rehearsal", type: "Series", year: "2022–" },
{ title: "Rome", type: "Series", year: "2005–2007" },
{ title: "The Righteous Gemstones", type: "Series", year: "2019–" },
{ title: "Rick and Morty", type: "Series", year: "2013–" },
{ title: "Riverdale", type: "Series", year: "2017–2023" },
{ title: "The Rookie", type: "Series", year: "2018–" },
{ title: "Rectify", type: "Series", year: "2013–2016" },
{ title: "Reservation Dogs", type: "Series", year: "2021–2023" },
{ title: "Ray Donovan", type: "Series", year: "2013–2020" },
{ title: "Reacher", type: "Series", year: "2022–" },

// DOCUMENTARIES
{ title: "Restrepo", type: "Documentary", year: "2010" },
{ title: "The Rescue", type: "Documentary", year: "2021" },
{ title: "Roger & Me", type: "Documentary", year: "1989" },
{ title: "RBG", type: "Documentary", year: "2018" },
{ title: "The Rape of Europa", type: "Documentary", year: "2006" },
{ title: "Rolling Thunder Revue: A Bob Dylan Story by Martin Scorsese", type: "Documentary", year: "2019" },
{ title: "ReMastered", type: "Documentary", year: "2018–" },
{ title: "Rise of Empires: Ottoman", type: "Documentary", year: "2020–2022" },

// S
// MOVIES
{ title: "Saving Private Ryan", type: "Movie", year: "1998" },
{ title: "Scarface", type: "Movie", year: "1983" },
{ title: "Schindler's List", type: "Movie", year: "1993" },
{ title: "Se7en", type: "Movie", year: "1995" },
{ title: "The Shawshank Redemption", type: "Movie", year: "1994" },
{ title: "Sicario", type: "Movie", year: "2015" },
{ title: "Silver Linings Playbook", type: "Movie", year: "2012" },
{ title: "The Silence of the Lambs", type: "Movie", year: "1991" },
{ title: "The Sixth Sense", type: "Movie", year: "1999" },
{ title: "Skyfall", type: "Movie", year: "2012" },
{ title: "Slumdog Millionaire", type: "Movie", year: "2008" },
{ title: "Snowpiercer", type: "Movie", year: "2013" },
{ title: "The Social Network", type: "Movie", year: "2010" },
{ title: "Spider-Man: Into the Spider-Verse", type: "Movie", year: "2018" },
{ title: "Spider-Man: No Way Home", type: "Movie", year: "2021" },
{ title: "Spirited Away", type: "Movie", year: "2001" },
{ title: "Spotlight", type: "Movie", year: "2015" },
{ title: "Stand by Me", type: "Movie", year: "1986" },
{ title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
{ title: "Superbad", type: "Movie", year: "2007" },
{ title: "Saturday Night Fever", type: "Movie", year: "1977" },
{ title: "Scott Pilgrim vs. the World", type: "Movie", year: "2010" },
{ title: "The Shape of Water", type: "Movie", year: "2017" },
{ title: "Shutter Island", type: "Movie", year: "2010" },
{ title: "Sideways", type: "Movie", year: "2004" },
{ title: "Singin' in the Rain", type: "Movie", year: "1952" },
{ title: "Sin City", type: "Movie", year: "2005" },
{ title: "The Sting", type: "Movie", year: "1973" },
{ title: "Straight Outta Compton", type: "Movie", year: "2015" },
{ title: "The Suicide Squad", type: "Movie", year: "2021" },
{ title: "Sunset Boulevard", type: "Movie", year: "1950" },
{ title: "Suspiria", type: "Movie", year: "1977" },
{ title: "The Sandlot", type: "Movie", year: "1993" },
{ title: "The Shining", type: "Movie", year: "1980" },
{ title: "Speed", type: "Movie", year: "1994" },
{ title: "The Spectacular Now", type: "Movie", year: "2013" },
{ title: "The Spy Who Loved Me", type: "Movie", year: "1977" },
{ title: "Star Trek", type: "Movie", year: "2009" },
{ title: "Star Trek II: The Wrath of Khan", type: "Movie", year: "1982" },
{ title: "Starship Troopers", type: "Movie", year: "1997" },

// SERIES
{ title: "Seinfeld", type: "Series", year: "1989–1998" },
{ title: "Sherlock", type: "Series", year: "2010–2017" },
{ title: "Stranger Things", type: "Series", year: "2016–" },
{ title: "Succession", type: "Series", year: "2018–2023" },
{ title: "Sex and the City", type: "Series", year: "1998–2004" },
{ title: "Six Feet Under", type: "Series", year: "2001–2005" },
{ title: "The Simpsons", type: "Series", year: "1989–" },
{ title: "Sons of Anarchy", type: "Series", year: "2008–2014" },
{ title: "South Park", type: "Series", year: "1997–" },
{ title: "The Shield", type: "Series", year: "2002–2008" },

// DOCUMENTARIES
{ title: "Searching for Sugar Man", type: "Documentary", year: "2012" },
{ title: "Senna", type: "Documentary", year: "2010" },
{ title: "Super Size Me", type: "Documentary", year: "2004" },
{ title: "The Staircase", type: "Documentary", year: "2004–2018" },
{ title: "Summer of Soul", type: "Documentary", year: "2021" },
{ title: "Shoah", type: "Documentary", year: "1985" },
{ title: "Stories We Tell", type: "Documentary", year: "2012" },
{ title: "Some Kind of Monster", type: "Documentary", year: "2004" },
{ title: "Sicko", type: "Documentary", year: "2007" },
{ title: "The Social Dilemma", type: "Documentary", year: "2020" },
  
 // T
// MOVIES
{ title: "Taxi Driver", type: "Movie", year: "1976" },
{ title: "The Talented Mr. Ripley", type: "Movie", year: "1999" },
{ title: "Tár", type: "Movie", year: "2022" },
{ title: "Tenet", type: "Movie", year: "2020" },
{ title: "The Terminator", type: "Movie", year: "1984" },
{ title: "Terminator 2: Judgment Day", type: "Movie", year: "1991" },
{ title: "The Texas Chain Saw Massacre", type: "Movie", year: "1974" },
{ title: "The Thin Red Line", type: "Movie", year: "1998" },
{ title: "Thor: Ragnarok", type: "Movie", year: "2017" },
{ title: "Three Billboards Outside Ebbing, Missouri", type: "Movie", year: "2017" },
{ title: "Titanic", type: "Movie", year: "1997" },
{ title: "Top Gun", type: "Movie", year: "1986" },
{ title: "Top Gun: Maverick", type: "Movie", year: "2022" },
{ title: "The Town", type: "Movie", year: "2010" },
{ title: "Training Day", type: "Movie", year: "2001" },
{ title: "Tropic Thunder", type: "Movie", year: "2008" },
{ title: "True Grit", type: "Movie", year: "2010" },
{ title: "The Truman Show", type: "Movie", year: "1998" },

// SERIES
{ title: "Taskmaster", type: "Series", year: "2015–" },
{ title: "The Sopranos", type: "Series", year: "1999–2007" },
{ title: "True Detective", type: "Series", year: "2014–" },
{ title: "Ted Lasso", type: "Series", year: "2020–2023" },
{ title: "The Twilight Zone", type: "Series", year: "1959–1964" },
{ title: "The Thick of It", type: "Series", year: "2005–2012" },

// DOCUMENTARIES
{ title: "The Thin Blue Line", type: "Documentary", year: "1988" },
{ title: "Tiger King", type: "Documentary", year: "2020" },
{ title: "The Act of Killing", type: "Documentary", year: "2012" },
{ title: "The Fog of War", type: "Documentary", year: "2003" },
{ title: "Touching the Void", type: "Documentary", year: "2003" },

// U
// MOVIES
{ title: "Unforgiven", type: "Movie", year: "1992" },
{ title: "Uncut Gems", type: "Movie", year: "2019" },
{ title: "Us", type: "Movie", year: "2019" },
{ title: "Up", type: "Movie", year: "2009" },
{ title: "Up in the Air", type: "Movie", year: "2009" },
{ title: "Upgrade", type: "Movie", year: "2018" },
{ title: "Unbreakable", type: "Movie", year: "2000" },
{ title: "Under the Skin", type: "Movie", year: "2013" },
{ title: "Uncle Buck", type: "Movie", year: "1989" },
{ title: "Unstoppable", type: "Movie", year: "2010" },
{ title: "United 93", type: "Movie", year: "2006" },
{ title: "Uncharted", type: "Movie", year: "2022" },
{ title: "Urban Cowboy", type: "Movie", year: "1980" },
{ title: "The Untouchables", type: "Movie", year: "1987" },
{ title: "Uncle Boonmee Who Can Recall His Past Lives", type: "Movie", year: "2010" },

// SERIES
{ title: "The Umbrella Academy", type: "Series", year: "2019–2024" },
{ title: "Unbelievable", type: "Series", year: "2019" },
{ title: "Undone", type: "Series", year: "2019–2022" },
{ title: "Unorthodox", type: "Series", year: "2020" },
{ title: "Utopia", type: "Series", year: "2013–2014" },

// DOCUMENTARIES
{ title: "Unknown: The Lost Pyramid", type: "Documentary", year: "2023" },
{ title: "Untold", type: "Documentary", year: "2021–" },
{ title: "Under the Sun", type: "Documentary", year: "2015" },
{ title: "Ukraine on Fire", type: "Documentary", year: "2016" },
{ title: "Unrest", type: "Documentary", year: "2017" },

// V
// MOVIES
{ title: "V for Vendetta", type: "Movie", year: "2005" },
{ title: "Vanilla Sky", type: "Movie", year: "2001" },
{ title: "Vertigo", type: "Movie", year: "1958" },
{ title: "Vice", type: "Movie", year: "2018" },
{ title: "Victoria", type: "Movie", year: "2015" },
{ title: "Videodrome", type: "Movie", year: "1983" },
{ title: "Vicky Cristina Barcelona", type: "Movie", year: "2008" },
{ title: "The Village", type: "Movie", year: "2004" },
{ title: "A View to a Kill", type: "Movie", year: "1985" },
{ title: "The Virgin Suicides", type: "Movie", year: "1999" },
{ title: "Volver", type: "Movie", year: "2006" },
{ title: "Venom", type: "Movie", year: "2018" },
{ title: "Venom: Let There Be Carnage", type: "Movie", year: "2021" },
{ title: "Valerian and the City of a Thousand Planets", type: "Movie", year: "2017" },
{ title: "Valkyrie", type: "Movie", year: "2008" },

// SERIES
{ title: "Veep", type: "Series", year: "2012–2019" },
{ title: "Vikings", type: "Series", year: "2013–2020" },
{ title: "Vikings: Valhalla", type: "Series", year: "2022–" },
{ title: "The Vampire Diaries", type: "Series", year: "2009–2017" },
{ title: "Veronica Mars", type: "Series", year: "2004–2019" },

// DOCUMENTARIES
{ title: "The Vietnam War", type: "Documentary", year: "2017" },
{ title: "Virunga", type: "Documentary", year: "2014" },
{ title: "Voyeur", type: "Documentary", year: "2017" },
{ title: "Val", type: "Documentary", year: "2021" },
{ title: "Vice", type: "Documentary", year: "2013–" },

// W
// MOVIES
{ title: "WALL·E", type: "Movie", year: "2008" },
{ title: "War of the Worlds", type: "Movie", year: "2005" },
{ title: "Warrior", type: "Movie", year: "2011" },
{ title: "Watchmen", type: "Movie", year: "2009" },
{ title: "Wedding Crashers", type: "Movie", year: "2005" },
{ title: "West Side Story", type: "Movie", year: "2021" },
{ title: "What We Do in the Shadows", type: "Movie", year: "2014" },
{ title: "Whiplash", type: "Movie", year: "2014" },
{ title: "When Harry Met Sally…", type: "Movie", year: "1989" },
{ title: "Who Framed Roger Rabbit", type: "Movie", year: "1988" },
{ title: "Widows", type: "Movie", year: "2018" },
{ title: "Wild", type: "Movie", year: "2014" },
{ title: "Wind River", type: "Movie", year: "2017" },
{ title: "The Witch", type: "Movie", year: "2015" },
{ title: "The Wolf of Wall Street", type: "Movie", year: "2013" },
{ title: "Wonder Boys", type: "Movie", year: "2000" },
{ title: "World War Z", type: "Movie", year: "2013" },
{ title: "The Wrestler", type: "Movie", year: "2008" },

// SERIES
{ title: "The Walking Dead", type: "Series", year: "2010–2022" },
{ title: "Watchmen", type: "Series", year: "2019" },
{ title: "The West Wing", type: "Series", year: "1999–2006" },
{ title: "What We Do in the Shadows", type: "Series", year: "2019–2024" },
{ title: "The Wire", type: "Series", year: "2002–2008" },

// DOCUMENTARIES
{ title: "Won't You Be My Neighbor?", type: "Documentary", year: "2018" },
{ title: "Woodstock", type: "Documentary", year: "1970" },
{ title: "The World at War", type: "Documentary", year: "1973–1974" },
{ title: "Wild Wild Country", type: "Documentary", year: "2018" },
{ title: "Weiner", type: "Documentary", year: "2016" },

// X
// MOVIES
{ title: "X", type: "Movie", year: "2022" },
{ title: "X2: X-Men United", type: "Movie", year: "2003" },
{ title: "X-Men", type: "Movie", year: "2000" },
{ title: "X-Men: Days of Future Past", type: "Movie", year: "2014" },
{ title: "X-Men: First Class", type: "Movie", year: "2011" },
{ title: "X-Men: The Last Stand", type: "Movie", year: "2006" },
{ title: "X-Men Origins: Wolverine", type: "Movie", year: "2009" },
{ title: "Xanadu", type: "Movie", year: "1980" },
{ title: "xXx", type: "Movie", year: "2002" },
{ title: "xXx: Return of Xander Cage", type: "Movie", year: "2017" },
{ title: "Xiu Xiu: The Sent-Down Girl", type: "Movie", year: "1998" },
{ title: "X: The Man with the X-Ray Eyes", type: "Movie", year: "1963" },

// SERIES
{ title: "X-Files", type: "Series", year: "1993–2018" },
{ title: "X-Men: The Animated Series", type: "Series", year: "1992–1997" },
{ title: "X-Men '97", type: "Series", year: "2024–" },
{ title: "XO, Kitty", type: "Series", year: "2023–" },
{ title: "Xena: Warrior Princess", type: "Series", year: "1995–2001" },

// DOCUMENTARIES
{ title: "XR: The Unheard Generation", type: "Documentary", year: "2020" },
{ title: "XTC: This Is Pop", type: "Documentary", year: "2017" },
  
// Y 
// MOVIES
{ title: "Y Tu Mamá También", type: "Movie", year: "2001" },
{ title: "Yojimbo", type: "Movie", year: "1961" },
{ title: "Young Frankenstein", type: "Movie", year: "1974" },
{ title: "Young Guns", type: "Movie", year: "1988" },
{ title: "Young Guns II", type: "Movie", year: "1990" },
{ title: "Young Adult", type: "Movie", year: "2011" },
{ title: "Youth", type: "Movie", year: "2015" },
{ title: "Youth in Revolt", type: "Movie", year: "2009" },
{ title: "Yesterday", type: "Movie", year: "2019" },
{ title: "Yentl", type: "Movie", year: "1983" },
{ title: "Yes Man", type: "Movie", year: "2008" },
{ title: "Yes, God, Yes", type: "Movie", year: "2019" },
{ title: "You Don't Mess with the Zohan", type: "Movie", year: "2008" },
{ title: "You Only Live Twice", type: "Movie", year: "1967" },
{ title: "You Were Never Really Here", type: "Movie", year: "2017" },
{ title: "You Can Count on Me", type: "Movie", year: "2000" },
{ title: "You Hurt My Feelings", type: "Movie", year: "2023" },
{ title: "You're Next", type: "Movie", year: "2011" },
{ title: "Your Name.", type: "Movie", year: "2016" },
{ title: "Your Friends & Neighbors", type: "Movie", year: "1998" },

// SERIES 
{ title: "Yellowstone", type: "Series", year: "2018–2024" },
{ title: "Yellowjackets", type: "Series", year: "2021–" },
{ title: "You", type: "Series", year: "2018–2024" },
{ title: "Yes Minister", type: "Series", year: "1980–1984" },
{ title: "Yes, Prime Minister", type: "Series", year: "1986–1988" },

// DOCUMENTARIES 
{ title: "Young @ Heart", type: "Documentary", year: "2007" },
{ title: "Yosemite: America's Treasure", type: "Documentary", year: "2010" },
{ title: "Yarn", type: "Documentary", year: "2016" },
{ title: "Yellow Is Forbidden", type: "Documentary", year: "2018" },
{ title: "You Cannot Kill David Arquette", type: "Documentary", year: "2020" },
  
// Z
// MOVIES
{ title: "Z", type: "Movie", year: "1969" },
{ title: "Zack and Miri Make a Porno", type: "Movie", year: "2008" },
{ title: "Zathura: A Space Adventure", type: "Movie", year: "2005" },
{ title: "Zelig", type: "Movie", year: "1983" },
{ title: "Zero Dark Thirty", type: "Movie", year: "2012" },
{ title: "Zero Effect", type: "Movie", year: "1998" },
{ title: "Zodiac", type: "Movie", year: "2007" },
{ title: "Zombieland", type: "Movie", year: "2009" },
{ title: "Zombieland: Double Tap", type: "Movie", year: "2019" },
{ title: "Zoolander", type: "Movie", year: "2001" },
{ title: "Zoolander 2", type: "Movie", year: "2016" },
{ title: "Zootopia", type: "Movie", year: "2016" },

// SERIES
{ title: "Z Nation", type: "Series", year: "2014–2018" },
{ title: "ZeroZeroZero", type: "Series", year: "2020" },
{ title: "Zoey's Extraordinary Playlist", type: "Series", year: "2020–2021" },

// DOCUMENTARIES
{ title: "Zeitgeist: The Movie", type: "Documentary", year: "2007" },
{ title: "Zappa", type: "Documentary", year: "2020" },
];
