// watchlist.js
// Just Movies, Series, Documentaries

window.WATCHLIST = [
  // A
  { title: "1917", type: "Movie", year: "2019" },
  { title: "12 Angry Men", type: "Movie", year: "1957" },
  { title: "12 Years a Slave", type: "Movie", year: "2013" },
  { title: "13th", type: "Documentary", year: "2016" },
  { title: "2001: A Space Odyssey", type: "Movie", year: "1968" },
  { title: "30 Rock", type: "Series", year: "2006–2013" },
  { title: "A Beautiful Mind", type: "Movie", year: "2001" },
  { title: "A Few Good Men", type: "Movie", year: "1992" },
  { title: "A Quiet Place", type: "Movie", year: "2018" },
  { title: "A Serious Man", type: "Movie", year: "2009" },
  { title: "A Star Is Born", type: "Movie", year: "2018" },
  { title: "About Time", type: "Movie", year: "2013" },
  { title: "Adaptation.", type: "Movie", year: "2002" },
  { title: "Air", type: "Movie", year: "2023" },
  { title: "Airplane!", type: "Movie", year: "1980" },
  { title: "Alien", type: "Movie", year: "1979" },
  { title: "All the President's Men", type: "Movie", year: "1976" },
  { title: "All Quiet on the Western Front", type: "Movie", year: "2022" },
  { title: "Almost Famous", type: "Movie", year: "2000" },
  { title: "American Psycho", type: "Movie", year: "2000" },
  { title: "American Factory", type: "Documentary", year: "2019" },
  { title: "Amélie", type: "Movie", year: "2001" },
  { title: "Anatomy of a Fall", type: "Movie", year: "2023" },
  { title: "Anchorman: The Legend of Ron Burgundy", type: "Movie", year: "2004" },
  { title: "Andor", type: "Series", year: "2022–" },
  { title: "Another Round", type: "Movie", year: "2020" },
  { title: "Annihilation", type: "Movie", year: "2018" },
  { title: "Apollo 11", type: "Documentary", year: "2019" },
  { title: "Apollo 13", type: "Movie", year: "1995" },
  { title: "Apocalypse Now", type: "Movie", year: "1979" },
  { title: "Arcane", type: "Series", year: "2021–" },
  { title: "Argo", type: "Movie", year: "2012" },
  { title: "Arrested Development", type: "Series", year: "2003–2019" },
  { title: "Arrival", type: "Movie", year: "2016" },
  { title: "As Good as It Gets", type: "Movie", year: "1997" },
  { title: "Atlanta", type: "Series", year: "2016–2022" },
  { title: "Avatar: The Last Airbender", type: "Series", year: "2005–2008" },
  { title: "Avengers: Endgame", type: "Movie", year: "2019" },

  // B
  { title: "Back to the Future", type: "Movie", year: "1985" },
  { title: "Band of Brothers", type: "Series", year: "2001" },
  { title: "Barbarian", type: "Movie", year: "2022" },
  { title: "Barbie", type: "Movie", year: "2023" },
  { title: "Barry", type: "Series", year: "2018–2023" },
  { title: "Beckham", type: "Documentary", year: "2023" },
  { title: "Before Midnight", type: "Movie", year: "2013" },
  { title: "Before Sunrise", type: "Movie", year: "1995" },
  { title: "Before Sunset", type: "Movie", year: "2004" },
  { title: "Belfast", type: "Movie", year: "2021" },
  { title: "Better Call Saul", type: "Series", year: "2015–2022" },
  { title: "Big", type: "Movie", year: "1988" },
  { title: "Big Little Lies", type: "Series", year: "2017–2019" },
  { title: "Birdman", type: "Movie", year: "2014" },
  { title: "Black Hawk Down", type: "Movie", year: "2001" },
  { title: "Black Mirror", type: "Series", year: "2011–" },
  { title: "Black Swan", type: "Movie", year: "2010" },
  { title: "Blade", type: "Movie", year: "1998" },
  { title: "Blade Runner", type: "Movie", year: "1982" },
  { title: "Blade Runner 2049", type: "Movie", year: "2017" },
  { title: "Blue Planet", type: "Documentary", year: "2001" },
  { title: "Blue Planet II", type: "Documentary", year: "2017" },
  { title: "Boardwalk Empire", type: "Series", year: "2010–2014" },
  { title: "BoJack Horseman", type: "Series", year: "2014–2020" },
  { title: "Boogie Nights", type: "Movie", year: "1997" },
  { title: "Borat", type: "Movie", year: "2006" },
  { title: "Bowling for Columbine", type: "Documentary", year: "2002" },
  { title: "Braveheart", type: "Movie", year: "1995" },
  { title: "Breaking Bad", type: "Series", year: "2008–2013" },
  { title: "Bridesmaids", type: "Movie", year: "2011" },
  { title: "Brooklyn Nine-Nine", type: "Series", year: "2013–2021" },
  { title: "Brokeback Mountain", type: "Movie", year: "2005" },
  { title: "Burn After Reading", type: "Movie", year: "2008" },
  { title: "Butch Cassidy and the Sundance Kid", type: "Movie", year: "1969" },

  // C
  { title: "Caddyshack", type: "Movie", year: "1980" },
  { title: "Call Me by Your Name", type: "Movie", year: "2017" },
  { title: "Casino Royale", type: "Movie", year: "2006" },
  { title: "Catch Me If You Can", type: "Movie", year: "2002" },
  { title: "Chef's Table", type: "Documentary", year: "2015–" },
  { title: "Chernobyl", type: "Series", year: "2019" },
  { title: "Chicago", type: "Movie", year: "2002" },
  { title: "Chinatown", type: "Movie", year: "1974" },
  { title: "Children of Men", type: "Movie", year: "2006" },
  { title: "Citizenfour", type: "Documentary", year: "2014" },
  { title: "City of God", type: "Movie", year: "2002" },
  { title: "Clerks", type: "Movie", year: "1994" },
  { title: "Clueless", type: "Movie", year: "1995" },
  { title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
  { title: "Coco", type: "Movie", year: "2017" },
  { title: "Community", type: "Series", year: "2009–2015" },
  { title: "Coming to America", type: "Movie", year: "1988" },
  { title: "Contact", type: "Movie", year: "1997" },
  { title: "Cool Hand Luke", type: "Movie", year: "1967" },
  { title: "Cosmos: A Personal Voyage", type: "Documentary", year: "1980" },
  { title: "Cosmos: A Spacetime Odyssey", type: "Documentary", year: "2014" },
  { title: "Crash", type: "Movie", year: "2004" },
  { title: "Crazy Rich Asians", type: "Movie", year: "2018" },
  { title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
  { title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },
  { title: "Curb Your Enthusiasm", type: "Series", year: "2000–2024" },

  // D
  { title: "Dallas Buyers Club", type: "Movie", year: "2013" },
  { title: "Dances with Wolves", type: "Movie", year: "1990" },
  { title: "Dark", type: "Series", year: "2017–2020" },
  { title: "Date Night", type: "Movie", year: "2010" },
  { title: "Dazed and Confused", type: "Movie", year: "1993" },
  { title: "Dead Poets Society", type: "Movie", year: "1989" },
  { title: "Dear Zachary: A Letter to a Son About His Father", type: "Documentary", year: "2008" },
  { title: "Die Hard", type: "Movie", year: "1988" },
  { title: "District 9", type: "Movie", year: "2009" },
  { title: "Django Unchained", type: "Movie", year: "2012" },
  { title: "Donnie Brasco", type: "Movie", year: "1997" },
  { title: "Donnie Darko", type: "Movie", year: "2001" },
  { title: "Drive", type: "Movie", year: "2011" },
  { title: "Dunkirk", type: "Movie", year: "2017" },
  { title: "Dune", type: "Movie", year: "2021" },
  { title: "Dune: Part Two", type: "Movie", year: "2024" },

  // E
  { title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
  { title: "Eighth Grade", type: "Movie", year: "2018" },
  { title: "Edge of Tomorrow", type: "Movie", year: "2014" },
  { title: "Elvis", type: "Movie", year: "2022" },
  { title: "Enemy", type: "Movie", year: "2013" },
  { title: "Enter the Dragon", type: "Movie", year: "1973" },
  { title: "Entourage", type: "Series", year: "2004–2011" },
  { title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
  { title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
  { title: "Ex Machina", type: "Movie", year: "2014" },
  { title: "Exit Through the Gift Shop", type: "Documentary", year: "2010" },
  { title: "Explained", type: "Documentary", year: "2018–" },

  // F
  { title: "Fargo", type: "Movie", year: "1996" },
  { title: "Fargo", type: "Series", year: "2014–" },
  { title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
  { title: "Fight Club", type: "Movie", year: "1999" },
  { title: "Finding Nemo", type: "Movie", year: "2003" },
  { title: "Fire of Love", type: "Documentary", year: "2022" },
  { title: "Fleabag", type: "Series", year: "2016–2019" },
  { title: "Forrest Gump", type: "Movie", year: "1994" },
  { title: "Free Solo", type: "Documentary", year: "2018" },
  { title: "Friday", type: "Movie", year: "1995" },
  { title: "Friends", type: "Series", year: "1994–2004" },
  { title: "Full Metal Jacket", type: "Movie", year: "1987" },

  // G
  { title: "Game of Thrones", type: "Series", year: "2011–2019" },
  { title: "Get Out", type: "Movie", year: "2017" },
  { title: "Ghostbusters", type: "Movie", year: "1984" },
  { title: "Gladiator", type: "Movie", year: "2000" },
  { title: "Glass Onion", type: "Movie", year: "2022" },
  { title: "Godzilla Minus One", type: "Movie", year: "2023" },
  { title: "Gone Girl", type: "Movie", year: "2014" },
  { title: "Goodfellas", type: "Movie", year: "1990" },
  { title: "Good Will Hunting", type: "Movie", year: "1997" },
  { title: "Gravity", type: "Movie", year: "2013" },
  { title: "Groundhog Day", type: "Movie", year: "1993" },

  // H
  { title: "Hacksaw Ridge", type: "Movie", year: "2016" },
  { title: "Halt and Catch Fire", type: "Series", year: "2014–2017" },
  { title: "Heat", type: "Movie", year: "1995" },
  { title: "Hell or High Water", type: "Movie", year: "2016" },
  { title: "Her", type: "Movie", year: "2013" },
  { title: "High Noon", type: "Movie", year: "1952" },
  { title: "Home Alone", type: "Movie", year: "1990" },
  { title: "House of the Dragon", type: "Series", year: "2022–" },

  // I
  { title: "In Bruges", type: "Movie", year: "2008" },
  { title: "Inception", type: "Movie", year: "2010" },
  { title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
  { title: "Inglourious Basterds", type: "Movie", year: "2009" },
  { title: "Inside Job", type: "Documentary", year: "2010" },
  { title: "Inside Out", type: "Movie", year: "2015" },
  { title: "Interstellar", type: "Movie", year: "2014" },
  { title: "Invincible", type: "Series", year: "2021–" },
  { title: "Icarus", type: "Documentary", year: "2017" },

  // J
  { title: "Jackie Brown", type: "Movie", year: "1997" },
  { title: "Jaws", type: "Movie", year: "1975" },
  { title: "Jerry Maguire", type: "Movie", year: "1996" },
  { title: "Jiro Dreams of Sushi", type: "Documentary", year: "2011" },
  { title: "John Wick", type: "Movie", year: "2014" },
  { title: "Jojo Rabbit", type: "Movie", year: "2019" },

  // K
  { title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
  { title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },
  { title: "King Richard", type: "Movie", year: "2021" },
  { title: "Knives Out", type: "Movie", year: "2019" },

  // L
  { title: "La La Land", type: "Movie", year: "2016" },
  { title: "Lady Bird", type: "Movie", year: "2017" },
  { title: "Letters from Iwo Jima", type: "Movie", year: "2006" },
  { title: "Licorice Pizza", type: "Movie", year: "2021" },
  { title: "Lost in Translation", type: "Movie", year: "2003" },
  { title: "Love Actually", type: "Movie", year: "2003" },

  // M
  { title: "Mad Max: Fury Road", type: "Movie", year: "2015" },
  { title: "Mad Men", type: "Series", year: "2007–2015" },
  { title: "Manchester by the Sea", type: "Movie", year: "2016" },
  { title: "Mare of Easttown", type: "Series", year: "2021" },
  { title: "Marriage Story", type: "Movie", year: "2019" },
  { title: "Mean Girls", type: "Movie", year: "2004" },
  { title: "Memento", type: "Movie", year: "2000" },
  { title: "Mindhunter", type: "Series", year: "2017–2019" },
  { title: "Moneyball", type: "Movie", year: "2011" },
  { title: "Moonlight", type: "Movie", year: "2016" },
  { title: "My Octopus Teacher", type: "Documentary", year: "2020" },

  // N
  { title: "Napoleon Dynamite", type: "Movie", year: "2004" },
  { title: "Narcos", type: "Series", year: "2015–2017" },
  { title: "Nightcrawler", type: "Movie", year: "2014" },
  { title: "No Country for Old Men", type: "Movie", year: "2007" },

  // O
  { title: "Ocean's Eleven", type: "Movie", year: "2001" },
  { title: "O.J.: Made in America", type: "Documentary", year: "2016" },
  { title: "Only Murders in the Building", type: "Series", year: "2021–" },
  { title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
  { title: "Oppenheimer", type: "Movie", year: "2023" },
  { title: "Our Planet", type: "Documentary", year: "2019" },
  { title: "Oz", type: "Series", year: "1997–2003" },

  // P
  { title: "Palm Springs", type: "Movie", year: "2020" },
  { title: "Parasite", type: "Movie", year: "2019" },
  { title: "Patton", type: "Movie", year: "1970" },
  { title: "Peaky Blinders", type: "Series", year: "2013–2022" },
  { title: "Pineapple Express", type: "Movie", year: "2008" },
  { title: "Planet Earth", type: "Documentary", year: "2006" },
  { title: "Planet Earth II", type: "Documentary", year: "2016" },
  { title: "Platoon", type: "Movie", year: "1986" },
  { title: "Poltergeist", type: "Movie", year: "1982" },
  { title: "Poor Things", type: "Movie", year: "2023" },
  { title: "Prisoners", type: "Movie", year: "2013" },
  { title: "Promising Young Woman", type: "Movie", year: "2020" },
  { title: "Pulp Fiction", type: "Movie", year: "1994" },

  // Q
  { title: "The Queen's Gambit", type: "Series", year: "2020" },

  // R
  { title: "Raging Bull", type: "Movie", year: "1980" },
  { title: "Rain Man", type: "Movie", year: "1988" },
  { title: "Reservoir Dogs", type: "Movie", year: "1992" },
  { title: "Rick and Morty", type: "Series", year: "2013–" },
  { title: "Rocky", type: "Movie", year: "1976" },

  // S
  { title: "Saving Private Ryan", type: "Movie", year: "1998" },
  { title: "Schitt's Creek", type: "Series", year: "2015–2020" },
  { title: "Seinfeld", type: "Series", year: "1989–1998" },
  { title: "Seven", type: "Movie", year: "1995" },
  { title: "Severance", type: "Series", year: "2022–" },
  { title: "Sherlock", type: "Series", year: "2010–2017" },
  { title: "Sicario", type: "Movie", year: "2015" },
  { title: "Silver Linings Playbook", type: "Movie", year: "2012" },
  { title: "Slow Horses", type: "Series", year: "2022–" },
  { title: "South Park", type: "Series", year: "1997–" },
  { title: "Spotlight", type: "Movie", year: "2015" },
  { title: "Spider-Man: Into the Spider-Verse", type: "Movie", year: "2018" },
  { title: "Spider-Man: No Way Home", type: "Movie", year: "2021" },
  { title: "Spirited Away", type: "Movie", year: "2001" },
  { title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
  { title: "Stranger Things", type: "Series", year: "2016–2025" },
  { title: "Succession", type: "Series", year: "2018–2023" },
  { title: "Summer of Soul", type: "Documentary", year: "2021" },
  { title: "Superbad", type: "Movie", year: "2007" },
  { title: "Super Troopers", type: "Movie", year: "2001" },

  // T
  { title: "Taskmaster", type: "Series", year: "2015–" },
  { title: "Ted Lasso", type: "Series", year: "2020–2023" },
  { title: "The Act of Killing", type: "Documentary", year: "2012" },
  { title: "The Bear", type: "Series", year: "2022–" },
  { title: "The Big Lebowski", type: "Movie", year: "1998" },
  { title: "The Big Short", type: "Movie", year: "2015" },
  { title: "The Breakfast Club", type: "Movie", year: "1985" },
  { title: "The Dark Knight", type: "Movie", year: "2008" },
  { title: "The Departed", type: "Movie", year: "2006" },
  { title: "The Exorcist", type: "Movie", year: "1973" },
  { title: "The Fog of War", type: "Documentary", year: "2003" },
  { title: "The Godfather", type: "Movie", year: "1972" },
  { title: "The Godfather Part II", type: "Movie", year: "1974" },
  { title: "The Grand Budapest Hotel", type: "Movie", year: "2014" },
  { title: "The Hateful Eight", type: "Movie", year: "2015" },
  { title: "The Holdovers", type: "Movie", year: "2023" },
  { title: "The Hurt Locker", type: "Movie", year: "2008" },
  { title: "The Last Dance", type: "Documentary", year: "2020" },
  { title: "The Last of Us", type: "Series", year: "2023–" },
  { title: "The Leftovers", type: "Series", year: "2014–2017" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
  { title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },
  { title: "The Mandalorian", type: "Series", year: "2019–" },
  { title: "The Matrix", type: "Movie", year: "1999" },
  { title: "The Menu", type: "Movie", year: "2022" },
  { title: "The Night Of", type: "Series", year: "2016" },
  { title: "The Northman", type: "Movie", year: "2022" },
  { title: "The Office (UK)", type: "Series", year: "2001–2003" },
  { title: "The Office (US)", type: "Series", year: "2005–2013" },
  { title: "The Prestige", type: "Movie", year: "2006" },
  { title: "The Princess Bride", type: "Movie", year: "1987" },
  { title: "The Rescue", type: "Documentary", year: "2021" },
  { title: "The Shawshank Redemption", type: "Movie", year: "1994" },
  { title: "The Shining", type: "Movie", year: "1980" },
  { title: "The Silence of the Lambs", type: "Movie", year: "1991" },
  { title: "The Social Network", type: "Movie", year: "2010" },
  { title: "The Social Dilemma", type: "Documentary", year: "2020" },
  { title: "The Sopranos", type: "Series", year: "1999–2007" },
  { title: "The Truman Show", type: "Movie", year: "1998" },
  { title: "The Vietnam War", type: "Documentary", year: "2017" },
  { title: "The White Lotus", type: "Series", year: "2021–" },
  { title: "The Wire", type: "Series", year: "2002–2008" },
  { title: "Titanic", type: "Movie", year: "1997" },
  { title: "Top Gun", type: "Movie", year: "1986" },
  { title: "Top Gun: Maverick", type: "Movie", year: "2022" },
  { title: "Toy Story", type: "Movie", year: "1995" },
  { title: "True Detective", type: "Series", year: "2014–" },

  // U
  { title: "Unforgiven", type: "Movie", year: "1992" },

  // V
  { title: "Veep", type: "Series", year: "2012–2019" },

  // W
  { title: "When Harry Met Sally…", type: "Movie", year: "1989" },
  { title: "Whiplash", type: "Movie", year: "2014" },
  { title: "Won't You Be My Neighbor?", type: "Documentary", year: "2018" },

  // Z
  { title: "Zodiac", type: "Movie", year: "2007" }
];
