window.WATCHLIST = [
  { title: "1917", type: "Movie", year: "2019" },
  { title: "A Beautiful Mind", type: "Movie", year: "2001" },
  { title: "A Quiet Place", type: "Movie", year: "2018" },
  { title: "About Time", type: "Movie", year: "2013" },
  { title: "Air", type: "Movie", year: "2023" },
  { title: "Airplane!", type: "Movie", year: "1980" },
  { title: "Alien", type: "Movie", year: "1979" },
  { title: "All the President's Men", type: "Movie", year: "1976" },
  { title: "Almost Famous", type: "Movie", year: "2000" },
  { title: "American Psycho", type: "Movie", year: "2000" },
  { title: "Amélie", type: "Movie", year: "2001" },
  { title: "Anchorman: The Legend of Ron Burgundy", type: "Movie", year: "2004" },
  { title: "Another Round", type: "Movie", year: "2020" },
  { title: "Apocalypse Now", type: "Movie", year: "1979" },
  { title: "Apollo 13", type: "Movie", year: "1995" },
  { title: "Argo", type: "Movie", year: "2012" },
  { title: "Arrival", type: "Movie", year: "2016" },

  { title: "Back to the Future", type: "Movie", year: "1985" },
  { title: "Band of Brothers", type: "TV", year: "2001" },
  { title: "Barbie", type: "Movie", year: "2023" },
  { title: "Beetlejuice", type: "Movie", year: "1988" },
  { title: "Before Sunrise", type: "Movie", year: "1995" },
  { title: "Belfast", type: "Movie", year: "2021" },
  { title: "Better Call Saul", type: "TV", year: "2015–2022" },
  { title: "Big", type: "Movie", year: "1988" },
  { title: "Big Little Lies", type: "TV", year: "2017–2019" },
  { title: "Birdman", type: "Movie", year: "2014" },
  { title: "Black Hawk Down", type: "Movie", year: "2001" },
  { title: "Black Mirror", type: "TV", year: "2011–2023" },
  { title: "Blade Runner", type: "Movie", year: "1982" },
  { title: "Blade Runner 2049", type: "Movie", year: "2017" },
  { title: "Boardwalk Empire", type: "TV", year: "2010–2014" },
  { title: "Borat", type: "Movie", year: "2006" },
  { title: "Braveheart", type: "Movie", year: "1995" },
  { title: "Bridesmaids", type: "Movie", year: "2011" },
  { title: "Brokeback Mountain", type: "Movie", year: "2005" },
  { title: "Butch Cassidy and the Sundance Kid", type: "Movie", year: "1969" },

  { title: "Caddyshack", type: "Movie", year: "1980" },
  { title: "Call Me by Your Name", type: "Movie", year: "2017" },
  { title: "Casino Royale", type: "Movie", year: "2006" },
  { title: "Catch Me If You Can", type: "Movie", year: "2002" },
  { title: "Chernobyl", type: "TV", year: "2019" },
  { title: "Chicago", type: "Movie", year: "2002" },
  { title: "Chinatown", type: "Movie", year: "1974" },
  { title: "Clueless", type: "Movie", year: "1995" },
  { title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
  { title: "Coco", type: "Movie", year: "2017" },
  { title: "Coming to America", type: "Movie", year: "1988" },
  { title: "Cool Hand Luke", type: "Movie", year: "1967" },
  { title: "Crash", type: "Movie", year: "2004" },
  { title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
  { title: "Crazy Rich Asians", type: "Movie", year: "2018" },
  { title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },

  { title: "Dallas Buyers Club", type: "Movie", year: "2013" },
  { title: "Date Night", type: "Movie", year: "2010" },
  { title: "Dances with Wolves", type: "Movie", year: "1990" },
  { title: "Dazed and Confused", type: "Movie", year: "1993" },
  { title: "Dead Poets Society", type: "Movie", year: "1989" },
  { title: "Death Proof", type: "Movie", year: "2007" },
  { title: "Die Hard", type: "Movie", year: "1988" },
  { title: "Donnie Brasco", type: "Movie", year: "1997" },
  { title: "Donnie Darko", type: "Movie", year: "2001" },
  { title: "Drive", type: "Movie", year: "2011" },
  { title: "Django Unchained", type: "Movie", year: "2012" },
  { title: "Dunkirk", type: "Movie", year: "2017" },
  { title: "Dune", type: "Movie", year: "2021" },
  { title: "Dune: Part Two", type: "Movie", year: "2024" },

  { title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
  { title: "Elvis", type: "Movie", year: "2022" },
  { title: "Enter the Dragon", type: "Movie", year: "1973" },
  { title: "Entourage", type: "TV", year: "2004–2011" },
  { title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
  { title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
  { title: "Ex Machina", type: "Movie", year: "2014" },
  { title: "The Exorcist", type: "Movie", year: "1973" },

  { title: "Fargo", type: "Movie", year: "1996" },
  { title: "Fargo", type: "TV", year: "2014–2024" },
  { title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
  { title: "Finding Nemo", type: "Movie", year: "2003" },
  { title: "Fight Club", type: "Movie", year: "1999" },
  { title: "Forrest Gump", type: "Movie", year: "1994" },
  { title: "Friday", type: "Movie", year: "1995" },
  { title: "Friends", type: "TV", year: "1994–2004" },
  { title: "Full Metal Jacket", type: "Movie", year: "1987" },

  { title: "Game of Thrones", type: "TV", year: "2011–2019" },
  { title: "Get Out", type: "Movie", year: "2017" },
  { title: "Ghostbusters", type: "Movie", year: "1984" },
  { title: "Gladiator", type: "Movie", year: "2000" },
  { title: "Glass Onion", type: "Movie", year: "2022" },
  { title: "The Godfather", type: "Movie", year: "1972" },
  { title: "The Godfather Part II", type: "Movie", year: "1974" },
  { title: "Goodfellas", type: "Movie", year: "1990" },
  { title: "Good Will Hunting", type: "Movie", year: "1997" },
  { title: "Groundhog Day", type: "Movie", year: "1993" },

  { title: "Hacksaw Ridge", type: "Movie", year: "2016" },
  { title: "The Hateful Eight", type: "Movie", year: "2015" },
  { title: "Heat", type: "Movie", year: "1995" },
  { title: "Her", type: "Movie", year: "2013" },
  { title: "High Noon", type: "Movie", year: "1952" },
  { title: "The Holdovers", type: "Movie", year: "2023" },
  { title: "Home Alone", type: "Movie", year: "1990" },

  { title: "Inception", type: "Movie", year: "2010" },
  { title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
  { title: "Inglourious Basterds", type: "Movie", year: "2009" },
  { title: "Inside Out", type: "Movie", year: "2015" },
  { title: "Interstellar", type: "Movie", year: "2014" },

  { title: "Jackie Brown", type: "Movie", year: "1997" },
  { title: "Jaws", type: "Movie", year: "1975" },
  { title: "Jerry Maguire", type: "Movie", year: "1996" },
  { title: "John Wick", type: "Movie", year: "2014" },
  { title: "Jurassic Park", type: "Movie", year: "1993" },

  { title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
  { title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },
  { title: "Knives Out", type: "Movie", year: "2019" },

  { title: "La La Land", type: "Movie", year: "2016" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
  { title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },

  { title: "Mad Men", type: "TV", year: "2007–2015" },
  { title: "Marriage Story", type: "Movie", year: "2019" },
  { title: "Mean Girls", type: "Movie", year: "2004" },
  { title: "Moneyball", type: "Movie", year: "2011" },

  { title: "Napoleon Dynamite", type: "Movie", year: "2004" },
  { title: "No Country for Old Men", type: "Movie", year: "2007" },

  { title: "Ocean's Eleven", type: "Movie", year: "2001" },
  { title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
  { title: "Oppenheimer", type: "Movie", year: "2023" },

  { title: "Parasite", type: "Movie", year: "2019" },
  { title: "Patton", type: "Movie", year: "1970" },
  { title: "Platoon", type: "Movie", year: "1986" },
  { title: "Pulp Fiction", type: "Movie", year: "1994" },

  { title: "Raging Bull", type: "Movie", year: "1980" },
  { title: "Reservoir Dogs", type: "Movie", year: "1992" },
  { title: "Rocky", type: "Movie", year: "1976" },

  { title: "Saving Private Ryan", type: "Movie", year: "1998" },
  { title: "Schitt's Creek", type: "TV", year: "2015–2020" },
  { title: "Seinfeld", type: "TV", year: "1989–1998" },
  { title: "Seven", type: "Movie", year: "1995" },
  { title: "Sex and the City", type: "TV", year: "1998–2004" },
  { title: "The Shawshank Redemption", type: "Movie", year: "1994" },
  { title: "Sicario", type: "Movie", year: "2015" },
  { title: "Spotlight", type: "Movie", year: "2015" },
  { title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
  { title: "Stranger Things", type: "TV", year: "2016–2025" },
  { title: "Succession", type: "TV", year: "2018–2023" },
  { title: "Superbad", type: "Movie", year: "2007" },

  { title: "Taskmaster", type: "TV", year: "2015–" },
  { title: "Ted Lasso", type: "TV", year: "2020–2023" },
  { title: "The Big Lebowski", type: "Movie", year: "1998" },
  { title: "The Departed", type: "Movie", year: "2006" },
  { title: "The Matrix", type: "Movie", year: "1999" },
  { title: "The Prestige", type: "Movie", year: "2006" },
  { title: "The Princess Bride", type: "Movie", year: "1987" },
  { title: "The Sopranos", type: "TV", year: "1999–2007" },
  { title: "The Truman Show", type: "Movie", year: "1998" },
  { title: "The White Lotus", type: "TV", year: "2021–2025" },
  { title: "The Wire", type: "TV", year: "2002–2008" },

  { title: "Titanic", type: "Movie", year: "1997" },
  { title: "Top Gun", type: "Movie", year: "1986" },
  { title: "Top Gun: Maverick", type: "Movie", year: "2022" },
  { title: "Toy Story", type: "Movie", year: "1995" },

  { title: "Unforgiven", type: "Movie", year: "1992" },
  { title: "Veep", type: "TV", year: "2012–2019" },
  { title: "Whiplash", type: "Movie", year: "2014" },
  { title: "When Harry Met Sally…", type: "Movie", year: "1989" },
  { title: "Zodiac", type: "Movie", year: "2007" }
  { title: "1917", type: "Movie", year: "2019" },
  { title: "A Beautiful Mind", type: "Movie", year: "2001" },
  { title: "A Quiet Place", type: "Movie", year: "2018" },
  { title: "About Time", type: "Movie", year: "2013" },
  { title: "Air", type: "Movie", year: "2023" },
  { title: "Airplane!", type: "Movie", year: "1980" },
  { title: "Alien", type: "Movie", year: "1979" },
  { title: "All the President's Men", type: "Movie", year: "1976" },
  { title: "Almost Famous", type: "Movie", year: "2000" },
  { title: "American Psycho", type: "Movie", year: "2000" },
  { title: "Amélie", type: "Movie", year: "2001" },
  { title: "Anchorman: The Legend of Ron Burgundy", type: "Movie", year: "2004" },
  { title: "Another Round", type: "Movie", year: "2020" },
  { title: "Apocalypse Now", type: "Movie", year: "1979" },
  { title: "Apollo 13", type: "Movie", year: "1995" },
  { title: "Argo", type: "Movie", year: "2012" },
  { title: "Arrival", type: "Movie", year: "2016" },
  { title: "As Good as It Gets", type: "Movie", year: "1997" },
  { title: "A Star Is Born", type: "Movie", year: "2018" },

  { title: "Back to the Future", type: "Movie", year: "1985" },
  { title: "Band of Brothers", type: "TV", year: "2001" },
  { title: "Barbarian", type: "Movie", year: "2022" },
  { title: "Barbie", type: "Movie", year: "2023" },
  { title: "Beetlejuice", type: "Movie", year: "1988" },
  { title: "Before Sunrise", type: "Movie", year: "1995" },
  { title: "Belfast", type: "Movie", year: "2021" },
  { title: "Better Call Saul", type: "TV", year: "2015–2022" },
  { title: "Big", type: "Movie", year: "1988" },
  { title: "Big Little Lies", type: "TV", year: "2017–2019" },
  { title: "Birdman", type: "Movie", year: "2014" },
  { title: "Black Hawk Down", type: "Movie", year: "2001" },
  { title: "Black Mirror", type: "TV", year: "2011–" },
  { title: "Black Swan", type: "Movie", year: "2010" },
  { title: "Blade Runner", type: "Movie", year: "1982" },
  { title: "Blade Runner 2049", type: "Movie", year: "2017" },
  { title: "Boardwalk Empire", type: "TV", year: "2010–2014" },
  { title: "Borat", type: "Movie", year: "2006" },
  { title: "Braveheart", type: "Movie", year: "1995" },
  { title: "Bridesmaids", type: "Movie", year: "2011" },
  { title: "Brokeback Mountain", type: "Movie", year: "2005" },
  { title: "Butch Cassidy and the Sundance Kid", type: "Movie", year: "1969" },

  { title: "Caddyshack", type: "Movie", year: "1980" },
  { title: "Call Me by Your Name", type: "Movie", year: "2017" },
  { title: "Casino Royale", type: "Movie", year: "2006" },
  { title: "Catch Me If You Can", type: "Movie", year: "2002" },
  { title: "Chernobyl", type: "TV", year: "2019" },
  { title: "Cheech & Chong's Up in Smoke", type: "Movie", year: "1978" },
  { title: "Chicago", type: "Movie", year: "2002" },
  { title: "Chinatown", type: "Movie", year: "1974" },
  { title: "Clerks", type: "Movie", year: "1994" },
  { title: "Clueless", type: "Movie", year: "1995" },
  { title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
  { title: "Coco", type: "Movie", year: "2017" },
  { title: "Coming to America", type: "Movie", year: "1988" },
  { title: "Cool Hand Luke", type: "Movie", year: "1967" },
  { title: "Crash", type: "Movie", year: "2004" },
  { title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
  { title: "Crazy Rich Asians", type: "Movie", year: "2018" },
  { title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },

  { title: "Dallas Buyers Club", type: "Movie", year: "2013" },
  { title: "Date Night", type: "Movie", year: "2010" },
  { title: "Dances with Wolves", type: "Movie", year: "1990" },
  { title: "Dazed and Confused", type: "Movie", year: "1993" },
  { title: "Dead Poets Society", type: "Movie", year: "1989" },
  { title: "Death Proof", type: "Movie", year: "2007" },
  { title: "Die Hard", type: "Movie", year: "1988" },
  { title: "Donnie Brasco", type: "Movie", year: "1997" },
  { title: "Donnie Darko", type: "Movie", year: "2001" },
  { title: "Drive", type: "Movie", year: "2011" },
  { title: "Django Unchained", type: "Movie", year: "2012" },
  { title: "Dunkirk", type: "Movie", year: "2017" },
  { title: "Dune", type: "Movie", year: "2021" },
  { title: "Dune: Part Two", type: "Movie", year: "2024" },

  { title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
  { title: "Elvis", type: "Movie", year: "2022" },
  { title: "Enter the Dragon", type: "Movie", year: "1973" },
  { title: "Entourage", type: "TV", year: "2004–2011" },
  { title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
  { title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
  { title: "Ex Machina", type: "Movie", year: "2014" },
  { title: "The Exorcist", type: "Movie", year: "1973" },

  { title: "Fargo", type: "Movie", year: "1996" },
  { title: "Fargo", type: "TV", year: "2014–" },
  { title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
  { title: "Finding Nemo", type: "Movie", year: "2003" },
  { title: "Fight Club", type: "Movie", year: "1999" },
  { title: "Flashdance", type: "Movie", year: "1983" },
  { title: "Footloose", type: "Movie", year: "1984" },
  { title: "Forrest Gump", type: "Movie", year: "1994" },
  { title: "Free Guy", type: "Movie", year: "2021" },
  { title: "Friday", type: "Movie", year: "1995" },
  { title: "Friends", type: "TV", year: "1994–2004" },
  { title: "Full Metal Jacket", type: "Movie", year: "1987" },
  { title: "The French Connection", type: "Movie", year: "1971" },

  { title: "Game of Thrones", type: "TV", year: "2011–2019" },
  { title: "Get Out", type: "Movie", year: "2017" },
  { title: "Ghostbusters", type: "Movie", year: "1984" },
  { title: "Girls", type: "TV", year: "2012–2017" },
  { title: "Gladiator", type: "Movie", year: "2000" },
  { title: "Glass Onion", type: "Movie", year: "2022" },
  { title: "The Godfather", type: "Movie", year: "1972" },
  { title: "The Godfather Part II", type: "Movie", year: "1974" },
  { title: "Godzilla Minus One", type: "Movie", year: "2023" },
  { title: "Gone Girl", type: "Movie", year: "2014" },
  { title: "Goodfellas", type: "Movie", year: "1990" },
  { title: "Good Morning, Vietnam", type: "Movie", year: "1987" },
  { title: "Good Will Hunting", type: "Movie", year: "1997" },
  { title: "Gravity", type: "Movie", year: "2013" },
  { title: "The Great Escape", type: "Movie", year: "1963" },
  { title: "The Great Gatsby", type: "Movie", year: "2013" },
  { title: "The Green Mile", type: "Movie", year: "1999" },
  { title: "Grease", type: "Movie", year: "1978" },
  { title: "Groundhog Day", type: "Movie", year: "1993" },

  { title: "Half Baked", type: "Movie", year: "1998" },
  { title: "Hacksaw Ridge", type: "Movie", year: "2016" },
  { title: "The Hateful Eight", type: "Movie", year: "2015" },
  { title: "Harry Potter and the Sorcerer's Stone", type: "Movie", year: "2001" },
  { title: "Heat", type: "Movie", year: "1995" },
  { title: "Her", type: "Movie", year: "2013" },
  { title: "High Noon", type: "Movie", year: "1952" },
  { title: "The Holdovers", type: "Movie", year: "2023" },
  { title: "Home Alone", type: "Movie", year: "1990" },

  { title: "Inception", type: "Movie", year: "2010" },
  { title: "Indiana Jones and the Last Crusade", type: "Movie", year: "1989" },
  { title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
  { title: "Inglourious Basterds", type: "Movie", year: "2009" },
  { title: "Inside Out", type: "Movie", year: "2015" },
  { title: "Interstellar", type: "Movie", year: "2014" },
  { title: "Jackie Brown", type: "Movie", year: "1997" },
  { title: "Jarhead", type: "Movie", year: "2005" },
  { title: "Jaws", type: "Movie", year: "1975" },
  { title: "Jerry Maguire", type: "Movie", year: "1996" },
  { title: "John Wick", type: "Movie", year: "2014" },
  { title: "Jojo Rabbit", type: "Movie", year: "2019" },
  { title: "Jurassic Park", type: "Movie", year: "1993" },

  { title: "Karate Kid", type: "Movie", year: "1984" },
  { title: "King Richard", type: "Movie", year: "2021" },
  { title: "Knives Out", type: "Movie", year: "2019" },
  { title: "Knocked Up", type: "Movie", year: "2007" },
  { title: "Kramer vs. Kramer", type: "Movie", year: "1979" },
  { title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
  { title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },

  { title: "L.A. Confidential", type: "Movie", year: "1997" },
  { title: "La La Land", type: "Movie", year: "2016" },
  { title: "Lady Bird", type: "Movie", year: "2017" },
  { title: "Letters from Iwo Jima", type: "Movie", year: "2006" },
  { title: "Lethal Weapon", type: "Movie", year: "1987" },
  { title: "Licorice Pizza", type: "Movie", year: "2021" },
  { title: "The Longest Day", type: "Movie", year: "1962" },
  { title: "Love Actually", type: "Movie", year: "2003" },

  { title: "Mad Max: Fury Road", type: "Movie", year: "2015" },
  { title: "Mad Men", type: "TV", year: "2007–2015" },
  { title: "Manchester by the Sea", type: "Movie", year: "2016" },
  { title: "Marcel the Shell with Shoes On", type: "Movie", year: "2021" },
  { title: "Marriage Story", type: "Movie", year: "2019" },
  { title: "Mean Girls", type: "Movie", year: "2004" },
  { title: "Men in Black", type: "Movie", year: "1997" },
  { title: "Midnight in Paris", type: "Movie", year: "2011" },
  { title: "Midway", type: "Movie", year: "2019" },
  { title: "Million Dollar Baby", type: "Movie", year: "2004" },
  { title: "Minari", type: "Movie", year: "2020" },
  { title: "Minority Report", type: "Movie", year: "2002" },
  { title: "Moneyball", type: "Movie", year: "2011" },
  { title: "Moonlight", type: "Movie", year: "2016" },
  { title: "Moonstruck", type: "Movie", year: "1987" },
  { title: "Mrs. Doubtfire", type: "Movie", year: "1993" },
  { title: "Moulin Rouge!", type: "Movie", year: "2001" },

  { title: "Napoleon Dynamite", type: "Movie", year: "2004" },
  { title: "Nightcrawler", type: "Movie", year: "2014" },
  { title: "No Country for Old Men", type: "Movie", year: "2007" },
  { title: "No Time to Die", type: "Movie", year: "2021" },

  { title: "Ocean's Eleven", type: "Movie", year: "2001" },
  { title: "Old School", type: "Movie", year: "2003" },
  { title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
  { title: "Once Upon a Time in the West", type: "Movie", year: "1968" },
  { title: "Oppenheimer", type: "Movie", year: "2023" },
  { title: "The Outlaw Josey Wales", type: "Movie", year: "1976" },
  { title: "Oz", type: "TV", year: "1997–2003" },

  { title: "Palm Springs", type: "Movie", year: "2020" },
  { title: "Parasite", type: "Movie", year: "2019" },
  { title: "Patton", type: "Movie", year: "1970" },
  { title: "Pineapple Express", type: "Movie", year: "2008" },
  { title: "Platoon", type: "Movie", year: "1986" },
  { title: "Poltergeist", type: "Movie", year: "1982" },
  { title: "Poor Things", type: "Movie", year: "2023" },
  { title: "Pretty in Pink", type: "Movie", year: "1986" },
  { title: "Pretty Woman", type: "Movie", year: "1990" },
  { title: "Prisoners", type: "Movie", year: "2013" },
  { title: "Pride & Prejudice", type: "Movie", year: "2005" },
  { title: "Promising Young Woman", type: "Movie", year: "2020" },
  { title: "Pulp Fiction", type: "Movie", year: "1994" },

  { title: "Raging Bull", type: "Movie", year: "1980" },
  { title: "Rain Man", type: "Movie", year: "1988" },
  { title: "Reservoir Dogs", type: "Movie", year: "1992" },
  { title: "Risky Business", type: "Movie", year: "1983" },
  { title: "Rocky", type: "Movie", year: "1976" },
  { title: "Rome", type: "TV", year: "2005–2007" },

  { title: "Saving Private Ryan", type: "Movie", year: "1998" },
  { title: "Saturday Night Fever", type: "Movie", year: "1977" },
  { title: "Schitt's Creek", type: "TV", year: "2015–2020" },
  { title: "Scott Pilgrim vs. the World", type: "Movie", year: "2010" },
  { title: "Seinfeld", type: "TV", year: "1989–1998" },
  { title: "Seven", type: "Movie", year: "1995" },
  { title: "Sex and the City", type: "TV", year: "1998–2004" },
  { title: "The Shawshank Redemption", type: "Movie", year: "1994" },
  { title: "Sherlock", type: "TV", year: "2010–2017" },
  { title: "Sicario", type: "Movie", year: "2015" },
  { title: "Silver Linings Playbook", type: "Movie", year: "2012" },
  { title: "Sleepless in Seattle", type: "Movie", year: "1993" },
  { title: "Spider-Man: Into the Spider-Verse", type: "Movie", year: "2018" },
  { title: "Spider-Man: No Way Home", type: "Movie", year: "2021" },
  { title: "Spirited Away", type: "Movie", year: "2001" },
  { title: "Spotlight", type: "Movie", year: "2015" },
  { title: "Stand by Me", type: "Movie", year: "1986" },
  { title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
  { title: "Stranger Things", type: "TV", year: "2016–" },
  { title: "Succession", type: "TV", year: "2018–2023" },
  { title: "Superbad", type: "Movie", year: "2007" },
  { title: "Super Troopers", type: "Movie", year: "2001" },

  { title: "Taskmaster", type: "TV", year: "2015–" },
  { title: "Ted Lasso", type: "TV", year: "2020–2023" },
  { title: "The Batman", type: "Movie", year: "2022" },
  { title: "The Big Lebowski", type: "Movie", year: "1998" },
  { title: "The Big Short", type: "Movie", year: "2015" },
  { title: "The Big Sick", type: "Movie", year: "2017" },
  { title: "The Bourne Identity", type: "Movie", year: "2002" },
  { title: "The Breakfast Club", type: "Movie", year: "1985" },
  { title: "The Dark Knight", type: "Movie", year: "2008" },
  { title: "The Departed", type: "Movie", year: "2006" },
  { title: "The Devil Wears Prada", type: "Movie", year: "2006" },
  { title: "The Fugitive", type: "Movie", year: "1993" },
  { title: "The Good, the Bad and the Ugly", type: "Movie", year: "1966" },
  { title: "The Good Place", type: "TV", year: "2016–2020" },
  { title: "The Goonies", type: "Movie", year: "1985" },
  { title: "The Grand Budapest Hotel", type: "Movie", year: "2014" },
  { title: "The Green Knight", type: "Movie", year: "2021" },
  { title: "The Hangover", type: "Movie", year: "2009" },
  { title: "The Hurt Locker", type: "Movie", year: "2008" },
  { title: "The Leftovers", type: "TV", year: "2014–2017" },
  { title: "The Life Aquatic with Steve Zissou", type: "Movie", year: "2004" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
  { title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },
  { title: "The Magnificent Seven", type: "Movie", year: "1960" },
  { title: "The Matrix", type: "Movie", year: "1999" },
  { title: "The Matrix Reloaded", type: "Movie", year: "2003" },
  { title: "The Menu", type: "Movie", year: "2022" },
  { title: "The Night Of", type: "TV", year: "2016" },
  { title: "The Northman", type: "Movie", year: "2022" },
  { title: "The Office (UK)", type: "TV", year: "2001–2003" },
  { title: "The Office (US)", type: "TV", year: "2005–2013" },
  { title: "The Prestige", type: "Movie", year: "2006" },
  { title: "The Princess Bride", type: "Movie", year: "1987" },
  { title: "The Revenant", type: "Movie", year: "2015" },
  { title: "The Shape of Water", type: "Movie", year: "2017" },
  { title: "The Shining", type: "Movie", year: "1980" },
  { title: "The Silence of the Lambs", type: "Movie", year: "1991" },
  { title: "The Sixth Sense", type: "Movie", year: "1999" },
  { title: "The Social Network", type: "Movie", year: "2010" },
  { title: "The Sopranos", type: "TV", year: "1999–2007" },
  { title: "The Sting", type: "Movie", year: "1973" },
  { title: "The Terminator", type: "Movie", year: "1984" },
  { title: "The Texas Chain Saw Massacre", type: "Movie", year: "1974" },
  { title: "The Thin Red Line", type: "Movie", year: "1998" },
  { title: "The Towering Inferno", type: "Movie", year: "1974" },
  { title: "The Truman Show", type: "Movie", year: "1998" },
  { title: "The Unbearable Weight of Massive Talent", type: "Movie", year: "2022" },
  { title: "The White Lotus", type: "TV", year: "2021–" },
  { title: "The Wire", type: "TV", year: "2002–2008" },
  { title: "This Is the End", type: "Movie", year: "2013" },
  { title: "Titanic", type: "Movie", year: "1997" },
  { title: "Top Gun", type: "Movie", year: "1986" },
  { title: "Top Gun: Maverick", type: "Movie", year: "2022" },
  { title: "Tora! Tora! Tora!", type: "Movie", year: "1970" },
  { title: "Toy Story", type: "Movie", year: "1995" },
  { title: "Training Day", type: "Movie", year: "2001" },
  { title: "True Detective", type: "TV", year: "2014–" },
  { title: "True Grit", type: "Movie", year: "1969" },
  { title: "True Lies", type: "Movie", year: "1994" },

  { title: "Unforgiven", type: "Movie", year: "1992" },
  { title: "Up in Smoke", type: "Movie", year: "1978" },

  { title: "Veep", type: "TV", year: "2012–2019" },

  { title: "Wedding Crashers", type: "Movie", year: "2005" },
  { title: "We Were Soldiers", type: "Movie", year: "2002" },
  { title: "West Side Story", type: "Movie", year: "2021" },
  { title: "Whiplash", type: "Movie", year: "2014" },
  { title: "When Harry Met Sally…", type: "Movie", year: "1989" },
  { title: "Zodiac", type: "Movie", year: "2007" },
    window.WATCHLIST = [
  { title: "1917", type: "Movie", year: "2019" },
  { title: "A Beautiful Mind", type: "Movie", year: "2001" },
  { title: "A Quiet Place", type: "Movie", year: "2018" },
  { title: "About Time", type: "Movie", year: "2013" },
  { title: "Air", type: "Movie", year: "2023" },
  { title: "Airplane!", type: "Movie", year: "1980" },
  { title: "Alien", type: "Movie", year: "1979" },
  { title: "All the President's Men", type: "Movie", year: "1976" },
  { title: "Almost Famous", type: "Movie", year: "2000" },
  { title: "American Psycho", type: "Movie", year: "2000" },
  { title: "Amelie", type: "Movie", year: "2001" },
  { title: "Anchorman: The Legend of Ron Burgundy", type: "Movie", year: "2004" },
  { title: "Another Round", type: "Movie", year: "2020" },
  { title: "Apocalypse Now", type: "Movie", year: "1979" },
  { title: "Apollo 13", type: "Movie", year: "1995" },
  { title: "Argo", type: "Movie", year: "2012" },
  { title: "Arrival", type: "Movie", year: "2016" },

  { title: "Back to the Future", type: "Movie", year: "1985" },
  { title: "Band of Brothers", type: "Series", year: "2001" },
  { title: "Barbie", type: "Movie", year: "2023" },
  { title: "Beetlejuice", type: "Movie", year: "1988" },
  { title: "Before Sunrise", type: "Movie", year: "1995" },
  { title: "Belfast", type: "Movie", year: "2021" },
  { title: "Better Call Saul", type: "Series", year: "2015-2022" },
  { title: "Big", type: "Movie", year: "1988" },
  { title: "Big Little Lies", type: "Series", year: "2017-2019" },
  { title: "Birdman", type: "Movie", year: "2014" },
  { title: "Black Hawk Down", type: "Movie", year: "2001" },
  { title: "Black Mirror", type: "Series", year: "2011-2023" },
  { title: "Blade Runner", type: "Movie", year: "1982" },
  { title: "Blade Runner 2049", type: "Movie", year: "2017" },
  { title: "Boardwalk Empire", type: "Series", year: "2010-2014" },
  { title: "Borat", type: "Movie", year: "2006" },
  { title: "Braveheart", type: "Movie", year: "1995" },
  { title: "Bridesmaids", type: "Movie", year: "2011" },
  { title: "Brokeback Mountain", type: "Movie", year: "2005" },
  { title: "Butch Cassidy and the Sundance Kid", type: "Movie", year: "1969" },

  { title: "Caddyshack", type: "Movie", year: "1980" },
  { title: "Call Me by Your Name", type: "Movie", year: "2017" },
  { title: "Casino Royale", type: "Movie", year: "2006" },
  { title: "Catch Me If You Can", type: "Movie", year: "2002" },
  { title: "Chernobyl", type: "Series", year: "2019" },
  { title: "Chicago", type: "Movie", year: "2002" },
  { title: "Chinatown", type: "Movie", year: "1974" },
  { title: "Clueless", type: "Movie", year: "1995" },
  { title: "Close Encounters of the Third Kind", type: "Movie", year: "1977" },
  { title: "Coco", type: "Movie", year: "2017" },
  { title: "Coming to America", type: "Movie", year: "1988" },
  { title: "Cool Hand Luke", type: "Movie", year: "1967" },
  { title: "Crash", type: "Movie", year: "2004" },
  { title: "Crazy, Stupid, Love.", type: "Movie", year: "2011" },
  { title: "Crazy Rich Asians", type: "Movie", year: "2018" },
  { title: "Crouching Tiger, Hidden Dragon", type: "Movie", year: "2000" },

  { title: "Dallas Buyers Club", type: "Movie", year: "2013" },
  { title: "Date Night", type: "Movie", year: "2010" },
  { title: "Dances with Wolves", type: "Movie", year: "1990" },
  { title: "Dazed and Confused", type: "Movie", year: "1993" },
  { title: "Dead Poets Society", type: "Movie", year: "1989" },
  { title: "Death Proof", type: "Movie", year: "2007" },
  { title: "Die Hard", type: "Movie", year: "1988" },
  { title: "Donnie Brasco", type: "Movie", year: "1997" },
  { title: "Donnie Darko", type: "Movie", year: "2001" },
  { title: "Drive", type: "Movie", year: "2011" },
  { title: "Django Unchained", type: "Movie", year: "2012" },
  { title: "Dunkirk", type: "Movie", year: "2017" },
  { title: "Dune", type: "Movie", year: "2021" },
  { title: "Dune: Part Two", type: "Movie", year: "2024" },

  { title: "E.T. the Extra-Terrestrial", type: "Movie", year: "1982" },
  { title: "Elvis", type: "Movie", year: "2022" },
  { title: "Enter the Dragon", type: "Movie", year: "1973" },
  { title: "Entourage", type: "Series", year: "2004-2011" },
  { title: "Eternal Sunshine of the Spotless Mind", type: "Movie", year: "2004" },
  { title: "Everything Everywhere All at Once", type: "Movie", year: "2022" },
  { title: "Ex Machina", type: "Movie", year: "2014" },
  { title: "The Exorcist", type: "Movie", year: "1973" },

  { title: "Fargo", type: "Movie", year: "1996" },
  { title: "Fargo", type: "Series", year: "2014-2024" },
  { title: "Ferris Bueller's Day Off", type: "Movie", year: "1986" },
  { title: "Finding Nemo", type: "Movie", year: "2003" },
  { title: "Fight Club", type: "Movie", year: "1999" },
  { title: "Forrest Gump", type: "Movie", year: "1994" },
  { title: "Friday", type: "Movie", year: "1995" },
  { title: "Friends", type: "Series", year: "1994-2004" },
  { title: "Full Metal Jacket", type: "Movie", year: "1987" },

  { title: "Game of Thrones", type: "Series", year: "2011-2019" },
  { title: "Get Out", type: "Movie", year: "2017" },
  { title: "Ghostbusters", type: "Movie", year: "1984" },
  { title: "Gladiator", type: "Movie", year: "2000" },
  { title: "Glass Onion", type: "Movie", year: "2022" },
  { title: "The Godfather", type: "Movie", year: "1972" },
  { title: "The Godfather Part II", type: "Movie", year: "1974" },
  { title: "Goodfellas", type: "Movie", year: "1990" },
  { title: "Good Will Hunting", type: "Movie", year: "1997" },
  { title: "Groundhog Day", type: "Movie", year: "1993" },

  { title: "Hacksaw Ridge", type: "Movie", year: "2016" },
  { title: "The Hateful Eight", type: "Movie", year: "2015" },
  { title: "Heat", type: "Movie", year: "1995" },
  { title: "Her", type: "Movie", year: "2013" },
  { title: "High Noon", type: "Movie", year: "1952" },
  { title: "The Holdovers", type: "Movie", year: "2023" },
  { title: "Home Alone", type: "Movie", year: "1990" },

  { title: "Inception", type: "Movie", year: "2010" },
  { title: "Indiana Jones and the Raiders of the Lost Ark", type: "Movie", year: "1981" },
  { title: "Inglourious Basterds", type: "Movie", year: "2009" },
  { title: "Inside Out", type: "Movie", year: "2015" },
  { title: "Interstellar", type: "Movie", year: "2014" },

  { title: "Jackie Brown", type: "Movie", year: "1997" },
  { title: "Jaws", type: "Movie", year: "1975" },
  { title: "Jerry Maguire", type: "Movie", year: "1996" },
  { title: "John Wick", type: "Movie", year: "2014" },
  { title: "Jurassic Park", type: "Movie", year: "1993" },

  { title: "Kill Bill: Vol. 1", type: "Movie", year: "2003" },
  { title: "Kill Bill: Vol. 2", type: "Movie", year: "2004" },
  { title: "Knives Out", type: "Movie", year: "2019" },

  { title: "La La Land", type: "Movie", year: "2016" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", type: "Movie", year: "2001" },
  { title: "The Lord of the Rings: The Return of the King", type: "Movie", year: "2003" },

  { title: "Mad Men", type: "Series", year: "2007-2015" },
  { title: "Marriage Story", type: "Movie", year: "2019" },
  { title: "Mean Girls", type: "Movie", year: "2004" },
  { title: "Moneyball", type: "Movie", year: "2011" },

  { title: "Napoleon Dynamite", type: "Movie", year: "2004" },
  { title: "No Country for Old Men", type: "Movie", year: "2007" },

  { title: "Ocean's Eleven", type: "Movie", year: "2001" },
  { title: "Once Upon a Time in Hollywood", type: "Movie", year: "2019" },
  { title: "Oppenheimer", type: "Movie", year: "2023" },

  { title: "Parasite", type: "Movie", year: "2019" },
  { title: "Patton", type: "Movie", year: "1970" },
  { title: "Platoon", type: "Movie", year: "1986" },
  { title: "Pulp Fiction", type: "Movie", year: "1994" },

  { title: "Raging Bull", type: "Movie", year: "1980" },
  { title: "Reservoir Dogs", type: "Movie", year: "1992" },
  { title: "Rocky", type: "Movie", year: "1976" },

  { title: "Saving Private Ryan", type: "Movie", year: "1998" },
  { title: "Schitt's Creek", type: "Series", year: "2015-2020" },
  { title: "Seinfeld", type: "Series", year: "1989-1998" },
  { title: "Seven", type: "Movie", year: "1995" },
  { title: "Sex and the City", type: "Series", year: "1998-2004" },
  { title: "The Shawshank Redemption", type: "Movie", year: "1994" },
  { title: "Sicario", type: "Movie", year: "2015" },
  { title: "Spotlight", type: "Movie", year: "2015" },
  { title: "Star Wars: A New Hope", type: "Movie", year: "1977" },
  { title: "Stranger Things", type: "Series", year: "2016-2025" },
  { title: "Succession", type: "Series", year: "2018-2023" },
  { title: "Superbad", type: "Movie", year: "2007" },

  { title: "Taskmaster", type: "Series", year: "2015-" },
  { title: "Ted Lasso", type: "Series", year: "2020-2023" },
  { title: "The Big Lebowski", type: "Movie", year: "1998" },
  { title: "The Departed", type: "Movie", year: "2006" },
  { title: "The Matrix", type: "Movie", year: "1999" },
  { title: "The Prestige", type: "Movie", year: "2006" },
  { title: "The Princess Bride", type: "Movie", year: "1987" },
  { title: "The Sopranos", type: "Series", year: "1999-2007" },
  { title: "The Truman Show", type: "Movie", year: "1998" },
  { title: "The White Lotus", type: "Series", year: "2021-2025" },
  { title: "The Wire", type: "Series", year: "2002-2008" },

  { title: "Titanic", type: "Movie", year: "1997" },
  { title: "Top Gun", type: "Movie", year: "1986" },
  { title: "Top Gun: Maverick", type: "Movie", year: "2022" },
  { title: "Toy Story", type: "Movie", year: "1995" },

  { title: "Unforgiven", type: "Movie", year: "1992" },
  { title: "Veep", type: "Series", year: "2012-2019" },
  { title: "Whiplash", type: "Movie", year: "2014" },
  { title: "When Harry Met Sally...", type: "Movie", year: "1989" },
  { title: "Zodiac", type: "Movie", year: "2007" },

  /* +100 SERIES */
  { title: "Breaking Bad", type: "Series", year: "2008-2013" },
  { title: "The Americans", type: "Series", year: "2013-2018" },
  { title: "The Crown", type: "Series", year: "2016-2023" },
  { title: "The Bear", type: "Series", year: "2022-" },
  { title: "The Last of Us", type: "Series", year: "2023-" },
  { title: "Severance", type: "Series", year: "2022-" },
  { title: "The Mandalorian", type: "Series", year: "2019-" },
  { title: "Andor", type: "Series", year: "2022-" },
  { title: "The Expanse", type: "Series", year: "2015-2022" },
  { title: "Mr. Robot", type: "Series", year: "2015-2019" },
  { title: "The West Wing", type: "Series", year: "1999-2006" },
  { title: "The Office (US)", type: "Series", year: "2005-2013" },
  { title: "The Office (UK)", type: "Series", year: "2001-2003" },
  { title: "Parks and Recreation", type: "Series", year: "2009-2015" },
  { title: "Brooklyn Nine-Nine", type: "Series", year: "2013-2021" },
  { title: "Arrested Development", type: "Series", year: "2003-2019" },
  { title: "Community", type: "Series", year: "2009-2015" },
  { title: "30 Rock", type: "Series", year: "2006-2013" },
  { title: "It's Always Sunny in Philadelphia", type: "Series", year: "2005-" },
  { title: "Curb Your Enthusiasm", type: "Series", year: "2000-2024" },
  { title: "Frasier", type: "Series", year: "1993-2004" },
  { title: "The Simpsons", type: "Series", year: "1989-" },
  { title: "South Park", type: "Series", year: "1997-" },
  { title: "Rick and Morty", type: "Series", year: "2013-" },
  { title: "BoJack Horseman", type: "Series", year: "2014-2020" },
  { title: "Avatar: The Last Airbender", type: "Series", year: "2005-2008" },
  { title: "The Legend of Korra", type: "Series", year: "2012-2014" },
  { title: "Arcane", type: "Series", year: "2021-" },
  { title: "Invincible", type: "Series", year: "2021-" },
  { title: "Bluey", type: "Series", year: "2018-" },
  { title: "Planet Earth", type: "Series", year: "2006" },
  { title: "Planet Earth II", type: "Series", year: "2016" },
  { title: "Blue Planet", type: "Series", year: "2001" },
  { title: "Blue Planet II", type: "Series", year: "2017" },
  { title: "Our Planet", type: "Series", year: "2019" },
  { title: "The Night Manager", type: "Series", year: "2016" },
  { title: "The Queen's Gambit", type: "Series", year: "2020" },
  { title: "Mindhunter", type: "Series", year: "2017-2019" },
  { title: "Ozark", type: "Series", year: "2017-2022" },
  { title: "Narcos", type: "Series", year: "2015-2017" },
  { title: "Narcos: Mexico", type: "Series", year: "2018-2021" },
  { title: "The Handmaid's Tale", type: "Series", year: "2017-" },
  { title: "The Leftovers", type: "Series", year: "2014-2017" },
  { title: "Lost", type: "Series", year: "2004-2010" },
  { title: "The Walking Dead", type: "Series", year: "2010-2022" },
  { title: "The Boys", type: "Series", year: "2019-" },
  { title: "Peaky Blinders", type: "Series", year: "2013-2022" },
  { title: "Sherlock", type: "Series", year: "2010-2017" },
  { title: "Luther", type: "Series", year: "2010-2019" },
  { title: "Broadchurch", type: "Series", year: "2013-2017" },
  { title: "Killing Eve", type: "Series", year: "2018-2022" },
  { title: "Fleabag", type: "Series", year: "2016-2019" },
  { title: "The Marvelous Mrs. Maisel", type: "Series", year: "2017-2023" },
  { title: "The Good Place", type: "Series", year: "2016-2020" },
  { title: "Black Sails", type: "Series", year: "2014-2017" },
  { title: "Vikings", type: "Series", year: "2013-2020" },
  { title: "The Last Kingdom", type: "Series", year: "2015-2022" },
  { title: "House of the Dragon", type: "Series", year: "2022-" },
  { title: "The Witcher", type: "Series", year: "2019-" },
  { title: "Dark", type: "Series", year: "2017-2020" },
  { title: "Money Heist", type: "Series", year: "2017-2021" },
  { title: "Squid Game", type: "Series", year: "2021-" },
  { title: "The Good Wife", type: "Series", year: "2009-2016" },
  { title: "The Good Fight", type: "Series", year: "2017-2022" },
  { title: "House", type: "Series", year: "2004-2012" },
  { title: "Madam Secretary", type: "Series", year: "2014-2019" },
  { title: "The Newsroom", type: "Series", year: "2012-2014" },
  { title: "Better Things", type: "Series", year: "2016-2022" },
  { title: "Atlanta", type: "Series", year: "2016-2022" },
  { title: "Barry", type: "Series", year: "2018-2023" },
  { title: "Silicon Valley", type: "Series", year: "2014-2019" },
  { title: "The IT Crowd", type: "Series", year: "2006-2013" },
  { title: "Ted", type: "Series", year: "2024-" },
  { title: "The Undoing", type: "Series", year: "2020" },
  { title: "Mare of Easttown", type: "Series", year: "2021" },
  { title: "Sharp Objects", type: "Series", year: "2018" },
  { title: "Big Mouth", type: "Series", year: "2017-" },
  { title: "The Venture Bros.", type: "Series", year: "2003-2018" },
  { title: "King of the Hill", type: "Series", year: "1997-2010" },
  { title: "Futurama", type: "Series", year: "1999-" },
  { title: "Saturday Night Live", type: "Series", year: "1975-" },
  { title: "Top Boy", type: "Series", year: "2011-2023" },
  { title: "The O.C.", type: "Series", year: "2003-2007" },
  { title: "Friday Night Lights", type: "Series", year: "2006-2011" },
  { title: "The Shield", type: "Series", year: "2002-2008" },
  { title: "Justified", type: "Series", year: "2010-2015" },
  { title: "The OA", type: "Series", year: "2016-2019" },
  { title: "Station Eleven", type: "Series", year: "2021-2022" },
  { title: "The Peripheral", type: "Series", year: "2022" },
  { title: "Silo", type: "Series", year: "2023-" },
  { title: "The Penguin", type: "Series", year: "2024" },
  { title: "Slow Horses", type: "Series", year: "2022-" },
  { title: "Only Murders in the Building", type: "Series", year: "2021-" },
  { title: "The Morning Show", type: "Series", year: "2019-" },
  { title: "Halt and Catch Fire", type: "Series", year: "2014-2017" },
  { title: "The X-Files", type: "Series", year: "1993-2018" },
  { title: "Twin Peaks", type: "Series", year: "1990-2017" },
  { title: "The Twilight Zone", type: "Series", year: "1959-1964" },
  { title: "Doctor Who", type: "Series", year: "2005-" },

  /* +100 DOCUMENTARIES */
  { title: "Free Solo", type: "Documentary", year: "2018" },
  { title: "The Last Dance", type: "Documentary", year: "2020" },
  { title: "Won't You Be My Neighbor?", type: "Documentary", year: "2018" },
  { title: "13th", type: "Documentary", year: "2016" },
  { title: "Icarus", type: "Documentary", year: "2017" },
  { title: "Amy", type: "Documentary", year: "2015" },
  { title: "Man on Wire", type: "Documentary", year: "2008" },
  { title: "Searching for Sugar Man", type: "Documentary", year: "2012" },
  { title: "The Fog of War", type: "Documentary", year: "2003" },
  { title: "Grizzly Man", type: "Documentary", year: "2005" },
  { title: "Bowling for Columbine", type: "Documentary", year: "2002" },
  { title: "Super Size Me", type: "Documentary", year: "2004" },
  { title: "Jiro Dreams of Sushi", type: "Documentary", year: "2011" },
  { title: "Exit Through the Gift Shop", type: "Documentary", year: "2010" },
  { title: "The Social Dilemma", type: "Documentary", year: "2020" },
  { title: "Fyre", type: "Documentary", year: "2019" },
  { title: "Tiger King", type: "Documentary", year: "2020" },
  { title: "Making a Murderer", type: "Documentary", year: "2015-2018" },
  { title: "The Jinx", type: "Documentary", year: "2015" },
  { title: "Wild Wild Country", type: "Documentary", year: "2018" },
  { title: "O.J.: Made in America", type: "Documentary", year: "2016" },
  { title: "The Cove", type: "Documentary", year: "2009" },
  { title: "Blackfish", type: "Documentary", year: "2013" },
  { title: "The Act of Killing", type: "Documentary", year: "2012" },
  { title: "The Look of Silence", type: "Documentary", year: "2014" },
  { title: "Citizenfour", type: "Documentary", year: "2014" },
  { title: "Enron: The Smartest Guys in the Room", type: "Documentary", year: "2005" },
  { title: "Inside Job", type: "Documentary", year: "2010" },
  { title: "March of the Penguins", type: "Documentary", year: "2005" },
  { title: "Touching the Void", type: "Documentary", year: "2003" },
  { title: "The Rescue", type: "Documentary", year: "2021" },
  { title: "Fire of Love", type: "Documentary", year: "2022" },
  { title: "Navalny", type: "Documentary", year: "2022" },
  { title: "Summer of Soul", type: "Documentary", year: "2021" },
  { title: "The Beatles: Get Back", type: "Documentary", year: "2021" },
  { title: "Senna", type: "Documentary", year: "2010" },
  { title: "Restrepo", type: "Documentary", year: "2010" },
  { title: "They Shall Not Grow Old", type: "Documentary", year: "2018" },
  { title: "The Vietnam War", type: "Documentary", year: "2017" },
  { title: "The Civil War", type: "Documentary", year: "1990" },
  { title: "Cosmos: A Personal Voyage", type: "Documentary", year: "1980" },
  { title: "Cosmos: A Spacetime Odyssey", type: "Documentary", year: "2014" },
  { title: "Cosmos: Possible Worlds", type: "Documentary", year: "2020" },
  { title: "Our Universe", type: "Documentary", year: "2022" },
  { title: "Night on Earth", type: "Documentary", year: "2020" },
  { title: "My Octopus Teacher", type: "Documentary", year: "2020" },
  { title: "Fantastic Fungi", type: "Documentary", year: "2019" },
  { title: "The Biggest Little Farm", type: "Documentary", year: "2018" },
  { title: "Kedi", type: "Documentary", year: "2016" },
  { title: "Honeyland", type: "Documentary", year: "2019" },
  { title: "The Alpinist", type: "Documentary", year: "2021" },
  { title: "The Dawn Wall", type: "Documentary", year: "2017" },
  { title: "The Deepest Breath", type: "Documentary", year: "2023" },
  { title: "The Imposter", type: "Documentary", year: "2012" },
  { title: "Three Identical Strangers", type: "Documentary", year: "2018" },
  { title: "The King of Kong: A Fistful of Quarters", type: "Documentary", year: "2007" },
  { title: "Jiro: Dreams of Sushi", type: "Documentary", year: "2011" },
  { title: "The Staircase", type: "Documentary", year: "2004-2018" },
  { title: "The Thin Blue Line", type: "Documentary", year: "1988" },
  { title: "Hoop Dreams", type: "Documentary", year: "1994" },
  { title: "Paris Is Burning", type: "Documentary", year: "1990" },
  { title: "The Great Hack", type: "Documentary", year: "2019" },
  { title: "American Factory", type: "Documentary", year: "2019" },
  { title: "The Keepers", type: "Documentary", year: "2017" },
  { title: "Evil Genius", type: "Documentary", year: "2018" },
  { title: "Don't F**k with Cats", type: "Documentary", year: "2019" },
  { title: "The Tinder Swindler", type: "Documentary", year: "2022" },
  { title: "The Inventor: Out for Blood in Silicon Valley", type: "Documentary", year: "2019" },
  { title: "The Great British Bake Off: An Extra Slice", type: "Documentary", year: "2014-" },
  { title: "Get Me Roger Stone", type: "Documentary", year: "2017" },
  { title: "The Square", type: "Documentary", year: "2013" },
  { title: "Winter on Fire", type: "Documentary", year: "2015" },
  { title: "The Dissident", type: "Documentary", year: "2020" },
  { title: "The Edge of Democracy", type: "Documentary", year: "2019" },
  { title: "Crip Camp", type: "Documentary", year: "2020" },
  { title: "Collective", type: "Documentary", year: "2019" },
  { title: "For Sama", type: "Documentary", year: "2019" },
  { title: "Athlete A", type: "Documentary", year: "2020" },
  { title: "The Last Breath", type: "Documentary", year: "2019" },
  { title: "McMillions", type: "Documentary", year: "2020" },
  { title: "The Vow", type: "Documentary", year: "2020-2022" },
  { title: "Allen v. Farrow", type: "Documentary", year: "2021" },
  { title: "The Great British Baking Show", type: "Documentary", year: "2010-" },
  { title: "Chef's Table", type: "Documentary", year: "2015-" },
  { title: "Abstract: The Art of Design", type: "Documentary", year: "2017-2019" },
  { title: "Explained", type: "Documentary", year: "2018-" },
  { title: "Last Chance U", type: "Documentary", year: "2016-2020" },
  { title: "Formula 1: Drive to Survive", type: "Documentary", year: "2019-" },
  { title: "Sunderland 'Til I Die", type: "Documentary", year: "2018-2020" },
  { title: "The Last Czars", type: "Documentary", year: "2019" },
  { title: "The People v. O.J. Simpson: American Crime Story (Behind the Scenes)", type: "Documentary", year: "2016" },
  { title: "The Secrets of Hillsong", type: "Documentary", year: "2023" },
  { title: "The Games That Changed Us", type: "Documentary", year: "2018" },
  { title: "Beckham", type: "Documentary", year: "2023" },
  { title: "Sly", type: "Documentary", year: "2023" },
  { title: "Arnold", type: "Documentary", year: "2023" },
  { title: "Pamela, A Love Story", type: "Documentary", year: "2023" },
  { title: "The Most Unknown", type: "Documentary", year: "2018" },
  { title: "The Farthest", type: "Documentary", year: "2017" },
  { title: "Apollo 11", type: "Documentary", year: "2019" },
  { title: "The Last Man on the Moon", type: "Documentary", year: "2014" },
  { title: "The Search for General Tso", type: "Documentary", year: "2014" },
  { title: "RBG", type: "Documentary", year: "2018" },
  { title: "The Punk Singer", type: "Documentary", year: "2013" },
  { title: "20 Feet from Stardom", type: "Documentary", year: "2013" },
  { title: "The Salt of the Earth", type: "Documentary", year: "2014" },
  { title: "I Am Not Your Negro", type: "Documentary", year: "2016" },
  { title: "Stories We Tell", type: "Documentary", year: "2012" },
  { title: "Dear Zachary: A Letter to a Son About His Father", type: "Documentary", year: "2008" },
  { title: "The Inventor", type: "Documentary", year: "2019" },
       { title: "12 Angry Men", type: "Movie", year: "1957" },
  { title: "12 Years a Slave", type: "Movie", year: "2013" },
  { title: "2001: A Space Odyssey", type: "Movie", year: "1968" },
  { title: "A Few Good Men", type: "Movie", year: "1992" },
  { title: "A History of Violence", type: "Movie", year: "2005" },
  { title: "A Serious Man", type: "Movie", year: "2009" },
  { title: "Adaptation.", type: "Movie", year: "2002" },
  { title: "All Quiet on the Western Front", type: "Movie", year: "2022" },
  { title: "Anatomy of a Fall", type: "Movie", year: "2023" },
  { title: "Annihilation", type: "Movie", year: "2018" },
  { title: "Before Sunset", type: "Movie", year: "2004" },
  { title: "Before Midnight", type: "Movie", year: "2013" },
  { title: "Bird Box", type: "Movie", year: "2018" },
  { title: "BlacKkKlansman", type: "Movie", year: "2018" },
  { title: "Blade", type: "Movie", year: "1998" },
  { title: "Boogie Nights", type: "Movie", year: "1997" },
  { title: "Brazil", type: "Movie", year: "1985" },
  { title: "Burn After Reading", type: "Movie", year: "2008" },
  { title: "City of God", type: "Movie", year: "2002" },
  { title: "Children of Men", type: "Movie", year: "2006" },
  { title: "Collateral", type: "Movie", year: "2004" },
  { title: "Contact", type: "Movie", year: "1997" },
  { title: "District 9", type: "Movie", year: "2009" },
  { title: "Eighth Grade", type: "Movie", year: "2018" },
  { title: "Edge of Tomorrow", type: "Movie", year: "2014" },
  { title: "Enemy", type: "Movie", year: "2013" },
  { title: "Fight the Power", type: "Movie", year: "1989" }, // Do the Right Thing alt title? remove if you want
  { title: "Field of Dreams", type: "Movie", year: "1989" },
  { title: "First Man", type: "Movie", year: "2018" },
  { title: "Good Time", type: "Movie", year: "2017" },
  { title: "Gran Torino", type: "Movie", year: "2008" },
  { title: "Hell or High Water", type: "Movie", year: "2016" },
  { title: "Hot Fuzz", type: "Movie", year: "2007" },
  { title: "In Bruges", type: "Movie", year: "2008" },
  { title: "Joker", type: "Movie", year: "2019" },
  { title: "LA Confidential", type: "Movie", year: "1997" },
  { title: "Logan", type: "Movie", year: "2017" },
  { title: "Looper", type: "Movie", year: "2012" },
  { title: "Lost in Translation", type: "Movie", year: "2003" },
  { title: "Manchester by the Sea", type: "Movie", year: "2016" },
  { title: "Memento", type: "Movie", year: "2000" },
  { title: "Nightcrawler", type: "Movie", year: "2014" },
  { title: "Nope", type: "Movie", year: "2022" },
  { title: "Oldboy", type: "Movie", year: "2003" },
  { title: "Primal Fear", type: "Movie", year: "1996" },
  { title: "Prisoners", type: "Movie", year: "2013" },
  { title: "Requiem for a Dream", type: "Movie", year: "2000" },
  { title: "Rush", type: "Movie", year: "2013" },
  { title: "The Big Short", type: "Movie", year: "2015" },
  { title: "The Florida Project", type: "Movie", year: "2017" },
  { title: "The Founder", type: "Movie", year: "2016" },
  { title: "The Lighthouse", type: "Movie", year: "2019" },
  { title: "The Nice Guys", type: "Movie", year: "2016" },
  { title: "The Pianist", type: "Movie", year: "2002" },
  { title: "The Wrestler", type: "Movie", year: "2008" },
  { title: "There Will Be Blood", type: "Movie", year: "2007" },
  { title: "Trainspotting", type: "Movie", year: "1996" },
  { title: "True Romance", type: "Movie", year: "1993" },
  { title: "Uncut Gems", type: "Movie", year: "2019" },
  { title: "Wind River", type: "Movie", year: "2017" },
  { title: "Zombieland", type: "Movie", year: "2009" },

  // Teen-friendly, adult-watchable "family" picks
  { title: "Spider-Man: Across the Spider-Verse", type: "Movie", year: "2023" },
  { title: "The Incredibles", type: "Movie", year: "2004" },
  { title: "The Incredibles 2", type: "Movie", year: "2018" },
  { title: "Ratatouille", type: "Movie", year: "2007" },
  { title: "WALL-E", type: "Movie", year: "2008" },
  { title: "Inside Out 2", type: "Movie", year: "2024" },
  { title: "The Iron Giant", type: "Movie", year: "1999" },
  { title: "Coraline", type: "Movie", year: "2009" },
  { title: "Kubo and the Two Strings", type: "Movie", year: "2016" },
  { title: "Paddington", type: "Movie", year: "2014" },
  { title: "Paddington 2", type: "Movie", year: "2017" },
  { title: "The Mitchells vs. the Machines", type: "Movie", year: "2021" },
  { title: "How to Train Your Dragon", type: "Movie", year: "2010" },
  { title: "How to Train Your Dragon 2", type: "Movie", year: "2014" },
  { title: "How to Train Your Dragon: The Hidden World", type: "Movie", year: "2019" },
  { title: "Shrek", type: "Movie", year: "2001" },
  { title: "Shrek 2", type: "Movie", year: "2004" },
  { title: "The Lego Movie", type: "Movie", year: "2014" },
  { title: "The Lego Batman Movie", type: "Movie", year: "2017" },
  { title: "A Goofy Movie", type: "Movie", year: "1995" },

  // MORE SERIES
  { title: "Breaking Bad", type: "Series", year: "2008-2013" },
  { title: "Better Things", type: "Series", year: "2016-2022" },
  { title: "Barry", type: "Series", year: "2018-2023" },
  { title: "The Bear", type: "Series", year: "2022-" },
  { title: "Severance", type: "Series", year: "2022-" },
  { title: "The Last of Us", type: "Series", year: "2023-" },
  { title: "Slow Horses", type: "Series", year: "2022-" },
  { title: "Only Murders in the Building", type: "Series", year: "2021-" },
  { title: "The Americans", type: "Series", year: "2013-2018" },
  { title: "The Crown", type: "Series", year: "2016-2023" },
  { title: "The West Wing", type: "Series", year: "1999-2006" },
  { title: "The Newsroom", type: "Series", year: "2012-2014" },
  { title: "Mare of Easttown", type: "Series", year: "2021" },
  { title: "The Night Manager", type: "Series", year: "2016" },
  { title: "Mindhunter", type: "Series", year: "2017-2019" },
  { title: "Ozark", type: "Series", year: "2017-2022" },
  { title: "Peaky Blinders", type: "Series", year: "2013-2022" },
  { title: "Dark", type: "Series", year: "2017-2020" },
  { title: "Squid Game", type: "Series", year: "2021-" },
  { title: "The Queen's Gambit", type: "Series", year: "2020" },
  { title: "The Handmaid's Tale", type: "Series", year: "2017-" },
  { title: "The Boys", type: "Series", year: "2019-" },
  { title: "The Expanse", type: "Series", year: "2015-2022" },
  { title: "Mr. Robot", type: "Series", year: "2015-2019" },
  { title: "Halt and Catch Fire", type: "Series", year: "2014-2017" },
  { title: "Friday Night Lights", type: "Series", year: "2006-2011" },
  { title: "Justified", type: "Series", year: "2010-2015" },
  { title: "The Shield", type: "Series", year: "2002-2008" },
  { title: "The X-Files", type: "Series", year: "1993-2018" },
  { title: "Twin Peaks", type: "Series", year: "1990-2017" },
  { title: "The Twilight Zone", type: "Series", year: "1959-1964" },
  { title: "House of the Dragon", type: "Series", year: "2022-" },
  { title: "The Witcher", type: "Series", year: "2019-" },
  { title: "Andor", type: "Series", year: "2022-" },
  { title: "The Mandalorian", type: "Series", year: "2019-" },
  { title: "Curb Your Enthusiasm", type: "Series", year: "2000-2024" },
  { title: "Arrested Development", type: "Series", year: "2003-2019" },
  { title: "Parks and Recreation", type: "Series", year: "2009-2015" },
  { title: "Brooklyn Nine-Nine", type: "Series", year: "2013-2021" },
  { title: "Community", type: "Series", year: "2009-2015" },
  { title: "30 Rock", type: "Series", year: "2006-2013" },
  { title: "The IT Crowd", type: "Series", year: "2006-2013" },
  { title: "Fleabag", type: "Series", year: "2016-2019" },
  { title: "Atlanta", type: "Series", year: "2016-2022" },
  { title: "Silicon Valley", type: "Series", year: "2014-2019" },
  { title: "The Marvelous Mrs. Maisel", type: "Series", year: "2017-2023" },
  { title: "The Sopranos", type: "Series", year: "1999-2007" }, // ok if duplicate
  { title: "True Detective", type: "Series", year: "2014-" },

  // MORE DOCUMENTARIES
  { title: "Apollo 11", type: "Documentary", year: "2019" },
  { title: "Free Solo", type: "Documentary", year: "2018" },
  { title: "The Rescue", type: "Documentary", year: "2021" },
  { title: "Fire of Love", type: "Documentary", year: "2022" },
  { title: "My Octopus Teacher", type: "Documentary", year: "2020" },
  { title: "The Social Dilemma", type: "Documentary", year: "2020" },
  { title: "Icarus", type: "Documentary", year: "2017" },
  { title: "13th", type: "Documentary", year: "2016" },
  { title: "Citizenfour", type: "Documentary", year: "2014" },
  { title: "Inside Job", type: "Documentary", year: "2010" },
  { title: "The Fog of War", type: "Documentary", year: "2003" },
  { title: "Man on Wire", type: "Documentary", year: "2008" },
  { title: "Searching for Sugar Man", type: "Documentary", year: "2012" },
  { title: "Won't You Be My Neighbor?", type: "Documentary", year: "2018" },
  { title: "Amy", type: "Documentary", year: "2015" },
  { title: "Exit Through the Gift Shop", type: "Documentary", year: "2010" },
  { title: "Jiro Dreams of Sushi", type: "Documentary", year: "2011" },
  { title: "Three Identical Strangers", type: "Documentary", year: "2018" },
  { title: "The Imposter", type: "Documentary", year: "2012" },
  { title: "The Cove", type: "Documentary", year: "2009" },
  { title: "Blackfish", type: "Documentary", year: "2013" },
  { title: "O.J.: Made in America", type: "Documentary", year: "2016" },
  { title: "The Act of Killing", type: "Documentary", year: "2012" },
  { title: "The Look of Silence", type: "Documentary", year: "2014" },
  { title: "Hoop Dreams", type: "Documentary", year: "1994" },
  { title: "Paris Is Burning", type: "Documentary", year: "1990" },
  { title: "The Thin Blue Line", type: "Documentary", year: "1988" },
  { title: "They Shall Not Grow Old", type: "Documentary", year: "2018" },
  { title: "The Vietnam War", type: "Documentary", year: "2017" },
  { title: "Cosmos: A Spacetime Odyssey", type: "Documentary", year: "2014" },
  { title: "Our Planet", type: "Documentary", year: "2019" },
  { title: "Night on Earth", type: "Documentary", year: "2020" },
  { title: "Fantastic Fungi", type: "Documentary", year: "2019" },
  { title: "The Biggest Little Farm", type: "Documentary", year: "2018" },
  { title: "Honeyland", type: "Documentary", year: "2019" },
  { title: "The Alpinist", type: "Documentary", year: "2021" },
  { title: "The Dawn Wall", type: "Documentary", year: "2017" },
  { title: "The Deepest Breath", type: "Documentary", year: "2023" },
  { title: "Navalny", type: "Documentary", year: "2022" },
  { title: "Summer of Soul", type: "Documentary", year: "2021" },
  { title: "The Beatles: Get Back", type: "Documentary", year: "2021" },
  { title: "Senna", type: "Documentary", year: "2010" },
  { title: "Restrepo", type: "Documentary", year: "2010" },
  { title: "Crip Camp", type: "Documentary", year: "2020" },
  { title: "American Factory", type: "Documentary", year: "2019" },
  { title: "The Great Hack", type: "Documentary", year: "2019" },
  { title: "Fyre", type: "Documentary", year: "2019" },
  { title: "The Tinder Swindler", type: "Documentary", year: "2022" },
  { title: "Chef's Table", type: "Documentary", year: "2015-" },
  { title: "Abstract: The Art of Design", type: "Documentary", year: "2017-2019" },
  { title: "Explained", type: "Documentary", year: "2018-" },
  { title: "Formula 1: Drive to Survive", type: "Documentary", year: "2019-" },
  { title: "Beckham", type: "Documentary", year: "2023" },
  { title: "Arnold", type: "Documentary", year: "2023" },
  { title: "Sly", type: "Documentary", year: "2023" },
  { title: "Pamela, A Love Story", type: "Documentary", year: "2023" }
];
